Repository mit-cml/appinventor-sources, pull requests merged in 2018-05, with the labels that each got.

#1218 Load all jars in launch-buildserver script with wildcard
  appinventor/misc/buildserver/launch-buildserver
Labels: affects: master, bug, pull request: needs reply to review

#1231 Update components.js
  appinventor/blocklyeditor/src/blocks/components.js
Labels: affects: master, bug, pull request: in review

#1239 Update How Build Server progress is reported.
  appinventor/appengine/src/com/google/appinventor/server/ReceiveBuildServlet.java
  appinventor/appengine/src/com/google/appinventor/server/project/youngandroid/YoungAndroidProjectService.java
  appinventor/appengine/src/com/google/appinventor/server/storage/ObjectifyStorageIo.java
  appinventor/appengine/src/com/google/appinventor/server/storage/StorageIo.java
  appinventor/buildserver/src/com/google/appinventor/buildserver/BuildServer.java
  appinventor/buildserver/src/com/google/appinventor/buildserver/Compiler.java
  appinventor/buildserver/src/com/google/appinventor/buildserver/Main.java
  appinventor/buildserver/src/com/google/appinventor/buildserver/ProjectBuilder.java
  appinventor/buildserver/tests/com/google/appinventor/buildserver/CompilerTest.java
Labels: pull request: needs review

#1241 Add A Shutdown Hook for the Buildserver
  appinventor/buildserver/src/com/google/appinventor/buildserver/BuildServer.java
Labels: pull request: needs reply to review
