Repository mit-cml/appinventor-sources, pull requests merged in 2018-11, with the labels that each got.

#1402 Trim extraneous whitespace from base64-encoded aia
  appinventor/appengine/src/com/google/appinventor/server/ProjectServiceImpl.java
Labels: affects: master, bug, pull request: needs review

#1406 Stop propagation of mouse events on warning toggle button
  appinventor/blocklyeditor/src/warningIndicator.js
Labels: affects: master, bug, pull request: needs review

#1400 Changes for Java 8 and the Buildservers
  appinventor/appengine/src/com/google/appinventor/server/project/youngandroid/YoungAndroidProjectService.java
  appinventor/appengine/war/WEB-INF/appengine-web.xml
  appinventor/buildserver/src/com/google/appinventor/buildserver/BuildServer.java
Labels: affects: master, on ai2-test, pull request: needs reply to review

#1411 Fix clearing of MockFeatureCollection when Source is None
  appinventor/appengine/src/com/google/appinventor/client/editor/simple/components/MockFeatureCollection.java
Labels: affects: master, bug, pull request: needs review

#1409 Remove BOM from GeoJSON files
  appinventor/appengine/src/com/google/appinventor/client/editor/simple/components/MockFeatureCollection.java
  appinventor/components/src/com/google/appinventor/components/runtime/MapFeatureContainerBase.java
  appinventor/components/tests/com/google/appinventor/components/runtime/FeatureCollectionTest.java
Labels: affects: master, affects: ucr, bug, pull request: needs review

#1418 Fire permission granted without posting runnable if we have permission
  appinventor/components/src/com/google/appinventor/components/runtime/Form.java
Labels: affects: ucr, bug, pull request: needs review

#1373 Bugfix to AARLibrary
  appinventor/buildserver/src/com/google/appinventor/buildserver/util/AARLibrary.java
Labels: affects: master, bug, pull request: ready to push to Gerrit

#1398 Reset min size of button with images
  appinventor/components/src/com/google/appinventor/components/runtime/ButtonBase.java
  appinventor/components/src/com/google/appinventor/components/runtime/util/KitkatUtil.java
  appinventor/components/src/com/google/appinventor/components/runtime/util/TextViewUtil.java
Labels: affects: ucr, bug, on ai2-test, pull request: needs review

#1115 Replace use of isRenderingOn with Blockly event management
  appinventor/blocklyeditor/src/events.js
  appinventor/blocklyeditor/src/savefile.js
  appinventor/blocklyeditor/src/versioning.js
  appinventor/blocklyeditor/src/workspace_svg.js
  appinventor/blocklyeditor/src/xml.js
  appinventor/blocklyeditor/tests/com/google/appinventor/blocklyeditor/moleMashTest.js
Labels: affects: master, bug, pull request: needs review

#1380 Force MockCircle default position to (0, 0)
  appinventor/appengine/src/com/google/appinventor/client/editor/simple/components/MockCircle.java
Labels: affects: master, bug, pull request: needs review

#1424 Make ScrollView fill viewport on Nougat and higher
  appinventor/components/src/com/google/appinventor/components/runtime/Form.java
Labels: affects: ucr, bug, pull request: needs review

#1434 Make sure we throw FileNotFound in FileUtil
  appinventor/components/src/com/google/appinventor/components/runtime/util/FileUtil.java
Labels: affects: ucr, bug, pull request: needs reply to review

#1377 1318 Button behavior pre and post-Lollipop
  appinventor/components/src/com/google/appinventor/components/runtime/ButtonBase.java
Labels: affects: master, bug, enhancement, pull request: needs review

#1419 Add syntax rule for old define-form form
  appinventor/buildserver/src/com/google/appinventor/buildserver/resources/runtime.scm
Labels: affects: ucr, bug, pull request: needs review

#1441 Enable debug panel logging only when admin
  appinventor/appengine/src/com/google/appinventor/client/output/OdeLog.java
Labels: affects: master, bug, pull request: needs review
