Repository mit-cml/appinventor-sources, pull requests merged in 2018-07, with the labels that each got.

#1297 Reference #!null directly instead
  appinventor/buildserver/src/com/google/appinventor/buildserver/resources/runtime.scm
Labels: pull request: needs review

#1266 Fix for #1144
  appinventor/appengine/src/com/google/appinventor/server/project/youngandroid/YoungAndroidProjectService.java
  appinventor/appengine/tests/com/google/appinventor/server/project/youngandroid/YoungAndroidProjectServiceTest.java
Labels: affects: master, bug, pull request: needs reply to review

#1288 Fix crash due to ClassCastException in Slider
  appinventor/components/src/com/google/appinventor/components/runtime/Slider.java
Labels: affects: ucr, bug, pull request: needs review

#1247 Enforce that block definitions exist for designer properties
  appinventor/blocklyeditor/src/generators/yail.js
  appinventor/components/src/com/google/appinventor/components/runtime/GameClient.java
  appinventor/components/src/com/google/appinventor/components/scripts/ComponentProcessor.java
Labels: affects: master, bug, pull request: needs review

#1227 Added LoadingDialogMessage and ShowLoadingDialog properties to Fusiontables component
  appinventor/appengine/src/com/google/appinventor/client/OdeMessages.java
  appinventor/appengine/src/com/google/appinventor/client/youngandroid/YoungAndroidFormUpgrader.java
  appinventor/blocklyeditor/src/versioning.js
  appinventor/components/src/com/google/appinventor/components/common/YaVersion.java
  appinventor/components/src/com/google/appinventor/components/runtime/FusiontablesControl.java
  appinventor/docs/reference/components/storage.html
Labels: affects: ucr, enhancement, pull request: needs review

#1300 Add missing annotation for setWebViewString
  appinventor/components/src/com/google/appinventor/components/runtime/WebViewer.java
Labels: affects: ucr, pull request: in review, technical debt

#1305 DataChanged (CloudDB) now handles images
  appinventor/components/src/com/google/appinventor/components/runtime/CloudDB.java
  appinventor/components/src/com/google/appinventor/components/runtime/util/CloudDBJedisListener.java
  appinventor/components/src/com/google/appinventor/components/runtime/util/JsonUtil.java
Labels: affects: ucr, bug, pull request: in review

#1307 Update CloudDB.StoreValue documentation to discuss use with files
  appinventor/docs/reference/components/experimental.html
Labels: affects: ucr, documentation, pull request: needs review
