Repository mit-cml/appinventor-sources, pull requests merged in 2018-02, with the labels that each got.

#1156 Fix spelling
  appinventor/appengine/src/com/google/appinventor/client/OdeMessages.java
Labels: affects: master, bug, pull request: needs review

#1117 Improve Chinese translation of Highlight Procedure
  appinventor/blocklyeditor/src/msg/zh_cn/_messages.js
Labels: affects: master, enhancement, pull request: needs review

#1147 Added UrlDecode function
  appinventor/appengine/src/com/google/appinventor/client/OdeMessages.java
  appinventor/appengine/src/com/google/appinventor/client/youngandroid/YoungAndroidFormUpgrader.java
  appinventor/blocklyeditor/src/versioning.js
  appinventor/components/src/com/google/appinventor/components/common/YaVersion.java
  appinventor/components/src/com/google/appinventor/components/runtime/Web.java
  appinventor/docs/reference/components/connectivity.html
Labels: affects: ucr, enhancement, pull request: ready to push to Gerrit

#1111 Adding a namespace for TinyDB in the companion
  appinventor/appengine/src/com/google/appinventor/client/OdeMessages.java
  appinventor/appengine/src/com/google/appinventor/client/youngandroid/YoungAndroidFormUpgrader.java
  appinventor/blocklyeditor/src/versioning.js
  appinventor/components/src/com/google/appinventor/components/common/YaVersion.java
  appinventor/components/src/com/google/appinventor/components/runtime/TinyDB.java
  appinventor/docs/reference/components/storage.html
Labels: affects: ucr, enhancement, pull request: ready to push to Gerrit
