Repository mit-cml/appinventor-sources, pull requests merged in 2018-12, with the labels that each got.

#1447 Fix null pointer when logging before user info available
  appinventor/appengine/src/com/google/appinventor/client/output/OdeLog.java
Labels: affects: master, bug, pull request: needs review

#1458 Fix GeoJSON parsing in MockFeatureCollection
  appinventor/appengine/src/com/google/appinventor/client/editor/simple/components/MockFeatureCollection.java
Labels: affects: master, pull request: needs review, regression

#1464 Make Backpack open in Firefox
  appinventor/blocklyeditor/src/backpack.js
Labels: affects: master, bug, pull request: needs review

#1468 Fix connection DB bug when workspace contains blocks with errors
  appinventor/blocklyeditor/src/connection_db.js
  appinventor/blocklyeditor/src/workspace_svg.js
Labels: affects: master, pull request: needs review, regression

#1469 Stop resetting list of connections when errors occur
  appinventor/blocklyeditor/src/workspace_svg.js
Labels: affects: master, pull request: needs review, regression

#1443 Fix handling of Map.ZoomLevel when animating changes
  appinventor/components/src/com/google/appinventor/components/runtime/util/NativeOpenStreetMapController.java
Labels: affects: master, bug, pull request: needs reply to review, pull request: needs review

#1472 Fix PlayApp build on Windows due to wrong slash
  appinventor/buildserver/src/com/google/appinventor/buildserver/Compiler.java
Labels: affects: master, pull request: needs review, regression

#1476 Fix backpack icon state with multiple screens
  appinventor/appengine/src/com/google/appinventor/client/editor/youngandroid/BlocklyPanel.java
  appinventor/blocklyeditor/src/backpack.js
  appinventor/blocklyeditor/src/workspace_svg.js
Labels: affects: master, bug, pull request: needs review

#1442 Implement versionName and dateBuilt annotation fields
  appinventor/appengine/src/com/google/appinventor/client/OdeMessages.java
  appinventor/appengine/src/com/google/appinventor/client/editor/simple/ComponentDatabase.java
  appinventor/appengine/src/com/google/appinventor/client/editor/simple/palette/ComponentHelpWidget.java
  appinventor/appengine/src/com/google/appinventor/client/editor/simple/palette/SimpleComponentDescriptor.java
  appinventor/appengine/src/com/google/appinventor/client/editor/youngandroid/palette/YoungAndroidPalettePanel.java
  appinventor/appengine/src/com/google/appinventor/shared/simple/ComponentDatabaseInterface.java
  appinventor/components/src/com/google/appinventor/components/annotations/DesignerComponent.java
  appinventor/components/src/com/google/appinventor/components/scripts/ComponentDescriptorGenerator.java
  appinventor/components/src/com/google/appinventor/components/scripts/ComponentProcessor.java
Labels: affects: master, feature request, pull request: needs reply to review

#1483 Chunk large Messages to the Companion
  appinventor/blocklyeditor/src/replmgr.js
Labels: affects: master, bug, pull request: in review

#1423 Added context menu items to show and hide all comments
  appinventor/blocklyeditor/src/msg/en/_messages.js
  appinventor/blocklyeditor/src/workspace_svg.js
Labels: affects: master, feature request, pull request: ready to push to Gerrit

#1420 Restrict the dimensions of AboutScreen for MockForm
  appinventor/appengine/src/com/google/appinventor/client/widgets/properties/TextAreaPropertyEditor.java
Labels: affects: master, bug, pull request: ready to push to Gerrit

#1415 Align labeled text boxes in the middle
  appinventor/appengine/src/com/google/appinventor/client/widgets/LabeledTextBox.java
  appinventor/appengine/war/Ya.css
Labels: affects: master, enhancement, pull request: needs reply to review

#1484 Implement scale bar for Map
  appinventor/appengine/src/com/google/appinventor/client/OdeMessages.java
  appinventor/appengine/src/com/google/appinventor/client/editor/simple/components/MockMap.java
  appinventor/appengine/src/com/google/appinventor/client/editor/simple/components/utils/PropertiesUtil.java
  appinventor/appengine/src/com/google/appinventor/client/editor/youngandroid/properties/YoungAndroidMapScaleUnitsPropertyEditor.java
  appinventor/components/src/com/google/appinventor/components/common/PropertyTypeConstants.java
  appinventor/components/src/com/google/appinventor/components/common/YaVersion.java
  appinventor/components/src/com/google/appinventor/components/runtime/Map.java
  appinventor/components/src/com/google/appinventor/components/runtime/util/DummyMapController.java
  appinventor/components/src/com/google/appinventor/components/runtime/util/ErrorMessages.java
  appinventor/components/src/com/google/appinventor/components/runtime/util/MapFactory.java
  appinventor/components/src/com/google/appinventor/components/runtime/util/NativeOpenStreetMapController.java
  appinventor/components/tests/com/google/appinventor/components/runtime/MapTest.java
  appinventor/docs/reference/components/maps.html
Labels: affects: master, feature request, pull request: needs review

#1486 Make removeDupes run in linear time
  appinventor/blocklyeditor/src/connection_db.js
Labels: affects: master, bug, pull request: needs review

#1489 Implement upgrader for Map version 5
  appinventor/appengine/src/com/google/appinventor/client/youngandroid/YoungAndroidFormUpgrader.java
  appinventor/blocklyeditor/src/versioning.js
Labels: affects: ucr, bug, pull request: needs review

#1490 Fix default background color on SDKs prior to 14
  appinventor/components/src/com/google/appinventor/components/runtime/Form.java
Labels: affects: ucr, bug, pull request: needs review
