Repository mit-cml/appinventor-sources, pull requests merged in 2018-03, with the labels that each got.

#1165 Fixed component type is not translated in generic method
  appinventor/blocklyeditor/src/blocks/components.js
Labels: affects: master, bug, pull request: ready to push to Gerrit

#1160 Update whitelist.py and /remote_api
  appinventor/appengine/src/com/google/appinventor/server/Whitelist.java
  appinventor/appengine/war/WEB-INF/web.xml
  appinventor/misc/whitelist/whitelist.py
Labels: affects: master, enhancement, pull request: ready to push to Gerrit

#1153 Add “Shared Backpack”
  appinventor/appengine/src/com/google/appinventor/client/Ode.java
  appinventor/appengine/src/com/google/appinventor/client/editor/youngandroid/BlocklyPanel.java
  appinventor/appengine/src/com/google/appinventor/server/UserInfoServiceImpl.java
  appinventor/appengine/src/com/google/appinventor/server/cookieauth/CookieAuth.java
  appinventor/appengine/src/com/google/appinventor/server/cookieauth/cookie.proto
  appinventor/appengine/src/com/google/appinventor/server/storage/ObjectifyStorageIo.java
  appinventor/appengine/src/com/google/appinventor/server/storage/StorageIo.java
  appinventor/appengine/src/com/google/appinventor/server/storage/StoredData.java
  appinventor/appengine/src/com/google/appinventor/shared/rpc/user/User.java
  appinventor/appengine/src/com/google/appinventor/shared/rpc/user/UserInfoService.java
  appinventor/appengine/src/com/google/appinventor/shared/rpc/user/UserInfoServiceAsync.java
  appinventor/blocklyeditor/src/backpack.js
Labels: affects: master, feature request, pull request: needs review

#1114 Icon display error when using base64 at any component
  appinventor/appengine/src/com/google/appinventor/client/editor/simple/components/MockComponent.java
Labels: affects: master, bug, pull request: in review

#1171 Remove a vestigial property from CloudDB
  appinventor/appengine/src/com/google/appinventor/client/editor/simple/components/MockCloudDB.java
Labels: affects: master, pull request: needs reply to review

#1182 Remove duplicate line
  appinventor/appengine/src/com/google/appinventor/YaClient.gwt.xml
Labels: affects: master, pull request: needs review

#1047 Implement touch support for designer drag-and-drop
  appinventor/appengine/src/com/google/appinventor/client/editor/simple/components/MockComponent.java
  appinventor/appengine/src/com/google/appinventor/client/editor/simple/palette/SimplePaletteItem.java
  appinventor/appengine/src/com/google/appinventor/client/widgets/dnd/DragSourcePanel.java
  appinventor/appengine/src/com/google/appinventor/client/widgets/dnd/DragSourceSupport.java
Labels: affects: master, pull request: needs review

#1188 Add Documentation for AfterFileSaved Event
  appinventor/docs/reference/components/storage.html
Labels: affects: master, pull request: needs review

#1192 Removed duplicate methods
  appinventor/buildserver/src/com/google/appinventor/buildserver/Compiler.java
Labels: affects: master, enhancement, pull request: in review

#1189 Cleanup assorted Issues
  appinventor/appengine/src/com/google/appinventor/client/GalleryGuiFactory.java
  appinventor/appengine/src/com/google/appinventor/client/explorer/youngandroid/GalleryList.java
  appinventor/appengine/src/com/google/appinventor/client/explorer/youngandroid/ProfilePage.java
  appinventor/appengine/src/com/google/appinventor/server/storage/ObjectifyStorageIo.java
Labels: affects: master, pull request: in review, technical debt
