Repository mit-cml/appinventor-sources, pull requests merged in 2018-09, with the labels that each got.

#1346 Hide custom colour picker on interaction elsewhere
  appinventor/appengine/src/com/google/appinventor/client/widgets/properties/ColorChoicePropertyEditor.java
Labels: affects: master, bug, pull request: in review

#1348 Check for java reserved words in component and project names
  appinventor/appengine/src/com/google/appinventor/client/OdeMessages.java
  appinventor/appengine/src/com/google/appinventor/client/OdeMessages_es_ES.properties
  appinventor/appengine/src/com/google/appinventor/client/OdeMessages_fr_FR.properties
  appinventor/appengine/src/com/google/appinventor/client/OdeMessages_it_IT.properties
  appinventor/appengine/src/com/google/appinventor/client/OdeMessages_ko_KR.properties
  appinventor/appengine/src/com/google/appinventor/client/OdeMessages_nl.properties
  appinventor/appengine/src/com/google/appinventor/client/OdeMessages_pt.properties
  appinventor/appengine/src/com/google/appinventor/client/OdeMessages_pt_BR.properties
  appinventor/appengine/src/com/google/appinventor/client/OdeMessages_ru.properties
  appinventor/appengine/src/com/google/appinventor/client/OdeMessages_sv.properties
  appinventor/appengine/src/com/google/appinventor/client/OdeMessages_zh_CN.properties
  appinventor/appengine/src/com/google/appinventor/client/OdeMessages_zh_TW.properties
  appinventor/appengine/src/com/google/appinventor/client/editor/simple/components/MockComponent.java
  appinventor/appengine/src/com/google/appinventor/client/explorer/commands/AddFormCommand.java
  appinventor/appengine/src/com/google/appinventor/client/youngandroid/TextValidators.java
  appinventor/appengine/tests/com/google/appinventor/client/youngandroid/TextValidatorsTest.java
Labels: affects: master, bug, pull request: needs review

#1353 Added context menu items to enable and disable all blocks
  appinventor/blocklyeditor/src/msg/en/_messages.js
  appinventor/blocklyeditor/src/workspace_svg.js
Labels: affects: master, feature request, pull request: in review

#1372 Increase the default URLFetch timeout
  appinventor/appengine/war/WEB-INF/appengine-web.xml
Labels: affects: master, pull request: needs review

#1369 Fix HELPURL for Control Do-Return block
  appinventor/blocklyeditor/src/blocks/control.js
Labels: affects: master, documentation, pull request: needs review

#1367 Fix set HELPURLs correctly
  appinventor/blocklyeditor/src/blocks/logic.js
  appinventor/blocklyeditor/src/blocks/math.js
  appinventor/blocklyeditor/src/msg/en/_messages.js
Labels: affects: master, bug, pull request: needs review
