Repository mit-cml/appinventor-sources, pull requests merged in 2019-03, with the labels that each got.

#1564 Fixed getVersionName translations
  appinventor/appengine/src/com/google/appinventor/client/OdeMessages.java
  appinventor/appengine/src/com/google/appinventor/client/OdeMessages_es_ES.properties
  appinventor/appengine/src/com/google/appinventor/client/OdeMessages_fr_FR.properties
  appinventor/appengine/src/com/google/appinventor/client/OdeMessages_it_IT.properties
  appinventor/appengine/src/com/google/appinventor/client/OdeMessages_ko_KR.properties
  appinventor/appengine/src/com/google/appinventor/client/OdeMessages_nl.properties
  appinventor/appengine/src/com/google/appinventor/client/OdeMessages_pt.properties
  appinventor/appengine/src/com/google/appinventor/client/OdeMessages_pt_BR.properties
  appinventor/appengine/src/com/google/appinventor/client/OdeMessages_ru.properties
  appinventor/appengine/src/com/google/appinventor/client/OdeMessages_sv.properties
  appinventor/appengine/src/com/google/appinventor/client/OdeMessages_zh_CN.properties
  appinventor/appengine/src/com/google/appinventor/client/OdeMessages_zh_TW.properties
Labels: affects: master, pull request: needs review, regression

#1579 Fix buggy ask for write permissions when not in REPL
  appinventor/components/src/com/google/appinventor/components/runtime/Form.java
Labels: affects: ucr, bug, pull request: needs review

#1582 Use per-app User-Agent for OpenStreetMap
  appinventor/components/src/com/google/appinventor/components/runtime/util/NativeOpenStreetMapController.java
Labels: affects: ucr, bug, pull request: needs review

#1555 Add Clock MakeDate, MakeTime, MakeInstantFromParts methods
  appinventor/appengine/src/com/google/appinventor/client/OdeMessages.java
  appinventor/appengine/src/com/google/appinventor/client/youngandroid/YoungAndroidFormUpgrader.java
  appinventor/blocklyeditor/src/versioning.js
  appinventor/components/src/com/google/appinventor/components/common/YaVersion.java
  appinventor/components/src/com/google/appinventor/components/runtime/Clock.java
  appinventor/docs/reference/components/sensors.html
Labels: affects: ucr, feature request, pull request: needs reply to review

#1572 Implement list reverse block
  appinventor/blocklyeditor/src/blocks/lists.js
  appinventor/blocklyeditor/src/generators/yail/lists.js
  appinventor/blocklyeditor/src/msg/en/_messages.js
  appinventor/blocklyeditor/src/versioning.js
  appinventor/buildserver/src/com/google/appinventor/buildserver/resources/runtime.scm
  appinventor/components/src/com/google/appinventor/components/common/YaVersion.java
  appinventor/docs/reference/blocks/images/lists/reverse.png
  appinventor/docs/reference/blocks/lists.html
Labels: affects: ucr, feature request, pull request: in review

#1569 Store shared constants between Compiler.java and ComponentListGenerator.java into ComponentDescriptorConstans.java
  appinventor/buildserver/build.xml
  appinventor/buildserver/src/com/google/appinventor/buildserver/Compiler.java
  appinventor/components/src/com/google/appinventor/components/common/ComponentDescriptorConstants.java
  appinventor/components/src/com/google/appinventor/components/scripts/ComponentListGenerator.java
Labels: affects: master, pull request: in review, technical debt

#1589 Copypaste order
  appinventor/blocklyeditor/src/workspace_svg.js
Labels: affects: master, enhancement, pull request: in review

#1587 Add Stop method to VideoPlayer
  appinventor/appengine/src/com/google/appinventor/client/youngandroid/YoungAndroidFormUpgrader.java
  appinventor/blocklyeditor/src/versioning.js
  appinventor/components/src/com/google/appinventor/components/common/YaVersion.java
  appinventor/components/src/com/google/appinventor/components/runtime/VideoPlayer.java
  appinventor/components/src/com/google/appinventor/components/runtime/util/FullScreenVideoUtil.java
Labels: affects: ucr, feature request, pull request: needs reply to review

#1590 join-with-separator Block Implementation
  appinventor/blocklyeditor/src/blocks/lists.js
  appinventor/blocklyeditor/src/drawer.js
  appinventor/blocklyeditor/src/generators/yail/lists.js
  appinventor/blocklyeditor/src/msg/en/_messages.js
  appinventor/blocklyeditor/src/versioning.js
  appinventor/blocklyeditor/tests/com/google/appinventor/blocklyeditor/BlocklyCodeGeneratorTest.java
  appinventor/blocklyeditor/tests/com/google/appinventor/generators_unit/listsJoinWithSeparatorTest.js
  appinventor/buildserver/src/com/google/appinventor/buildserver/resources/runtime.scm
  appinventor/components/src/com/google/appinventor/components/common/YaVersion.java
  appinventor/docs/reference/blocks/images/lists/joinwithseparator.PNG
  appinventor/docs/reference/blocks/lists.html
Labels: affects: ucr, feature request, pull request: needs reply to review

#1482 LocationSensor documentation updates
  appinventor/docs/reference/components/sensors.html
Labels: affects: master, documentation, pull request: needs reply to review

#1605 Fix build system dependency relationships
  appinventor/build.xml
  appinventor/buildserver/build.xml
  appinventor/components/build.xml
Labels: AI Extensions, affects: master, pull request: needs review, regression

#1598 Fix ill-encoding of UriBuilder class
  appinventor/appengine/src/com/google/appinventor/server/util/UriBuilder.java
Labels: affects: master, bug, pull request: needs review

#1595 WidthPercent, HeightPercent, Width & Height Tooltips, Documentation
  appinventor/components/src/com/google/appinventor/components/runtime/AndroidViewComponent.java
  appinventor/docs/reference/components/layout.html
Labels: affects: ucr, documentation, pull request: needs review

#1608 Use built-in (rejection algorithm) random sampling
  appinventor/components/src/com/google/appinventor/components/runtime/util/WebRTCNativeMgr.java
Labels: affects: ucr, bug, pull request: needs review

#1614 De-Bounce the “Connect To” Button in the Companion
  appinventor/components/src/com/google/appinventor/components/runtime/Notifier.java
  appinventor/components/src/com/google/appinventor/components/runtime/PhoneStatus.java
Labels: affects: ucr, pull request: in review

#1176 Added DrawShape & DrawArc into Canvas component
  appinventor/appengine/src/com/google/appinventor/client/OdeMessages.java
  appinventor/appengine/src/com/google/appinventor/client/youngandroid/YoungAndroidFormUpgrader.java
  appinventor/blocklyeditor/src/drawer.js
  appinventor/blocklyeditor/src/versioning.js
  appinventor/components/src/com/google/appinventor/components/common/YaVersion.java
  appinventor/components/src/com/google/appinventor/components/runtime/Canvas.java
  appinventor/components/src/com/google/appinventor/components/runtime/util/ErrorMessages.java
  appinventor/docs/reference/components/animation.html
Labels: affects: ucr, enhancement, pull request: needs reply to review

#1432 Toggle switch control (ucr)
  appinventor/appengine/src/com/google/appinventor/client/Images.java
  appinventor/appengine/src/com/google/appinventor/client/editor/simple/components/MockCheckBox.java
  appinventor/appengine/src/com/google/appinventor/client/editor/simple/components/MockSwitch.java
  appinventor/appengine/src/com/google/appinventor/client/editor/simple/components/MockToggleBase.java
  appinventor/appengine/src/com/google/appinventor/client/editor/simple/components/MockVisibleComponent.java
  appinventor/appengine/src/com/google/appinventor/client/editor/simple/palette/SimpleComponentDescriptor.java
  appinventor/appengine/src/com/google/appinventor/images/switch.png
  appinventor/blocklyeditor/src/blocks/components.js
  appinventor/blocklyeditor/src/msg/en/_messages.js
  appinventor/components/src/com/google/appinventor/components/common/YaVersion.java
  appinventor/components/src/com/google/appinventor/components/runtime/CheckBox.java
  appinventor/components/src/com/google/appinventor/components/runtime/Switch.java
  appinventor/components/src/com/google/appinventor/components/runtime/ToggleBase.java
  appinventor/components/tests/com/google/appinventor/components/runtime/CheckboxTest.java
  appinventor/components/tests/com/google/appinventor/components/runtime/SwitchTest.java
  appinventor/components/tests/com/google/appinventor/components/runtime/ToggleTestBase.java
  appinventor/docs/reference/components/userinterface.html
Labels: affects: ucr, feature request, pull request: needs reply to review

#1615 Simplify the WebRTC Poller
  appinventor/components/src/com/google/appinventor/components/runtime/util/WebRTCNativeMgr.java
Labels: affects: ucr, pull request: needs review

#1621 Rename image joinwithseparator.png
  appinventor/docs/reference/blocks/images/lists/joinwithseparator.png
Labels: affects: ucr

#1607 Created a variable to determine range of Permission request code (#1520)
  appinventor/components/src/com/google/appinventor/components/runtime/Form.java
Labels: affects: ucr, enhancement, pull request: needs review

#1609 Fix handling of percent lengths when changing width/height in blocks
  appinventor/components/src/com/google/appinventor/components/runtime/AndroidViewComponent.java
  appinventor/components/src/com/google/appinventor/components/runtime/Form.java
Labels: affects: ucr, bug, pull request: needs reply to review

#1610 Palette not shows up on deleting screen in Blocks
  appinventor/appengine/src/com/google/appinventor/client/editor/ProjectEditor.java
Labels: affects: master, bug, pull request: ready to push to Gerrit

#1600 Hide workspace
  appinventor/blocklyeditor/src/msg/en/_messages.js
  appinventor/blocklyeditor/src/workspace_svg.js
Labels: affects: master, enhancement, pull request: needs reply to review

#1622 App Inventor Hungarian translation
  appinventor/appengine/src/com/google/appinventor/YaClient.gwt.xml
  appinventor/appengine/src/com/google/appinventor/client/OdeMessages_hu.properties
  appinventor/appengine/src/com/google/appinventor/client/languages.json
  appinventor/blocklyeditor/ploverConfig.js
  appinventor/blocklyeditor/src/language_switch.js
  appinventor/blocklyeditor/src/msg/hu/_messages.js
Labels: Internationalization, affects: master

#1624 Remove bad image file from webassets
  appinventor/appengine/war/websiteassets/img/vjs.eot?
Labels: affects: master, pull request: needs review, regression

#1618 Fix logic bug when property value is the empty string
  appinventor/blocklyeditor/src/component_database.js
  appinventor/blocklyeditor/src/generators/yail.js
Labels: affects: master, bug, pull request: needs review

#1617 Simplify AndroidRuntime classpath further
  appinventor/components/build.xml
Labels: affects: master, pull request: needs review, technical debt

#1556 Make FormPropertiesAnalyzer handle Windows line endings
  appinventor/appengine/src/com/google/appinventor/shared/youngandroid/YoungAndroidSourceAnalyzer.java
  appinventor/buildserver/src/com/google/appinventor/buildserver/FormPropertiesAnalyzer.java
  appinventor/buildserver/tests/com/google/appinventor/buildserver/FormPropertiesAnalyzerTest.java
Labels: affects: master, pull request: needs review, regression

#1628 Have Companion Create a unique ID
  appinventor/aiplayapp/src/edu/mit/appinventor/aicompanion3/Screen1.bky
  appinventor/aiplayapp/src/edu/mit/appinventor/aicompanion3/Screen1.scm
  appinventor/aiplayapp/src/edu/mit/appinventor/aicompanion3/Screen1.yail
  appinventor/components/src/com/google/appinventor/components/runtime/PhoneStatus.java
Labels: affects: ucr, pull request: needs review

#1631 Fix MockSwitch sizing and positioning interactions with FontSize
  appinventor/appengine/src/com/google/appinventor/client/editor/simple/components/MockSwitch.java
Labels: affects: ucr, bug, pull request: needs review

#1588 Handle transitive nature of disabled blocks in conditional permissions
  appinventor/buildserver/src/com/google/appinventor/buildserver/FormPropertiesAnalyzer.java
Labels: affects: master, bug, pull request: needs reply to review

#1634 Pass query string parameters through the TOS
  appinventor/appengine/src/com/google/appinventor/client/Ode.java
  appinventor/appengine/src/com/google/appinventor/server/TosServlet.java
  appinventor/appengine/war/WEB-INF/appengine-web.xml
  appinventor/appengine/war/Ya_tos_form.html
  appinventor/appengine/war/js/tos.js
Labels: affects: master, bug, pull request: in review

#1633 Fix logic bug in MakePhoneCallDirect
  appinventor/components/src/com/google/appinventor/components/runtime/PhoneCall.java
Labels: affects: ucr, bug, pull request: in review

#1638 Do not show 'no project dialog' in gallery view
  appinventor/appengine/src/com/google/appinventor/client/Ode.java
Labels: affects: master, bug, pull request: needs review

#1632 Fix theme issue due to property/component initialization
  appinventor/buildserver/src/com/google/appinventor/buildserver/resources/runtime.scm
Labels: affects: ucr, bug, pull request: needs review

#1563 Unified file provider source
  appinventor/components/src/com/google/appinventor/components/runtime/ActivityStarter.java
  appinventor/components/src/com/google/appinventor/components/runtime/Camera.java
  appinventor/components/src/com/google/appinventor/components/runtime/Sharing.java
  appinventor/components/src/com/google/appinventor/components/runtime/util/AssetFetcher.java
  appinventor/components/src/com/google/appinventor/components/runtime/util/PackageInstaller.java
Labels: affects: ucr, enhancement, pull request: in review
