Repository mit-cml/appinventor-sources, pull requests merged in 2019-04, with the labels that each got.

#1641 Hide Progress Dialog on Companion Update
  appinventor/appengine/src/com/google/appinventor/client/ConnectProgressBar.java
  appinventor/blocklyeditor/src/replmgr.js
Labels: affects: master, pull request: needs review

#1646 Fix blocks PNG export in Webkit
  appinventor/blocklyeditor/src/exportBlocksImage.js
Labels: affects: master, bug, pull request: needs review

#1654 Fix issues with HolePointsFromString in Polygon
  appinventor/appengine/src/com/google/appinventor/client/editor/simple/components/MockPolygon.java
  appinventor/components/src/com/google/appinventor/components/runtime/Polygon.java
Labels: affects: ucr, bug, pull request: needs review

#1655 Fix failing PolygonTests
  appinventor/components/tests/com/google/appinventor/components/runtime/PolygonTest.java
Labels: affects: ucr, pull request: needs review, regression

#1648 Updated Texting documents for Google Voice no receiving issue #1015
  appinventor/docs/reference/components/social.html
Labels: affects: master, pull request: needs reply to review

#1659 Update macOS binaries to 64-bit for Mojave
  appinventor/lib/android/tools/mac/aapt
  appinventor/lib/android/tools/mac/zipalign
Labels: affects: master, pull request: needs review, technical debt

#1417 Replace JarSigner with ApkSigner
  appinventor/buildserver/src/com/google/appinventor/buildserver/Compiler.java
  appinventor/components/build.xml
  appinventor/lib/android/tools/apksigner.jar
Labels: affects: master, enhancement, pull request: on hold

#1663 Fix performance issue in project list
  appinventor/appengine/src/com/google/appinventor/client/explorer/youngandroid/ProjectList.java
Labels: affects: master, bug, pull request: needs review

#1664 Use DomHelper to show Do It error dialog
  appinventor/blocklyeditor/src/blocklyeditor.js
  appinventor/blocklyeditor/src/msg/en/_messages.js
Labels: affects: master, bug, pull request: needs review
