Repository mit-cml/appinventor-sources, pull requests merged in 2019-08, with the labels that each got.

#1759 Fixed empty dropdown
  appinventor/blocklyeditor/src/field_lexical_variable.js
Labels: affects: master, bug, pull request: needs review

#1755 Fix screen names with underscore
  appinventor/appengine/src/com/google/appinventor/client/editor/youngandroid/BlocklyPanel.java
  appinventor/blocklyeditor/src/drawer.js
Labels: affects: master, bug, pull request: needs review

#1758 Code optimise
  appinventor/appengine/src/com/google/appinventor/client/editor/simple/components/MockForm.java
  appinventor/appengine/src/com/google/appinventor/client/editor/youngandroid/YaBlocksEditor.java
Labels: affects: master, pull request: needs reply to review, technical debt

#1753 Don’t require WiFi for the Emulator
  appinventor/buildserver/src/com/google/appinventor/buildserver/Compiler.java
Labels: pull request: needs review

#1765 Fix blocks missing from editor after Blocks Toolkit enhancement
  appinventor/blocklyeditor/src/drawer.js
Labels: affects: master, bug, pull request: needs review

#1739 Add internationalization to component block tooltips in Blocks Editor
  appinventor/blocklyeditor/src/blocks/components.js
  appinventor/blocklyeditor/src/component_database.js
Labels: affects: master, bug, pull request: needs review

#1768 Move CloudDB from Experimental to Storage Category
  appinventor/blocklyeditor/src/msg/en/_messages.js
  appinventor/blocklyeditor/src/msg/hu/_messages.js
  appinventor/components/src/com/google/appinventor/components/runtime/CloudDB.java
  appinventor/docs/reference/components/experimental.html
  appinventor/docs/reference/components/storage.html
Labels: affects: master, pull request: in review

#1779 Update README
  README.md
Labels: affects: master, documentation, pull request: ready to push to Gerrit

#1769 Remove Obsolete Docs from Service
  appinventor/docs/ReleaseNotes.html
  appinventor/docs/forum/guidelines.html
  appinventor/docs/forum/index.html
  appinventor/docs/knownIssues.html
  appinventor/docs/learn/index.html
Labels: affects: master, pull request: in review

#1780 Make ScaledFrameLayout only save matrix
  appinventor/components/src/com/google/appinventor/components/runtime/ScaledFrameLayout.java
Labels: affects: ucr, bug, pull request: needs review

#1726 Korean translation update
  appinventor/appengine/src/com/google/appinventor/client/OdeMessages_ko_KR.properties
  appinventor/blocklyeditor/src/msg/ko_kr/_messages.js
Labels: affects: master, enhancement, pull request: needs review

#1781 Fix REPL bug when switching to freshly opened projects
  appinventor/appengine/src/com/google/appinventor/client/DesignToolbar.java
  appinventor/appengine/src/com/google/appinventor/client/editor/youngandroid/YaBlocksEditor.java
Labels: affects: master, pull request: needs review, regression

#1720 Make PhoneCall request READ_PHONE_STATE dangerous permission also
  appinventor/components/src/com/google/appinventor/components/runtime/Form.java
  appinventor/components/src/com/google/appinventor/components/runtime/PhoneCall.java
  appinventor/components/src/com/google/appinventor/components/runtime/util/BulkPermissionRequest.java
  appinventor/components/src/com/google/appinventor/components/scripts/ComponentProcessor.java
Labels: affects: ucr, pull request: needs review, regression

#1784 Make template wizard dialog fit smaller screens
  appinventor/appengine/src/com/google/appinventor/client/wizards/TemplateUploadWizard.java
Labels: affects: master, enhancement, pull request: in review

#1787 Remove horizontal scroll from template wizard dialog
  appinventor/appengine/src/com/google/appinventor/client/wizards/TemplateUploadWizard.java
Labels: affects: master, enhancement, pull request: in review

#1785 Add missing android.arch.lifecycle dependency
  appinventor/lib/android/support/jars.txt
  appinventor/lib/android/support/lifecycle-common-1.1.1.jar
Labels: affects: ucr, pull request: needs review, technical debt

#1794 Add missing extension to emulator build to allow package installation
  appinventor/buildserver/build.xml
Labels: affects: master, pull request: needs review, regression
