Repository mit-cml/appinventor-sources, pull requests merged in 2019-02, with the labels that each got.

#1546 Correctly convert bignums to strings in YailList
  appinventor/components/src/com/google/appinventor/components/runtime/util/YailList.java
  appinventor/components/src/com/google/appinventor/components/runtime/util/YailNumberToString.java
  appinventor/components/tests/com/google/appinventor/components/runtime/util/YailListTest.java
Labels: affects: ucr, bug, pull request: needs review

#1549 Limit Certain Permissions
  appinventor/buildserver/src/com/google/appinventor/buildserver/Compiler.java
  appinventor/common/src/com/google/appinventor/common/version/AppInventorFeatures.java
Labels: affects: master, pull request: needs review

#1560 Update WebViewer Documentation
  appinventor/docs/reference/components/userinterface.html
Labels: affects: master, documentation, pull request: needs reply to review

#1557 Add drop down menu and fix formatting issues
  appinventor/appengine/src/com/google/appinventor/client/OdeMessages.java
  appinventor/appengine/src/com/google/appinventor/client/editor/simple/SimpleVisibleComponentsPanel.java
  appinventor/appengine/src/com/google/appinventor/client/editor/simple/components/MockForm.java
Labels: affects: master, feature request, pull request: in review

#1480 Power User identified issues 1
  appinventor/docs/reference/blocks/control.html
  appinventor/docs/reference/blocks/procedures.html
  appinventor/docs/reference/components/maps.html
  appinventor/docs/reference/components/social.html
  appinventor/docs/reference/components/userinterface.html
Labels: affects: master, documentation, pull request: needs reply to review

#1561 Internationalization scripts
  appinventor/appengine/build.xml
  appinventor/appengine/src/com/google/appinventor/client/OdeMessages.java
  appinventor/appengine/src/com/google/appinventor/client/TopPanel.java
  appinventor/appengine/src/com/google/appinventor/client/languages.json
  appinventor/blocklyeditor/src/drawer.js
  appinventor/blocklyeditor/src/msg/en/_messages.js
  appinventor/blocklyeditor/src/msg/es_es/_messages.js
  appinventor/blocklyeditor/src/msg/fr_fr/_messages.js
  appinventor/blocklyeditor/src/msg/ko_kr/_messages.js
  appinventor/blocklyeditor/src/msg/nl/_messages.js
  appinventor/blocklyeditor/src/msg/pt/_messages.js
  appinventor/blocklyeditor/src/msg/pt_br/_messages.js
  appinventor/blocklyeditor/src/msg/ru/_messages.js
  appinventor/blocklyeditor/src/msg/sv/_messages.js
  appinventor/blocklyeditor/src/msg/zh_cn/_messages.js
  appinventor/blocklyeditor/src/msg/zh_tw/_messages.js
  appinventor/blocklyeditor/src/warningHandler.js
  appinventor/components/build.xml
  appinventor/components/src/com/google/appinventor/components/scripts/ComponentTranslationGenerator.java
  appinventor/misc/i18n/README.md
  appinventor/misc/i18n/i18n.py
  appinventor/misc/i18n/js_to_prop.js
  appinventor/misc/i18n/requirements.txt
Labels: affects: master, enhancement, pull request: needs review

#1575 Num1567
  appinventor/blocklyeditor/src/backpack.js
  appinventor/blocklyeditor/src/workspace_svg.js
Labels: affects: master, enhancement, pull request: needs review

#1550 Add password dialog option to Notifier
  appinventor/appengine/src/com/google/appinventor/client/OdeMessages.java
  appinventor/appengine/src/com/google/appinventor/client/youngandroid/YoungAndroidFormUpgrader.java
  appinventor/blocklyeditor/src/versioning.js
  appinventor/components/src/com/google/appinventor/components/common/YaVersion.java
  appinventor/components/src/com/google/appinventor/components/runtime/Notifier.java
  appinventor/docs/reference/components/userinterface.html
Labels: affects: ucr, feature request, pull request: needs reply to review

#1403 1004 cycle through warning error blocks
  appinventor/appengine/src/com/google/appinventor/client/editor/youngandroid/BlocklyPanel.java
  appinventor/blocklyeditor/src/blocklyeditor.js
  appinventor/blocklyeditor/src/blocks/procedures.js
  appinventor/blocklyeditor/src/warningHandler.js
  appinventor/blocklyeditor/src/warningIndicator.js
  appinventor/blocklyeditor/src/workspace_svg.js
Labels: affects: master, enhancement, pull request: needs review, status: needs discussion

#1576 Make preview size listbox invisible when Sizing = Fixed
  appinventor/appengine/src/com/google/appinventor/client/editor/simple/SimpleVisibleComponentsPanel.java
Labels: affects: master, enhancement, pull request: needs reply to review
