Repository mit-cml/appinventor-sources, pull requests merged in 2019-06, with the labels that each got.

#1723 Fix export projects in oneProject mode
  appinventor/appengine/src/com/google/appinventor/client/TopToolbar.java
Labels: affects: master, pull request: ON GERRIT

#1667 Search filter
  appinventor/appengine/src/com/google/appinventor/client/OdeMessages.java
  appinventor/appengine/src/com/google/appinventor/client/editor/youngandroid/palette/YoungAndroidPalettePanel.java
  appinventor/appengine/src/com/google/appinventor/client/utils/Trie.java
Labels: affects: master, enhancement, pull request: in review

#1657 Implement a StopListening method for SpeechRecognizer (#1013)
  appinventor/appengine/src/com/google/appinventor/client/youngandroid/YoungAndroidFormUpgrader.java
  appinventor/blocklyeditor/src/versioning.js
  appinventor/blocklyeditor/tests/com/google/appinventor/blocklyeditor/data/copyCat/copyCatExpected.yail
  appinventor/components/src/com/google/appinventor/components/common/YaVersion.java
  appinventor/components/src/com/google/appinventor/components/runtime/IntentBasedSpeechRecognizer.java
  appinventor/components/src/com/google/appinventor/components/runtime/ServiceBasedSpeechRecognizer.java
  appinventor/components/src/com/google/appinventor/components/runtime/SpeechListener.java
  appinventor/components/src/com/google/appinventor/components/runtime/SpeechRecognizer.java
  appinventor/components/src/com/google/appinventor/components/runtime/SpeechRecognizerController.java
  appinventor/components/src/com/google/appinventor/components/runtime/util/ErrorMessages.java
Labels: affects: ucr, feature request, pull request: needs reply to review

#1684 Added phone skin to designer
  appinventor/appengine/src/com/google/appinventor/client/editor/simple/SimpleVisibleComponentsPanel.java
  appinventor/appengine/src/com/google/appinventor/client/editor/simple/components/MockForm.java
  appinventor/appengine/war/Ya.css
  appinventor/appengine/war/images/phoneLandscape.png
  appinventor/appengine/war/images/phoneLandscapeMonitor.png
  appinventor/appengine/war/images/phoneLandscapeTablet.png
  appinventor/appengine/war/images/phonePortrait.png
  appinventor/appengine/war/images/phonePortraitMonitor.png
  appinventor/appengine/war/images/phonePortraitTablet.png
Labels: affects: master, feature request, pull request: in review

#1725 Fix exception when deleting extension with hidden components
  appinventor/appengine/src/com/google/appinventor/client/editor/youngandroid/palette/YoungAndroidPalettePanel.java
Labels: affects: master, bug, pull request: needs review
