Repository mit-cml/appinventor-sources, pull requests merged in 2019-10, with the labels that each got.

#1868 Associate marker asset with Map for runtime markers
  appinventor/components/src/com/google/appinventor/components/runtime/Map.java
  appinventor/components/src/com/google/appinventor/components/runtime/Marker.java
Labels: affects: master, bug, pull request: needs review

#1867 Make AWT run in headless mode in buildserver
  appinventor/buildserver/build.xml
Labels: affects: master, pull request: needs review, technical debt

#1872 Added Sponsor Button
  .github/FUNDING.yml
Labels: affects: master, pull request: needs review

#1864 Reenable convert number block translations in zh_tw, zh_cn
  appinventor/blocklyeditor/src/msg/zh_cn/_messages.js
  appinventor/blocklyeditor/src/msg/zh_tw/_messages.js
Labels: Internationalization, affects: master, pull request: needs reply to review

#1876 Reuse flydown SVG rather than making orphans
  appinventor/blocklyeditor/src/field_flydown.js
Labels: affects: master, bug, pull request: needs review

#1846 Raise error when using boxed primitive types in component APIs
  appinventor/components/src/com/google/appinventor/components/scripts/ComponentProcessor.java
Labels: affects: master, enhancement, pull request: needs review

#1871 Added TurnOn Function to BuildServer
  appinventor/buildserver/src/com/google/appinventor/buildserver/BuildServer.java
Labels: affects: ucr, enhancement, pull request: needs reply to review

#1863 Update Dutch translations
  appinventor/appengine/src/com/google/appinventor/client/OdeMessages_nl.properties
Labels: Internationalization, affects: master, pull request: needs review

#1886 Add ReadOnly property to TextBox component
  appinventor/appengine/src/com/google/appinventor/client/youngandroid/YoungAndroidFormUpgrader.java
  appinventor/blocklyeditor/src/versioning.js
  appinventor/components/src/com/google/appinventor/components/common/YaVersion.java
  appinventor/components/src/com/google/appinventor/components/runtime/TextBox.java
Labels: affects: ucr, enhancement, pull request: needs reply to review
