Repository mit-cml/appinventor-sources, pull requests merged in 2019-05, with the labels that each got.

#1666 Add support for a “secondary” Rendezvous Server
  appinventor/aiplayapp/src/edu/mit/appinventor/aicompanion3/Screen1.bky
  appinventor/aiplayapp/src/edu/mit/appinventor/aicompanion3/Screen1.scm
  appinventor/aiplayapp/src/edu/mit/appinventor/aicompanion3/Screen1.yail
  appinventor/appengine/src/com/google/appinventor/client/Ode.java
  appinventor/blocklyeditor/src/replmgr.js
  appinventor/components/src/com/google/appinventor/components/runtime/PhoneStatus.java
  appinventor/components/src/com/google/appinventor/components/runtime/util/WebRTCNativeMgr.java
Labels: affects: ucr, pull request: needs reply to review

#1642 Remove References to the Package Installer
  appinventor/components/src/com/google/appinventor/components/runtime/PhoneStatus.java
  appinventor/components/src/com/google/appinventor/components/runtime/util/AppInvHTTPD.java
  appinventor/components/src/com/google/appinventor/components/runtime/util/AssetFetcher.java
  appinventor/components/src/com/google/appinventor/components/runtime/util/PackageInstaller.java
Labels: affects: ucr, pull request: on hold

#1661 Add extra companions
  appinventor/aiplayapp/assets/external_comps/edu.mit.appinventor.companionextras/classes.jar
  appinventor/aiplayapp/assets/external_comps/edu.mit.appinventor.companionextras/component.json
  appinventor/aiplayapp/assets/external_comps/edu.mit.appinventor.companionextras/components.json
  appinventor/aiplayapp/assets/external_comps/edu.mit.appinventor.companionextras/extension.properties
  appinventor/aiplayapp/assets/external_comps/edu.mit.appinventor.companionextras/files/AndroidRuntime.jar
  appinventor/aiplayapp/assets/external_comps/edu.mit.appinventor.companionextras/files/component_build_info.json
  appinventor/aiplayapp/assets/external_comps/edu.mit.appinventor.companionextras/files/component_build_infos.json
  appinventor/build.xml
  appinventor/buildserver/build.xml
  appinventor/buildserver/src/com/google/appinventor/buildserver/BuildServer.java
  appinventor/buildserver/src/com/google/appinventor/buildserver/Compiler.java
  appinventor/buildserver/src/com/google/appinventor/buildserver/Main.java
  appinventor/buildserver/src/com/google/appinventor/buildserver/ProjectBuilder.java
  appinventor/buildserver/tests/com/google/appinventor/buildserver/CompilerTest.java
  appinventor/common/src/com/google/appinventor/common/version/AppInventorFeatures.java
  appinventor/components/src/com/google/appinventor/components/runtime/PhoneStatus.java
  appinventor/misc/companionextras-extension/edu/mit/appinventor/companionextras/CompanionExtras.java
Labels: affects: ucr, pull request: needs review, technical debt

#1677 Another minor fix to the German translation
  appinventor/blocklyeditor/src/msg/de/_messages.js
Labels: affects: master, pull request: needs review

#1681 Make Image.Picture ask for read permissions if needed
  appinventor/components/src/com/google/appinventor/components/runtime/Image.java
Labels: affects: master, bug, pull request: needs review

#1688 Make English the blocks editor base language
  appinventor/blocklyeditor/ploverConfig.js
Labels: affects: master, bug, pull request: needs review

#1703 Fix NPE when only using Google login
  appinventor/appengine/src/com/google/appinventor/server/LoginServlet.java
Labels: affects: master, bug, pull request: needs review

#1699 Refactor GeoJSON processing in mock map features
  appinventor/appengine/src/com/google/appinventor/client/editor/simple/components/MockLineString.java
  appinventor/appengine/src/com/google/appinventor/client/editor/simple/components/MockMapFeatureBase.java
  appinventor/appengine/src/com/google/appinventor/client/editor/simple/components/MockMapFeatureBaseWithFill.java
  appinventor/appengine/src/com/google/appinventor/client/editor/simple/components/MockMarker.java
  appinventor/appengine/src/com/google/appinventor/client/editor/simple/components/MockPolygon.java
Labels: affects: master, bug, pull request: needs review

#1702 Fallback to application/octet-stream for unknown file types
  appinventor/components/src/com/google/appinventor/components/runtime/Sharing.java
Labels: affects: ucr, bug, pull request: needs review

#1697 Apply AnchorHorizontal and AnchorVertical values to Marker
  appinventor/components/src/com/google/appinventor/components/runtime/util/NativeOpenStreetMapController.java
Labels: affects: ucr, bug, pull request: needs review

#1700 Initialize polygons loaded at runtime
  appinventor/components/build.xml
  appinventor/components/src/com/google/appinventor/components/runtime/Polygon.java
  appinventor/components/src/com/google/appinventor/components/runtime/util/GeoJSONUtil.java
  appinventor/components/tests/assets/com.google.appinventor.components.runtime.test/usa-new-england.geojson
  appinventor/components/tests/com/google/appinventor/components/runtime/MapTest.java
  appinventor/components/tests/com/google/appinventor/components/runtime/shadows/ShadowEventDispatcher.java
Labels: affects: ucr, pull request: needs review, regression

#1693 Update README
  README.md
Labels: affects: master, documentation, pull request: ready to push to Gerrit

#1689 Fix warning counter going to -1
  appinventor/blocklyeditor/src/warningHandler.js
  appinventor/blocklyeditor/src/warningIndicator.js
Labels: affects: master, bug, pull request: needs review

#1709 Add Build Fingerprint
  appinventor/appengine/src/com/google/appinventor/server/CrashReport.java
Labels: affects: master, pull request: needs review

#1712 Remove vestigial XML blocks generator
  appinventor/build-common.xml
  appinventor/components/build.xml
  appinventor/components/src/com/google/appinventor/components/annotations/DesignerComponent.java
  appinventor/components/src/com/google/appinventor/components/runtime/Form.java
  appinventor/components/src/com/google/appinventor/components/scripts/LangDefXmlGenerator.java
Labels: affects: master, pull request: needs review, technical debt

#1715 Add missing entry for German in languages.json
  appinventor/appengine/src/com/google/appinventor/client/languages.json
Labels: affects: master, technical debt

#1706 Enable import/export block code as PNGs
  appinventor/blocklyeditor/src/blocklyeditor.js
  appinventor/blocklyeditor/src/blocks/components.js
  appinventor/blocklyeditor/src/blocks/procedures.js
  appinventor/blocklyeditor/src/exportBlocksImage.js
  appinventor/blocklyeditor/src/msg/en/_messages.js
  appinventor/blocklyeditor/src/workspace_svg.js
Labels: affects: master, enhancement, pull request: needs review

#1714 More WebRTC fixes
  appinventor/blocklyeditor/src/replmgr.js
  appinventor/components/src/com/google/appinventor/components/runtime/util/WebRTCNativeMgr.java
Labels: affects: master, affects: ucr, pull request: needs review

#1708 Re-Enable the “Update Companion” Menu Item
  appinventor/appengine/src/com/google/appinventor/client/TopToolbar.java
  appinventor/blocklyeditor/src/msg/en/_messages.js
  appinventor/blocklyeditor/src/replmgr.js
Labels: affects: master, pull request: needs reply to review

#1704 Add Switch style for Classic theme
  appinventor/buildserver/src/com/google/appinventor/buildserver/Compiler.java
Labels: affects: master, bug, pull request: needs review

#1670 Fix backpack remove (#1467)
  appinventor/blocklyeditor/src/backpack.js
Labels: affects: master, bug, pull request: ready to push to Gerrit

#1660 Handle unbound variables and prompt user for input
  appinventor/blocklyeditor/src/blocklyeditor.js
  appinventor/blocklyeditor/src/msg/en/_messages.js
Labels: affects: master, feature request, pull request: ready to push to Gerrit
