Repository mit-cml/appinventor-sources, pull requests merged in 2019-11, with the labels that each got.

#1890 Remove unused context constructor param
  appinventor/components/src/com/google/appinventor/components/runtime/WebViewer.java
Labels: affects: ucr, pull request: needs review, technical debt

#1859 Support fill-opacity/stroke-opacity for map features
  appinventor/appengine/src/com/google/appinventor/client/youngandroid/YoungAndroidFormUpgrader.java
  appinventor/blocklyeditor/src/versioning.js
  appinventor/components/src/com/google/appinventor/components/common/YaVersion.java
  appinventor/components/src/com/google/appinventor/components/runtime/MapFeatureBase.java
  appinventor/components/src/com/google/appinventor/components/runtime/MapFeatureBaseWithFill.java
  appinventor/components/src/com/google/appinventor/components/runtime/MapFeatureContainerBase.java
  appinventor/components/src/com/google/appinventor/components/runtime/util/GeoJSONUtil.java
  appinventor/components/src/com/google/appinventor/components/runtime/util/MapFactory.java
  appinventor/components/src/com/google/appinventor/components/runtime/util/NativeOpenStreetMapController.java
  appinventor/components/tests/com/google/appinventor/components/runtime/util/GeoJSONUtilTest.java
  appinventor/docs/reference/components/maps.html
Labels: affects: ucr, feature request, pull request: needs reply to review

#1898 Fix empty points, holepoints after polygon drag
  appinventor/components/src/com/google/appinventor/components/runtime/util/NativeOpenStreetMapController.java
Labels: affects: ucr, bug, pull request: needs review

#1900 Bump YOUNG_ANDROID_VERSION due to recent changes
  appinventor/components/src/com/google/appinventor/components/common/YaVersion.java
Labels: affects: ucr, pull request: needs review, technical debt

#1896 Implement option to disable project auto load
  appinventor/appengine/src/com/google/appinventor/client/Ode.java
  appinventor/appengine/src/com/google/appinventor/client/OdeMessages.java
  appinventor/appengine/src/com/google/appinventor/client/TopToolbar.java
  appinventor/appengine/src/com/google/appinventor/client/explorer/youngandroid/ProjectToolbar.java
  appinventor/appengine/src/com/google/appinventor/client/settings/user/GeneralSettings.java
  appinventor/appengine/src/com/google/appinventor/client/widgets/DropDownButton.java
  appinventor/appengine/src/com/google/appinventor/shared/settings/SettingsConstants.java
Labels: affects: master, feature request, pull request: needs review

#1902 Fix global keyword internationalization
  appinventor/blocklyeditor/src/field_lexical_variable.js
Labels: affects: master, bug, pull request: needs review

#1891 Enable multiple component selection using shift key presses
  appinventor/appengine/src/com/google/appinventor/client/editor/simple/components/MockForm.java
  appinventor/appengine/src/com/google/appinventor/client/editor/simple/palette/AbstractPaletteItemWidget.java
  appinventor/appengine/src/com/google/appinventor/client/editor/youngandroid/YaFormEditor.java
  appinventor/appengine/src/com/google/appinventor/client/widgets/properties/EditableProperty.java
Labels: affects: master, feature request, pull request: needs review

#1904 Fix tutorial panel sizing
  appinventor/appengine/src/com/google/appinventor/client/Ode.java
Labels: affects: master, bug, pull request: needs review

#1906 Make Camera ask permission to write to external storage
  appinventor/components/src/com/google/appinventor/components/runtime/Camera.java
Labels: affects: ucr, bug, pull request: needs review

#1908 Only show preview context menu on supported file type.
  appinventor/appengine/src/com/google/appinventor/client/explorer/commands/ChainableCommand.java
  appinventor/appengine/src/com/google/appinventor/client/explorer/commands/PreviewFileCommand.java
  appinventor/appengine/src/com/google/appinventor/client/explorer/commands/ProjectNodeCommand.java
  appinventor/appengine/src/com/google/appinventor/client/explorer/project/ProjectNodeContextMenu.java
  appinventor/appengine/src/com/google/appinventor/shared/storage/StorageUtil.java
Labels: affects: master, enhancement, pull request: needs review

#1888 Add adaptive icons
  appinventor/buildserver/src/com/google/appinventor/buildserver/Compiler.java
  appinventor/buildserver/src/com/google/appinventor/buildserver/resources/ya.png
Labels: affects: master, pull request: needs review, technical debt

#1910 Fix environmental sensor documentation
  appinventor/blocklyeditor/src/blocks/components.js
  appinventor/blocklyeditor/src/msg/en/_messages.js
  appinventor/components/src/com/google/appinventor/components/runtime/SingleValueSensor.java
  appinventor/docs/reference/components/sensors.html
Labels: affects: ucr, documentation, pull request: needs review

#1915 Make PNG exports have transparent background
  appinventor/blocklyeditor/src/exportBlocksImage.js
Labels: affects: master

#1912 Use Ctrl (Windows/Linux) or Cmd (Mac) for multiselect
  appinventor/appengine/src/com/google/appinventor/client/editor/youngandroid/YaFormEditor.java
Labels: affects: master, enhancement, pull request: needs review

#1916 Remove the FusionTablesControl from visibility
  appinventor/components/src/com/google/appinventor/components/runtime/FusiontablesControl.java
  appinventor/docs/reference/components/storage.html
Labels: affects: master, pull request: needs review

#1919 Emit disable event code only if no active handler exists
  appinventor/blocklyeditor/src/replmgr.js
Labels: affects: master, pull request: needs review, regression

#1917 Update Android build tools to 29.0.2
  appinventor/buildserver/build.xml
  appinventor/buildserver/src/com/google/appinventor/buildserver/Compiler.java
  appinventor/lib/android/tools/linux/aapt
  appinventor/lib/android/tools/linux/zipalign
  appinventor/lib/android/tools/mac/aapt
  appinventor/lib/android/tools/mac/zipalign
  appinventor/lib/android/tools/windows/aapt
  appinventor/lib/android/tools/windows/libwinpthread-1.dll
  appinventor/lib/android/tools/windows/zipalign
Labels: affects: master, pull request: needs review, regression

#1923 Hide deprecated blocks
  appinventor/blocklyeditor/src/drawer.js
Labels: affects: master, pull request: needs review, regression

#1907 Remove Pedometer Resume and Pause methods
  appinventor/appengine/src/com/google/appinventor/client/youngandroid/YoungAndroidFormUpgrader.java
  appinventor/blocklyeditor/src/versioning.js
  appinventor/components/src/com/google/appinventor/components/common/YaVersion.java
  appinventor/components/src/com/google/appinventor/components/runtime/Pedometer.java
  appinventor/docs/reference/components/sensors.html
Labels: affects: ucr, pull request: needs review, technical debt
