Repository mit-cml/appinventor-sources, pull requests merged in 2020-07, with the labels that each got.

#2222 Update Chromebook Support
  appinventor/components/src/com/google/appinventor/components/runtime/ReplForm.java
Labels: affects: master, bug, pull request: needs review

#2207 Make sure autoload property propagates
  appinventor/appengine/src/com/google/appinventor/client/Ode.java
  appinventor/appengine/src/com/google/appinventor/server/LoginServlet.java
  appinventor/appengine/war/login.jsp
Labels: affects: master, pull request: needs review

#2226 Sort component names with numeric suffixes in a saner way
  appinventor/blocklyeditor/src/component_database.js
Labels: affects: master, feature request, pull request: needs review

#2234 Implement preventScroll for focusable elements
  appinventor/appengine/src/com/google/appinventor/YaClient.gwt.xml
  appinventor/appengine/src/com/google/appinventor/client/utils/FocusImplSafari.java
  appinventor/appengine/src/com/google/appinventor/client/utils/FocusImplStandard.java
Labels: affects: master, bug, pull request: in review

#2235 Escape Strings on the Login Page
  appinventor/appengine/build.xml
  appinventor/appengine/war/login.jsp
  appinventor/lib/commons-lang3/LICENSE.txt
  appinventor/lib/commons-lang3/NOTICE.txt
  appinventor/lib/commons-lang3/RELEASE-NOTES.txt
  appinventor/lib/commons-lang3/commons-lang3-3.10.jar
Labels: affects: master, pull request: needs reply to review, technical debt

#2220 Allow and/or blocks to have 0 or 1 inputs
  appinventor/blocklyeditor/src/blocks/logic.js
  appinventor/blocklyeditor/src/blocks/math.js
  appinventor/blocklyeditor/src/generators/yail/logic.js
  appinventor/blocklyeditor/src/generators/yail/math.js
  appinventor/components/src/com/google/appinventor/components/runtime/util/YailNumberToString.java
Labels: affects: master, feature request, pull request: needs review

#2243 Typo in the Picture-In-Picture element.
  appinventor/components/src/com/google/appinventor/components/annotations/androidmanifest/ActivityElement.java
Labels: affects: master, bug, pull request: needs review

#2124 Implement OnOrientationChange interface
  appinventor/components/src/com/google/appinventor/components/runtime/Form.java
  appinventor/components/src/com/google/appinventor/components/runtime/OnOrientationChangeListener.java
Labels: affects: ucr, feature request, pull request: needs review

#2255 Add osmdroid.jar as dependency of Navigation component
  appinventor/components/src/com/google/appinventor/components/runtime/Navigation.java
Labels: affects: master, bug, pull request: needs review

#2260 Update documentation for uselegacy in SpeechRecognizer
  appinventor/components/src/com/google/appinventor/components/runtime/SpeechRecognizer.java
  appinventor/docs/html/reference/components/media.html
  appinventor/docs/markdown/reference/components/media.md
Labels: affects: master, pull request: needs reply to review
