Repository mit-cml/appinventor-sources, pull requests merged in 2020-04, with the labels that each got.

#2125 Fix BackPress
  appinventor/components/src/com/google/appinventor/components/runtime/Form.java
Labels: affects: ucr, pull request: needs review, regression

#2142 Make property editors aware of conflicting multiple values
  appinventor/appengine/src/com/google/appinventor/client/OdeMessages.java
  appinventor/appengine/src/com/google/appinventor/client/editor/youngandroid/YaFormEditor.java
  appinventor/appengine/src/com/google/appinventor/client/editor/youngandroid/properties/YoungAndroidAssetSelectorPropertyEditor.java
  appinventor/appengine/src/com/google/appinventor/client/editor/youngandroid/properties/YoungAndroidComponentSelectorPropertyEditor.java
  appinventor/appengine/src/com/google/appinventor/client/editor/youngandroid/properties/YoungAndroidGeoJSONPropertyEditor.java
  appinventor/appengine/src/com/google/appinventor/client/editor/youngandroid/properties/YoungAndroidLengthPropertyEditor.java
  appinventor/appengine/src/com/google/appinventor/client/widgets/properties/AdditionalChoicePropertyEditor.java
  appinventor/appengine/src/com/google/appinventor/client/widgets/properties/BooleanPropertyEditor.java
  appinventor/appengine/src/com/google/appinventor/client/widgets/properties/ChoicePropertyEditor.java
  appinventor/appengine/src/com/google/appinventor/client/widgets/properties/ColorChoicePropertyEditor.java
  appinventor/appengine/src/com/google/appinventor/client/widgets/properties/EditableProperty.java
  appinventor/appengine/src/com/google/appinventor/client/widgets/properties/PropertyEditor.java
Labels: affects: master, bug, pull request: needs review

#2146 Fix collapse event not being fired
  appinventor/blocklyeditor/src/block_svg.js
Labels: affects: master, pull request: needs review, regression

#2144 Init polygon title/Description to that in Designer
  appinventor/components/src/com/google/appinventor/components/runtime/Polygon.java
Labels: affects: ucr, bug, pull request: needs review

#2154 Fix new blocks getting added to backpack on click
  appinventor/blocklyeditor/src/block_svg.js
Labels: affects: master, pull request: needs review, regression

#2155 Add support for user supplied Yandex API keys
  appinventor/appengine/src/com/google/appinventor/client/youngandroid/YoungAndroidFormUpgrader.java
  appinventor/blocklyeditor/src/versioning.js
  appinventor/components/src/com/google/appinventor/components/common/YaVersion.java
  appinventor/components/src/com/google/appinventor/components/runtime/YandexTranslate.java
  appinventor/docs/html/reference/components/media.html
  appinventor/docs/markdown/reference/components/media.md
Labels: affects: ucr, feature request, pull request: needs review

#2158 Make WebRTC Connections more robust
  appinventor/blocklyeditor/src/replmgr.js
Labels: affects: master, bug, pull request: needs review

#2159 Another fix for WebRTC
  appinventor/blocklyeditor/src/msg/en/_messages.js
  appinventor/blocklyeditor/src/replmgr.js
Labels: affects: master, pull request: needs review

#2161 Fix delete assets not working in nb183a
  appinventor/appengine/src/com/google/appinventor/client/OdeMessages.java
  appinventor/appengine/src/com/google/appinventor/client/explorer/commands/DeleteFileCommand.java
  appinventor/appengine/src/com/google/appinventor/client/explorer/commands/SaveScreenCheckpointCommand.java
  appinventor/appengine/src/com/google/appinventor/client/widgets/LabeledTextBox.java
  appinventor/appengine/war/static/css/Ya.css
Labels: affects: master, pull request: needs review, regression

#2162 Add missing READ_EXTERNAL_STORAGE permission for Player
  appinventor/components/src/com/google/appinventor/components/runtime/Player.java
  appinventor/components/src/com/google/appinventor/components/runtime/VideoPlayer.java
Labels: affects: master, bug, pull request: needs review

#2163 Remove Column and Row properties from Form
  appinventor/appengine/src/com/google/appinventor/client/editor/simple/components/MockVisibleComponent.java
  appinventor/appengine/src/com/google/appinventor/client/editor/youngandroid/YaFormEditor.java
Labels: affects: master, bug, pull request: needs review

#2136 Fix blockly context menu not hiding itself
  appinventor/blocklyeditor/src/blocklyeditor.js
Labels: affects: master, bug, pull request: needs review

#2152 Solving Hi-res download blocks PNG
  appinventor/blocklyeditor/src/exportBlocksImage.js
Labels: affects: master, enhancement, pull request: needs reply to review

#2137 Fix focusing on collapsed warnings/errors
  appinventor/blocklyeditor/src/warningHandler.js
Labels: affects: master, enhancement, pull request: needs reply to review

#2143 added new feature for project name in creating new project
  appinventor/appengine/src/com/google/appinventor/client/widgets/LabeledTextBox.java
  appinventor/appengine/src/com/google/appinventor/client/wizards/youngandroid/NewYoungAndroidProjectWizard.java
  appinventor/appengine/src/com/google/appinventor/client/wizards/youngandroid/RemixedYoungAndroidProjectWizard.java
  appinventor/appengine/src/com/google/appinventor/client/youngandroid/TextValidators.java
Labels: affects: master, enhancement, pull request: needs reply to review

#2150 Add drag-and-drop of resources into App Inventor workspace
  appinventor/appengine/src/com/google/appinventor/client/Ode.java
  appinventor/appengine/src/com/google/appinventor/client/OdeMessages.java
  appinventor/appengine/src/com/google/appinventor/client/explorer/youngandroid/ProjectList.java
  appinventor/appengine/src/com/google/appinventor/client/utils/HTML5DragDrop.java
  appinventor/appengine/src/com/google/appinventor/client/utils/html5dnd.js
  appinventor/appengine/src/com/google/appinventor/client/wizards/ComponentImportWizard.java
  appinventor/appengine/src/com/google/appinventor/client/youngandroid/TextValidators.java
  appinventor/appengine/war/static/css/Ya.css
Labels: affects: master, feature request, pull request: needs review

#2141 Make Camera component create Pictures directory if not exists
  appinventor/components/src/com/google/appinventor/components/runtime/Camera.java
Labels: affects: ucr, bug, pull request: needs review

#2178 Fix LineString.PointsFromString docs
  appinventor/components/src/com/google/appinventor/components/runtime/LineString.java
  appinventor/docs/html/reference/components/maps.html
  appinventor/docs/markdown/reference/components/maps.md
Labels: affects: master, documentation, pull request: needs review
