Repository mit-cml/appinventor-sources, pull requests merged in 2020-03, with the labels that each got.

#2073 Fix number block displaying non-number values
  appinventor/blocklyeditor/ploverConfig.js
  appinventor/blocklyeditor/src/field.js
Labels: affects: master, bug, pull request: needs review

#2003 Add the EmailAddresses property to activity starter. For the UCR branch
  appinventor/components/src/com/google/appinventor/components/runtime/ActivityStarter.java
Labels: affects: ucr, pull request: needs reply to review

#2049 Fix accelerometer crashing emulator if UseLegacy is off
  appinventor/components/src/com/google/appinventor/components/runtime/AccelerometerSensor.java
Labels: affects: ucr, bug, pull request: needs review

#2079 Add external issue link
  .github/ISSUE_TEMPLATE/config.yml
Labels: affects: master, documentation, pull request: needs reply to review

#2065 Support to load App Inventor over https
  appinventor/appengine/src/com/google/appinventor/client/editor/simple/components/MockMap.java
  appinventor/blocklyeditor/src/msg/en/_messages.js
  appinventor/blocklyeditor/src/replmgr.js
Labels: affects: master, enhancement, on ai2-test, pull request: needs review

#1998 Add Reverse Text Block
  appinventor/blocklyeditor/src/blocks/text.js
  appinventor/blocklyeditor/src/generators/yail/text.js
  appinventor/blocklyeditor/src/msg/en/_messages.js
  appinventor/blocklyeditor/src/versioning.js
  appinventor/buildserver/src/com/google/appinventor/buildserver/resources/runtime.scm
  appinventor/buildserver/tests/com/google/appinventor/buildserver/YailEvalTest.java
  appinventor/components/src/com/google/appinventor/components/common/YaVersion.java
  appinventor/docs/html/reference/blocks/images/text/text_reverse.png
  appinventor/docs/html/reference/blocks/text.html
  appinventor/docs/markdown/reference/blocks/images/text/text_reverse.png
  appinventor/docs/markdown/reference/blocks/text.md
Labels: affects: ucr, feature request, pull request: needs reply to review

#1943 Use onBackPressed instead of onKeyDown
  appinventor/components/src/com/google/appinventor/components/runtime/Form.java
  appinventor/components/src/com/google/appinventor/components/runtime/ListPickerActivity.java
Labels: affects: ucr, enhancement, pull request: needs review

#2086 Fix dyslexic font in context menus
  appinventor/blocklyeditor/media/ai2blockly.css
Labels: affects: master, bug, pull request: needs review

#2094 Allow ListView item highlighting programatically
  appinventor/components/src/com/google/appinventor/components/runtime/ListView.java
Labels: affects: ucr, enhancement, pull request: needs review

#2100 Fix Race Condition in Dyslexic font setting
  appinventor/appengine/src/com/google/appinventor/client/Ode.java
  appinventor/appengine/src/com/google/appinventor/client/TopToolbar.java
Labels: affects: master, pull request: needs review

#2077 Make the ExternalComponentGenerator more robust to existing directories
  appinventor/components/src/com/google/appinventor/components/scripts/ExternalComponentGenerator.java
Labels: AI Extensions, affects: master, bug, pull request: in review

#2067 Fix empty project export by non-admin users
  appinventor/appengine/src/com/google/appinventor/server/storage/ObjectifyStorageIo.java
Labels: affects: master, pull request: needs review, regression

#2091 Fix dictionary to list coercion
  appinventor/buildserver/tests/com/google/appinventor/buildserver/YailEvalTest.java
  appinventor/components/src/com/google/appinventor/components/runtime/util/YailDictionary.java
  appinventor/components/tests/com/google/appinventor/components/runtime/util/YailDictionaryTest.java
Labels: affects: ucr, bug, pull request: needs review

#2080 ProGuard for Extensions
  appinventor/components/build.xml
  appinventor/lib/proguard/LICENSE.md
  appinventor/lib/proguard/LICENSE_exception.md
  appinventor/lib/proguard/README.md
  appinventor/lib/proguard/proguard.cfg
  appinventor/lib/proguard/proguard.jar
Labels: AI Extensions, affects: master, feature request, pull request: needs review

#2075 Add radix number block
  appinventor/blocklyeditor/src/blocks/math.js
  appinventor/blocklyeditor/src/generators/yail/math.js
  appinventor/blocklyeditor/src/msg/en/_messages.js
  appinventor/docs/html/reference/blocks/images/math/numberradix.png
  appinventor/docs/html/reference/blocks/images/math/numberradix_equivalent.png
  appinventor/docs/html/reference/blocks/math.html
  appinventor/docs/markdown/reference/blocks/images/math/numberradix.png
  appinventor/docs/markdown/reference/blocks/images/math/numberradix_equivalent.png
  appinventor/docs/markdown/reference/blocks/math.md
Labels: affects: ucr, feature request, pull request: needs review

#2043 Additional functions for the WebView component
  appinventor/appengine/src/com/google/appinventor/client/youngandroid/YoungAndroidFormUpgrader.java
  appinventor/blocklyeditor/src/versioning.js
  appinventor/components/src/com/google/appinventor/components/common/YaVersion.java
  appinventor/components/src/com/google/appinventor/components/runtime/WebViewer.java
  appinventor/components/src/com/google/appinventor/components/runtime/util/FroyoUtil.java
  appinventor/docs/html/reference/components/userinterface.html
  appinventor/docs/markdown/reference/components/userinterface.md
Labels: affects: ucr, enhancement, pull request: needs reply to review

#1935 Used BluetoothSocket.isConnected on devices with APILevel >=14
  appinventor/appengine/src/com/google/appinventor/client/youngandroid/YoungAndroidFormUpgrader.java
  appinventor/blocklyeditor/src/versioning.js
  appinventor/components/src/com/google/appinventor/components/common/YaVersion.java
  appinventor/components/src/com/google/appinventor/components/runtime/BluetoothClient.java
  appinventor/components/src/com/google/appinventor/components/runtime/BluetoothConnectionBase.java
  appinventor/components/src/com/google/appinventor/components/runtime/util/BluetoothReflection.java
  appinventor/docs/html/reference/components/connectivity.html
  appinventor/docs/markdown/reference/components/connectivity.md
Labels: affects: ucr, feature request, pull request: needs reply to review

#2068 Add automatic conversion for other number bases
  appinventor/blocklyeditor/src/blocks/math.js
  appinventor/blocklyeditor/src/generators/yail/math.js
  appinventor/docs/html/reference/blocks/math.html
  appinventor/docs/markdown/reference/blocks/math.md
Labels: affects: master, feature request, pull request: needs reply to review

#2004 Handle special cases of trigonometric functions.
  appinventor/buildserver/src/com/google/appinventor/buildserver/resources/runtime.scm
  appinventor/buildserver/tests/com/google/appinventor/buildserver/YailEvalTest.java
Labels: affects: ucr, bug, pull request: in review

#1938 Navigation component
  appinventor/appengine/src/com/google/appinventor/client/Images.java
  appinventor/appengine/src/com/google/appinventor/client/OdeMessages.java
  appinventor/appengine/src/com/google/appinventor/client/editor/simple/components/utils/PropertiesUtil.java
  appinventor/appengine/src/com/google/appinventor/client/editor/simple/palette/SimpleComponentDescriptor.java
  appinventor/appengine/src/com/google/appinventor/client/editor/youngandroid/properties/YoungAndroidNavigationMethodChoicePropertyEditor.java
  appinventor/appengine/src/com/google/appinventor/images/navigation.png
  appinventor/blocklyeditor/src/blocks/components.js
  appinventor/blocklyeditor/src/msg/en/_messages.js
  appinventor/components/src/com/google/appinventor/components/common/PropertyTypeConstants.java
  appinventor/components/src/com/google/appinventor/components/common/YaVersion.java
  appinventor/components/src/com/google/appinventor/components/runtime/MapFeatureContainerBase.java
  appinventor/components/src/com/google/appinventor/components/runtime/Navigation.java
  appinventor/components/src/com/google/appinventor/components/runtime/util/ErrorMessages.java
  appinventor/components/src/com/google/appinventor/components/runtime/util/GeoJSONUtil.java
  appinventor/docs/html/reference/components/maps.html
  appinventor/docs/markdown/reference/components/maps.md
Labels: affects: ucr, feature request, pull request: needs reply to review

#2048 Make collapsed dictionary constructor look like JSON
  appinventor/blocklyeditor/src/blocks/dictionaries.js
Labels: affects: master, enhancement, pull request: needs review

#2002 First pass refactor of project explorer
  appinventor/appengine/src/com/google/appinventor/client/Ode.java
  appinventor/appengine/src/com/google/appinventor/client/OdeMessages.java
  appinventor/appengine/src/com/google/appinventor/client/OdeMessages_de.properties
  appinventor/appengine/src/com/google/appinventor/client/OdeMessages_es_ES.properties
  appinventor/appengine/src/com/google/appinventor/client/OdeMessages_fr_FR.properties
  appinventor/appengine/src/com/google/appinventor/client/OdeMessages_hu.properties
  appinventor/appengine/src/com/google/appinventor/client/OdeMessages_it_IT.properties
  appinventor/appengine/src/com/google/appinventor/client/OdeMessages_ko_KR.properties
  appinventor/appengine/src/com/google/appinventor/client/OdeMessages_nl.properties
  appinventor/appengine/src/com/google/appinventor/client/OdeMessages_pl.properties
  appinventor/appengine/src/com/google/appinventor/client/OdeMessages_pt.properties
  appinventor/appengine/src/com/google/appinventor/client/OdeMessages_pt_BR.properties
  appinventor/appengine/src/com/google/appinventor/client/OdeMessages_ru.properties
  appinventor/appengine/src/com/google/appinventor/client/OdeMessages_sv.properties
  appinventor/appengine/src/com/google/appinventor/client/OdeMessages_zh_CN.properties
  appinventor/appengine/src/com/google/appinventor/client/OdeMessages_zh_TW.properties
  appinventor/appengine/src/com/google/appinventor/client/TopToolbar.java
  appinventor/appengine/src/com/google/appinventor/client/boxes/ProjectListBox.java
  appinventor/appengine/src/com/google/appinventor/client/boxes/TrashProjectListBox.java
  appinventor/appengine/src/com/google/appinventor/client/explorer/project/Project.java
  appinventor/appengine/src/com/google/appinventor/client/explorer/project/ProjectManager.java
  appinventor/appengine/src/com/google/appinventor/client/explorer/project/ProjectManagerEventAdapter.java
  appinventor/appengine/src/com/google/appinventor/client/explorer/project/ProjectManagerEventListener.java
  appinventor/appengine/src/com/google/appinventor/client/explorer/youngandroid/ProjectList.java
  appinventor/appengine/src/com/google/appinventor/client/explorer/youngandroid/ProjectToolbar.java
  appinventor/appengine/src/com/google/appinventor/client/explorer/youngandroid/TrashProjectList.java
  appinventor/appengine/src/com/google/appinventor/client/youngandroid/TextValidators.java
  appinventor/appengine/src/com/google/appinventor/shared/rpc/project/UserProject.java
Labels: affects: master, pull request: needs reply to review, technical debt

#1732 Serial Component
  appinventor/appengine/src/com/google/appinventor/client/Images.java
  appinventor/appengine/src/com/google/appinventor/client/editor/simple/palette/SimpleComponentDescriptor.java
  appinventor/appengine/src/com/google/appinventor/images/arduino.png
  appinventor/components/build.xml
  appinventor/components/src/com/google/appinventor/components/common/YaVersion.java
  appinventor/components/src/com/google/appinventor/components/runtime/Serial.java
  appinventor/components/src/com/google/appinventor/components/runtime/util/ErrorMessages.java
  appinventor/docs/html/reference/components/connectivity.html
  appinventor/lib/physicaloid/physicaloid-library.jar
Labels: affects: ucr, enhancement, pull request: needs reply to review

#2111 Update Companion Build Dependencies
  appinventor/buildserver/build.xml
Labels: affects: master, pull request: needs review

#2112 Fix crash in Navigation component
  appinventor/components/src/com/google/appinventor/components/runtime/Navigation.java
Labels: affects: ucr, bug, pull request: needs review

#2104 Fix: OnDestroyListener doesn't fire
  appinventor/components/src/com/google/appinventor/components/runtime/Form.java
Labels: affects: master, bug, pull request: in review

#2108 Fix multiselect issue when changing tabs/windows
  appinventor/appengine/src/com/google/appinventor/client/boxes/BlockSelectorBox.java
  appinventor/appengine/src/com/google/appinventor/client/editor/simple/SimpleNonVisibleComponentsPanel.java
  appinventor/appengine/src/com/google/appinventor/client/editor/simple/components/MockCircle.java
  appinventor/appengine/src/com/google/appinventor/client/editor/simple/components/MockComponent.java
  appinventor/appengine/src/com/google/appinventor/client/editor/simple/components/MockContainer.java
  appinventor/appengine/src/com/google/appinventor/client/editor/simple/components/MockForm.java
  appinventor/appengine/src/com/google/appinventor/client/editor/simple/components/MockLineString.java
  appinventor/appengine/src/com/google/appinventor/client/editor/simple/components/MockMap.java
  appinventor/appengine/src/com/google/appinventor/client/editor/simple/components/MockMarker.java
  appinventor/appengine/src/com/google/appinventor/client/editor/simple/components/MockPolygon.java
  appinventor/appengine/src/com/google/appinventor/client/editor/simple/components/MockRectangle.java
  appinventor/appengine/src/com/google/appinventor/client/editor/simple/components/MockVisibleComponent.java
  appinventor/appengine/src/com/google/appinventor/client/editor/simple/components/utils/PropertiesUtil.java
  appinventor/appengine/src/com/google/appinventor/client/editor/youngandroid/YaBlocksEditor.java
  appinventor/appengine/src/com/google/appinventor/client/editor/youngandroid/YaFormEditor.java
  appinventor/appengine/src/com/google/appinventor/client/explorer/SourceStructureExplorer.java
  appinventor/appengine/src/com/google/appinventor/client/explorer/SourceStructureExplorerItem.java
  appinventor/appengine/src/com/google/appinventor/client/widgets/dnd/DragSourceSupport.java
  appinventor/appengine/src/com/google/appinventor/client/widgets/properties/EditableProperties.java
  appinventor/appengine/src/com/google/appinventor/client/widgets/properties/EditableProperty.java
  appinventor/appengine/src/com/google/appinventor/client/widgets/properties/PropertyEditor.java
  appinventor/components/src/com/google/appinventor/components/common/PropertyTypeConstants.java
Labels: affects: master, bug, pull request: needs review

#2113 Permit Companion to install from https
  appinventor/aiplayapp/src/edu/mit/appinventor/aicompanion3/Screen1.bky
  appinventor/aiplayapp/src/edu/mit/appinventor/aicompanion3/Screen1.yail
Labels: affects: ucr, pull request: needs review

#1731 Magnetic Field Sensor
  appinventor/appengine/src/com/google/appinventor/client/Images.java
  appinventor/appengine/src/com/google/appinventor/client/OdeMessages.java
  appinventor/appengine/src/com/google/appinventor/client/editor/simple/palette/SimpleComponentDescriptor.java
  appinventor/appengine/src/com/google/appinventor/images/magneticSensor.png
  appinventor/components/src/com/google/appinventor/components/common/YaVersion.java
  appinventor/components/src/com/google/appinventor/components/runtime/MagneticFieldSensor.java
  appinventor/docs/html/reference/components/connectivity.html
  appinventor/docs/html/reference/components/sensors.html
  appinventor/docs/markdown/reference/components/connectivity.md
  appinventor/docs/markdown/reference/components/sensors.md
Labels: affects: ucr, enhancement, pull request: needs reply to review

#2114 Fix hard-coded extension path in ExternalComponentGenerator
  appinventor/components/src/com/google/appinventor/components/scripts/ExternalComponentGenerator.java
Labels: AI Extensions, affects: master, bug, pull request: needs review

#2115 Fix recursive procedures breaking on mutation
  appinventor/blocklyeditor/src/blocks/procedures.js
Labels: affects: master, bug, pull request: needs review

#2074 Fix not being able to modify collapsed blocks
  appinventor/blocklyeditor/ploverConfig.js
  appinventor/blocklyeditor/src/block.js
  appinventor/blocklyeditor/src/block_svg.js
  appinventor/blocklyeditor/src/blocks/components.js
  appinventor/blocklyeditor/src/blocks/lexical-variables.js
  appinventor/blocklyeditor/src/blocks/procedures.js
  appinventor/blocklyeditor/src/blocks/utilities.js
  appinventor/blocklyeditor/src/input.js
  appinventor/blocklyeditor/src/rendered_connection.js
  appinventor/blocklyeditor/src/workspace_svg.js
  appinventor/blocklyeditor/tests/com/google/appinventor/mocha/block.js
  appinventor/blocklyeditor/tests/com/google/appinventor/mocha/index.html
Labels: affects: master, bug, pull request: needs reply to review

#2085 Replace All Mappings block
  appinventor/blocklyeditor/src/blocks/text.js
  appinventor/blocklyeditor/src/generators/yail/text.js
  appinventor/blocklyeditor/src/msg/en/_messages.js
  appinventor/blocklyeditor/src/versioning.js
  appinventor/buildserver/src/com/google/appinventor/buildserver/resources/runtime.scm
  appinventor/components/src/com/google/appinventor/components/common/YaVersion.java
  appinventor/components/src/com/google/appinventor/components/runtime/collect/Sets.java
  appinventor/components/src/com/google/appinventor/components/runtime/util/JavaJoinListOfStrings.java
  appinventor/components/src/com/google/appinventor/components/runtime/util/JavaStringUtils.java
  appinventor/components/tests/com/google/appinventor/components/runtime/util/JavaStringUtilsTest.java
  appinventor/docs/html/reference/blocks/images/text/replaceallmappings.png
  appinventor/docs/html/reference/blocks/text.html
  appinventor/docs/markdown/reference/blocks/images/text/replaceallmappings.png
  appinventor/docs/markdown/reference/blocks/text.md
Labels: affects: ucr, feature request, pull request: needs reply to review

#2117 Change round tooltip to include even rounding info
  appinventor/blocklyeditor/src/msg/en/_messages.js
Labels: affects: master, documentation, pull request: needs review

#2099 Reorg context menu opts. Add yail opt to events
  appinventor/blocklyeditor/src/blocklyeditor.js
  appinventor/blocklyeditor/src/blocks/components.js
Labels: affects: master, pull request: needs review, technical debt

#2120 Add missing help URLs for Serial
  appinventor/blocklyeditor/src/blocks/components.js
  appinventor/blocklyeditor/src/msg/en/_messages.js
Labels: affects: ucr, documentation, pull request: needs review

#2101 Fixes Type name to delete project/screen
  appinventor/appengine/src/com/google/appinventor/client/OdeMessages.java
  appinventor/appengine/src/com/google/appinventor/client/explorer/commands/DeleteFileCommand.java
  appinventor/appengine/src/com/google/appinventor/client/explorer/commands/SaveScreenCheckpointCommand.java
  appinventor/appengine/src/com/google/appinventor/client/widgets/LabeledTextBox.java
Labels: affects: master, feature request, pull request: needs review

#2132 Add event listener only if selecting a component
  appinventor/appengine/src/com/google/appinventor/client/editor/youngandroid/YaFormEditor.java
Labels: affects: master, bug, pull request: needs review

#2133 Show text validation errors if not in multiselect mode
  appinventor/appengine/src/com/google/appinventor/client/editor/youngandroid/YaFormEditor.java
  appinventor/appengine/src/com/google/appinventor/client/widgets/properties/PropertyEditor.java
  appinventor/appengine/src/com/google/appinventor/client/widgets/properties/TextPropertyEditorBase.java
Labels: affects: master, bug, pull request: needs review
