Repository mit-cml/appinventor-sources, pull requests merged in 2020-12, with the labels that each got.

#2116 Move to Trash menu item changes to Delete from Trash
  appinventor/appengine/src/com/google/appinventor/client/Ode.java
  appinventor/appengine/src/com/google/appinventor/client/TopPanel.java
  appinventor/appengine/src/com/google/appinventor/client/TopToolbar.java
  appinventor/appengine/src/com/google/appinventor/client/explorer/youngandroid/ProjectToolbar.java
  appinventor/appengine/src/com/google/appinventor/client/widgets/DropDownButton.java
Labels: affects: master, enhancement, pull request: needs review

#2331 Fixing the "ShowStatusBar" checkbox in the Designer.
  appinventor/appengine/src/com/google/appinventor/client/editor/simple/components/MockForm.java
Labels: affects: master, bug, pull request: needs review

#2330 Fixed Typeblocking bug in dictionaries block.
  appinventor/blocklyeditor/src/blocks/dictionaries.js
Labels: affects: master, bug, pull request: needs reply to review

#2324 Update support library for ProguardUpdate build.xml
  appinventor/components/build.xml
Labels: affects: master, pull request: needs review

#2326 Add ability to include license files in extensions
  appinventor/appengine/src/com/google/appinventor/client/OdeMessages.java
  appinventor/appengine/src/com/google/appinventor/client/editor/simple/ComponentDatabase.java
  appinventor/appengine/src/com/google/appinventor/client/editor/simple/palette/ComponentHelpWidget.java
  appinventor/appengine/src/com/google/appinventor/client/editor/simple/palette/SimpleComponentDescriptor.java
  appinventor/appengine/src/com/google/appinventor/server/DownloadServlet.java
  appinventor/appengine/src/com/google/appinventor/shared/simple/ComponentDatabaseInterface.java
  appinventor/components/src/com/google/appinventor/components/annotations/DesignerComponent.java
  appinventor/components/src/com/google/appinventor/components/scripts/ComponentDescriptorGenerator.java
  appinventor/components/src/com/google/appinventor/components/scripts/ComponentProcessor.java
  appinventor/components/src/com/google/appinventor/components/scripts/ExternalComponentGenerator.java
Labels: affects: master, enhancement, pull request: needs reply to review

#2319 Reserve some Scheme keywords
  appinventor/appengine/src/com/google/appinventor/client/OdeMessages.java
  appinventor/appengine/src/com/google/appinventor/client/youngandroid/TextValidators.java
Labels: affects: master, bug, pull request: needs reply to review

#2297 Patch Request added to Web Component
  appinventor/appengine/src/com/google/appinventor/client/youngandroid/YoungAndroidFormUpgrader.java
  appinventor/blocklyeditor/src/versioning.js
  appinventor/components/src/com/google/appinventor/components/common/YaVersion.java
  appinventor/components/src/com/google/appinventor/components/runtime/Web.java
  appinventor/components/src/com/google/appinventor/components/runtime/util/ErrorMessages.java
  appinventor/docs/html/reference/components/connectivity.html
  appinventor/docs/markdown/reference/components/connectivity.md
Labels: affects: ucr, feature request, pull request: needs reply to review

#2241 Fix CSV parsing issues in presence of trailing comma
  appinventor/components/src/com/google/appinventor/components/runtime/util/CsvUtil.java
  appinventor/components/tests/com/google/appinventor/components/runtime/util/CsvUtilTest.java
Labels: affects: ucr, bug, pull request: needs review

#2240 Fix instance typing and cleanup typing
  appinventor/blocklyeditor/src/blocks/utilities.js
Labels: affects: master, bug, pull request: needs reply to review
