Repository mit-cml/appinventor-sources, pull requests merged in 2020-09, with the labels that each got.

#2303 Fix loading projects with contains block in non-English languages
  appinventor/blocklyeditor/src/msg/de/_messages.js
  appinventor/blocklyeditor/src/msg/es_es/_messages.js
  appinventor/blocklyeditor/src/msg/fr_fr/_messages.js
  appinventor/blocklyeditor/src/msg/hu/_messages.js
  appinventor/blocklyeditor/src/msg/it_it/_messages.js
  appinventor/blocklyeditor/src/msg/ko_kr/_messages.js
  appinventor/blocklyeditor/src/msg/nl/_messages.js
  appinventor/blocklyeditor/src/msg/pl/_messages.js
  appinventor/blocklyeditor/src/msg/pt/_messages.js
  appinventor/blocklyeditor/src/msg/pt_br/_messages.js
  appinventor/blocklyeditor/src/msg/ru/_messages.js
  appinventor/blocklyeditor/src/msg/sv/_messages.js
  appinventor/blocklyeditor/src/msg/zh_cn/_messages.js
  appinventor/blocklyeditor/src/msg/zh_tw/_messages.js
Labels: affects: master, pull request: needs review, regression

#2302 Fix exception when cancelling asset removal
  appinventor/appengine/src/com/google/appinventor/client/explorer/commands/DeleteFileCommand.java
Labels: affects: master, pull request: ready to push to Gerrit, regression

#2275 URL encode faultData in bug report
  appinventor/appengine/src/com/google/appinventor/client/BugReport.java
Labels: affects: master, bug, pull request: ready to push to Gerrit

#2310 Chinese translation for contains any and contains all blocks
  appinventor/blocklyeditor/src/msg/zh_cn/_messages.js
  appinventor/blocklyeditor/src/msg/zh_tw/_messages.js
Labels: affects: master, pull request: needs reply to review, translation

#2306 Make componentcreator.py compatible with Python3.x
  appinventor/misc/componentcreator/componentcreator.py
Labels: affects: master, pull request: needs review, technical debt

#2279 Change name of "My Projects" toolbar menu to "File" or something else
  appinventor/appengine/src/com/google/appinventor/client/OdeMessages.java
Labels: affects: master, enhancement, pull request: ready to push to Gerrit

#2215 Clean up flydowns
  appinventor/blocklyeditor/ploverConfig.js
  appinventor/blocklyeditor/src/blocks/components.js
  appinventor/blocklyeditor/src/field_event_flydown.js
  appinventor/blocklyeditor/src/field_flydown.js
  appinventor/blocklyeditor/src/field_parameter_flydown.js
  appinventor/blocklyeditor/src/field_procedure_flydown.js
Labels: affects: master, pull request: ready to push to Gerrit, technical debt
