Repository mit-cml/appinventor-sources, pull requests merged in 2020-11, with the labels that each got.

#2340 De-bounce the Publish to Gallery button
  appinventor/appengine/src/com/google/appinventor/client/DesignToolbar.java
  appinventor/appengine/src/com/google/appinventor/client/explorer/youngandroid/ProjectToolbar.java
Labels: affects: master, pull request: needs review

#2341 Add Gallery Readonly Flag
  appinventor/appengine/src/com/google/appinventor/client/DesignToolbar.java
  appinventor/appengine/src/com/google/appinventor/client/Ode.java
  appinventor/appengine/src/com/google/appinventor/client/explorer/youngandroid/ProjectToolbar.java
  appinventor/appengine/src/com/google/appinventor/server/UserInfoServiceImpl.java
  appinventor/appengine/src/com/google/appinventor/shared/rpc/user/Config.java
Labels: affects: master, pull request: in review

#1996 Load Blockly translations as needed using JSON files
  appinventor/appengine/build.xml
  appinventor/appengine/src/com/google/appinventor/YaClient.gwt.xml
  appinventor/appengine/src/com/google/appinventor/client/Ode.java
  appinventor/appengine/src/com/google/appinventor/client/OdeMessages_lt.properties
  appinventor/appengine/src/com/google/appinventor/client/editor/youngandroid/BlocklyPanel.java
  appinventor/appengine/src/com/google/appinventor/client/editor/youngandroid/YaProjectEditor.java
  appinventor/appengine/src/com/google/appinventor/client/editor/youngandroid/i18n/BlocklyMsg.java
  appinventor/appengine/src/com/google/appinventor/client/editor/youngandroid/i18n/BlocklyTranslationGenerator.java
  appinventor/appengine/src/com/google/appinventor/client/languages.json
  appinventor/blocklyeditor/build.xml
  appinventor/blocklyeditor/ploverConfig.js
  appinventor/blocklyeditor/src/backpackFlyout.js
  appinventor/blocklyeditor/src/blocks/utilities.js
  appinventor/blocklyeditor/src/demos/yail/yail_testing_index.html
  appinventor/blocklyeditor/src/language_switch.js
  appinventor/blocklyeditor/src/msg.js
  appinventor/blocklyeditor/src/msg/BlocklyTranslationGenerator.java
  appinventor/blocklyeditor/src/msg/ai_blockly/messages.json
  appinventor/blocklyeditor/src/msg/ai_blockly/messages_de.json
  appinventor/blocklyeditor/src/msg/ai_blockly/messages_es.json
  appinventor/blocklyeditor/src/msg/ai_blockly/messages_fr.json
  appinventor/blocklyeditor/src/msg/ai_blockly/messages_he.json
  appinventor/blocklyeditor/src/msg/ai_blockly/messages_hu.json
  appinventor/blocklyeditor/src/msg/ai_blockly/messages_it.json
  appinventor/blocklyeditor/src/msg/ai_blockly/messages_ko.json
  appinventor/blocklyeditor/src/msg/ai_blockly/messages_lt.json
  appinventor/blocklyeditor/src/msg/ai_blockly/messages_nl.json
  appinventor/blocklyeditor/src/msg/ai_blockly/messages_pl.json
  appinventor/blocklyeditor/src/msg/ai_blockly/messages_pt.json
  appinventor/blocklyeditor/src/msg/ai_blockly/messages_pt_br.json
  appinventor/blocklyeditor/src/msg/ai_blockly/messages_ru.json
  appinventor/blocklyeditor/src/msg/ai_blockly/messages_sv.json
  appinventor/blocklyeditor/src/msg/ai_blockly/messages_zh_cn.json
  appinventor/blocklyeditor/src/msg/ai_blockly/messages_zh_tw.json
  appinventor/blocklyeditor/src/msg/de/_messages.js
  appinventor/blocklyeditor/src/msg/en/_messages.js
  appinventor/blocklyeditor/src/msg/es_es/_messages.js
  appinventor/blocklyeditor/src/msg/fr_fr/_messages.js
  appinventor/blocklyeditor/src/msg/hu/_messages.js
  appinventor/blocklyeditor/src/msg/it_it/_messages.js
  appinventor/blocklyeditor/src/msg/ko_kr/_messages.js
  appinventor/blocklyeditor/src/msg/lt/_messages.js
  appinventor/blocklyeditor/src/msg/nl/_messages.js
  appinventor/blocklyeditor/src/msg/pl/_messages.js
  appinventor/blocklyeditor/src/msg/pt/_messages.js
  appinventor/blocklyeditor/src/msg/pt_br/_messages.js
  appinventor/blocklyeditor/src/msg/ru/_messages.js
  appinventor/blocklyeditor/src/msg/sv/_messages.js
  appinventor/blocklyeditor/src/msg/zh_cn/_messages.js
  appinventor/blocklyeditor/src/msg/zh_tw/_messages.js
  appinventor/blocklyeditor/tests/com/google/appinventor/blocklyeditor/component_database_tests.js
  appinventor/blocklyeditor/tests/com/google/appinventor/blocklyeditor/factorialTest.js
  appinventor/blocklyeditor/tests/com/google/appinventor/blocklyeditor/makeQuizTest.js
  appinventor/blocklyeditor/tests/com/google/appinventor/blocklyeditor/moleMashTest.js
  appinventor/blocklyeditor/tests/com/google/appinventor/blocklyeditor/pictureCycleTest.js
  appinventor/blocklyeditor/tests/com/google/appinventor/blocklyeditor/underscoreTest.js
  appinventor/blocklyeditor/tests/com/google/appinventor/generators_unit/generator_test_mainRoutine.js
  appinventor/build-common.xml
Labels: affects: master, enhancement, pull request: needs review
