Repository mit-cml/appinventor-sources, pull requests merged in 2020-01, with the labels that each got.

#1934 Add refresh companion item to connect menu
  appinventor/appengine/src/com/google/appinventor/client/OdeMessages.java
  appinventor/appengine/src/com/google/appinventor/client/TopToolbar.java
  appinventor/appengine/src/com/google/appinventor/client/editor/youngandroid/BlocklyPanel.java
  appinventor/appengine/src/com/google/appinventor/client/editor/youngandroid/YaBlocksEditor.java
  appinventor/blocklyeditor/src/replmgr.js
Labels: affects: master, feature request, pull request: ready to push to Gerrit

#1968 Fix String comparisons
  appinventor/appengine/src/com/google/appinventor/client/DesignToolbar.java
  appinventor/appengine/src/com/google/appinventor/client/editor/simple/ComponentDatabase.java
  appinventor/appengine/src/com/google/appinventor/client/editor/simple/components/MockComponent.java
  appinventor/appengine/src/com/google/appinventor/client/editor/youngandroid/YaBlocksEditor.java
  appinventor/appengine/src/com/google/appinventor/client/editor/youngandroid/YaFormEditor.java
  appinventor/appengine/src/com/google/appinventor/client/widgets/properties/SubsetJSONPropertyEditor.java
  appinventor/appengine/src/com/google/appinventor/server/project/youngandroid/YoungAndroidProjectService.java
  appinventor/appengine/src/com/google/appinventor/shared/rpc/user/User.java
  appinventor/common/src/com/google/appinventor/common/utils/StringUtils.java
  appinventor/components/src/com/google/appinventor/components/runtime/util/AccountChooser.java
Labels: affects: master, bug, pull request: in review

#1858 Mock Container delete all child components
  appinventor/appengine/src/com/google/appinventor/client/editor/simple/components/MockContainer.java
Labels: affects: master, bug, pull request: ready to push to Gerrit

#1957 Fix camera failure on Android 10
  appinventor/components/src/com/google/appinventor/components/runtime/Camera.java
Labels: affects: ucr, bug, pull request: needs review

#1971 Fix bad call to undefined getTabCatcherElement
  appinventor/blocklyeditor/src/blocks/components.js
Labels: affects: master, pull request: needs review, regression

#1973 Update lists.js
  appinventor/blocklyeditor/src/blocks/lists.js
Labels: affects: master, bug, pull request: in review

#1972 Implement accept attribute on file inputs
  appinventor/appengine/src/com/google/appinventor/client/editor/youngandroid/properties/YoungAndroidGeoJSONPropertyEditor.java
  appinventor/appengine/src/com/google/appinventor/client/wizards/ComponentImportWizard.java
  appinventor/appengine/src/com/google/appinventor/client/wizards/ComponentUploadWizard.java
  appinventor/appengine/src/com/google/appinventor/client/wizards/FileUploadWizard.java
  appinventor/appengine/src/com/google/appinventor/client/wizards/KeystoreUploadWizard.java
  appinventor/appengine/src/com/google/appinventor/client/wizards/ProjectUploadWizard.java
Labels: affects: master, enhancement, pull request: needs review

#1132 Added 'devmode' target
  README.md
  appinventor/appengine/build.xml
  appinventor/appengine/src/com/google/appinventor/client/editor/simple/components/MockComponentsUtil.java
  appinventor/build.xml
  appinventor/lib/gwt/2.8.1-patched/gwt-codeserver.jar
Labels: affects: master, enhancement, pull request: needs reply to review

#1979 Fix broken gallery resources due to route refactor
  appinventor/appengine/src/com/google/appinventor/client/GalleryClient.java
  appinventor/appengine/src/com/google/appinventor/client/GalleryGuiFactory.java
  appinventor/appengine/src/com/google/appinventor/client/explorer/youngandroid/GalleryImages.java
  appinventor/appengine/src/com/google/appinventor/client/explorer/youngandroid/GalleryPage.java
  appinventor/appengine/src/com/google/appinventor/client/explorer/youngandroid/ProfilePage.java
  appinventor/appengine/src/com/google/appinventor/client/explorer/youngandroid/androidIcon.png
  appinventor/appengine/src/com/google/appinventor/client/explorer/youngandroid/genericApp.png
  appinventor/appengine/src/com/google/appinventor/shared/rpc/project/GalleryApp.java
Labels: affects: master, pull request: needs review, regression

#1980 Fix broken MockMap assets
  appinventor/appengine/src/com/google/appinventor/client/editor/simple/components/MockMap.java
Labels: affects: master, pull request: needs review, regression

#1984 Fix minor bugs identified by 'devmode'
  appinventor/appengine/src/com/google/appinventor/client/editor/simple/components/MockCheckBox.java
  appinventor/appengine/src/com/google/appinventor/client/editor/simple/components/MockSwitch.java
  appinventor/appengine/src/com/google/appinventor/client/widgets/properties/TextAreaPropertyEditor.java
Labels: affects: master, bug, pull request: needs review

#1983 Don't show comments of collapsed blocks
  appinventor/blocklyeditor/src/workspace_svg.js
Labels: affects: master, bug, pull request: needs review

#1992 Fix potential resource leak in JsonUtil
  appinventor/components/src/com/google/appinventor/components/runtime/util/JsonUtil.java
Labels: affects: ucr, bug, pull request: needs review

#1990 Add HelloPurrStarter as a built-in template
  appinventor/appengine/war/templates/HelloPurrStarter/HelloPurrStarter.json
  appinventor/appengine/war/templates/HelloPurrStarter/HelloPurrStarter.zip
Labels: affects: master, enhancement, pull request: needs reply to review

#1991 Fix miscellaneous issues in blocks editor code
  appinventor/blocklyeditor/src/blocks/lists.js
  appinventor/blocklyeditor/src/drawer.js
  appinventor/blocklyeditor/src/msg/en/_messages.js
Labels: affects: master, pull request: needs review, technical debt

#1986 Update README.md
  README.md
Labels: affects: master, documentation, pull request: needs reply to review

#1944 Convert \n in browser designer page
  appinventor/appengine/src/com/google/appinventor/client/editor/simple/components/MockLabel.java
Labels: affects: master, enhancement, pull request: needs reply to review

#1995 JsonComponentDescription is needed for buildserver
  appinventor/buildserver/build.xml
Labels: affects: master, pull request: in review

#1977 Add ant flag force.builddocs
  appinventor/appengine/build.xml
Labels: affects: master, pull request: needs review, technical debt

#1994 Include if-else and if-elseif-else mutations in blocks drawer
  appinventor/blocklyeditor/src/drawer.js
Labels: affects: master, enhancement, on ai2-test, pull request: needs review

#1993 Improve app resizing on Chromebooks
  appinventor/buildserver/src/com/google/appinventor/buildserver/Compiler.java
  appinventor/components/src/com/google/appinventor/components/runtime/util/ScreenDensityUtil.java
  appinventor/components/src/com/google/appinventor/components/runtime/util/SdkLevel.java
Labels: affects: ucr, bug, on ai2-test, pull request: ready to push to Gerrit

#1958 Wrap typeblock updates in an event group
  appinventor/blocklyeditor/src/typeblock.js
Labels: affects: master, bug, pull request: needs review

#2001 Update build.xml
  appinventor/components/build.xml
Labels: affects: ucr, pull request: needs review

#1978 Add READ_CALL_LOG permission for Android 9
  appinventor/components/src/com/google/appinventor/components/runtime/PhoneCall.java
Labels: affects: ucr, on ai2-test, pull request: needs review, regression

#1956 Fix adaptive icon scaling in latest release
  appinventor/aiplayapp/assets/AI2Companion-Icon.png
  appinventor/buildserver/src/com/google/appinventor/buildserver/Compiler.java
Labels: affects: ucr, enhancement, pull request: needs review

#1959 Send code after asset refresh, not before
  appinventor/appengine/src/com/google/appinventor/client/AssetManager.java
  appinventor/blocklyeditor/src/replmgr.js
Labels: affects: master, bug, pull request: needs review

#2000 ComponentProcessor should use helpUrl and not description
  appinventor/components/src/com/google/appinventor/components/scripts/ComponentProcessor.java
Labels: affects: master, pull request: needs review, regression

#2007 Fix automatic sizing of mock toggle components
  appinventor/appengine/src/com/google/appinventor/client/editor/simple/components/MockCheckBox.java
  appinventor/appengine/src/com/google/appinventor/client/editor/simple/components/MockComponentsUtil.java
  appinventor/appengine/src/com/google/appinventor/client/editor/simple/components/MockSwitch.java
  appinventor/appengine/src/com/google/appinventor/client/editor/simple/components/MockToggleBase.java
  appinventor/appengine/src/com/google/appinventor/client/editor/simple/components/MockWrapper.java
Labels: affects: master, pull request: needs review, regression

#2010 Allow only class files as related external classes
  appinventor/components/src/com/google/appinventor/components/scripts/ExternalComponentGenerator.java
Labels: AI Extensions, affects: master, pull request: needs review, regression
