Repository mit-cml/appinventor-sources, pull requests merged in 2020-06, with the labels that each got.

#2206 Fix nullptr in text connection check
  appinventor/blocklyeditor/src/blocks/text.js
  appinventor/blocklyeditor/tests/com/google/appinventor/mocha/text.js
Labels: affects: master, bug, pull request: needs reply to review

#2191 Implement metadata annotations for extensions
  appinventor/buildserver/src/com/google/appinventor/buildserver/Compiler.java
  appinventor/components/src/com/google/appinventor/components/annotations/UsesActivityMetadata.java
  appinventor/components/src/com/google/appinventor/components/annotations/UsesApplicationMetadata.java
  appinventor/components/src/com/google/appinventor/components/common/ComponentDescriptorConstants.java
  appinventor/components/src/com/google/appinventor/components/scripts/ComponentListGenerator.java
  appinventor/components/src/com/google/appinventor/components/scripts/ComponentProcessor.java
Labels: affects: master, feature request, pull request: in review, pull request: needs review

#2212 Do not include BlocksToolkit definition in codegen
  appinventor/blocklyeditor/src/generators/yail.js
Labels: affects: master, bug, pull request: needs review

#2166 Fix components not being accepted as dictionary keys
  appinventor/build-common.xml
  appinventor/buildserver/src/com/google/appinventor/buildserver/resources/runtime.scm
  appinventor/buildserver/tests/com/google/appinventor/buildserver/YailEvalTest.java
  appinventor/buildserver/tests/com/google/appinventor/buildserver/testComponentsAsDictKeys.scm
Labels: affects: ucr, bug, pull request: needs review

#2211 Add support for Chromebooks
  appinventor/appengine/src/com/google/appinventor/client/OdeMessages.java
  appinventor/appengine/src/com/google/appinventor/client/TopToolbar.java
  appinventor/appengine/src/com/google/appinventor/client/editor/FileEditor.java
  appinventor/appengine/src/com/google/appinventor/client/editor/youngandroid/BlocklyPanel.java
  appinventor/appengine/src/com/google/appinventor/client/editor/youngandroid/YaBlocksEditor.java
  appinventor/blocklyeditor/src/replmgr.js
  appinventor/buildserver/src/com/google/appinventor/buildserver/Compiler.java
  appinventor/components/src/com/google/appinventor/components/runtime/ReplForm.java
  appinventor/components/src/com/google/appinventor/components/runtime/util/WebRTCNativeMgr.java
Labels: affects: master, enhancement, pull request: needs review

#2217 Implement annotations for Services and Content Providers
  appinventor/buildserver/src/com/google/appinventor/buildserver/Compiler.java
  appinventor/components/src/com/google/appinventor/components/annotations/UsesContentProviders.java
  appinventor/components/src/com/google/appinventor/components/annotations/UsesServices.java
  appinventor/components/src/com/google/appinventor/components/annotations/androidmanifest/GrantUriPermissionElement.java
  appinventor/components/src/com/google/appinventor/components/annotations/androidmanifest/PathPermissionElement.java
  appinventor/components/src/com/google/appinventor/components/annotations/androidmanifest/ProviderElement.java
  appinventor/components/src/com/google/appinventor/components/annotations/androidmanifest/ServiceElement.java
  appinventor/components/src/com/google/appinventor/components/common/ComponentDescriptorConstants.java
  appinventor/components/src/com/google/appinventor/components/scripts/ComponentDescriptorGenerator.java
  appinventor/components/src/com/google/appinventor/components/scripts/ComponentListGenerator.java
  appinventor/components/src/com/google/appinventor/components/scripts/ComponentProcessor.java
Labels: affects: master, feature request, pull request: in review
