Repository mit-cml/appinventor-sources, pull requests merged in 2020-08, with the labels that each got.

#2273 Confirm overwrite of assets when dropping files into project
  appinventor/appengine/src/com/google/appinventor/client/utils/HTML5DragDrop.java
  appinventor/appengine/src/com/google/appinventor/client/utils/html5dnd.js
Labels: affects: master, bug, pull request: needs review

#2270 Do not open projects in the Trash
  appinventor/appengine/src/com/google/appinventor/client/explorer/youngandroid/ProjectList.java
Labels: affects: master, bug, pull request: ready to push to Gerrit

#2269 Fix ghost dropdown when switching logic blocks to external inputs
  appinventor/blocklyeditor/src/blocks/logic.js
Labels: affects: master, bug, pull request: ready to push to Gerrit

#2265 Issue #2257: Fixed Empty property descriptions overriding previous no…
  appinventor/components/src/com/google/appinventor/components/scripts/ComponentProcessor.java
Labels: affects: master, bug, pull request: ready to push to Gerrit

#2263 Exclude markdown files from AndroidRuntime.jar
  appinventor/components/build.xml
Labels: affects: master, pull request: ready to push to Gerrit, technical debt

#2274 Fix app crash when failing to put/post in Web component
  appinventor/components/src/com/google/appinventor/components/runtime/Web.java
Labels: affects: ucr, pull request: in review, regression

#2244 Fix merging of compressed AIAs
  appinventor/aimerger/AI2MergerApp.jar
  appinventor/aimerger/src/edu/mills/feeney/thesis/aimerger/AIMerger.java
Labels: affects: master, bug, pull request: needs review

#2272 Implement a universal URL format for assets in WebViewer
  appinventor/components/src/com/google/appinventor/components/runtime/WebViewer.java
  appinventor/components/src/com/google/appinventor/components/runtime/util/FroyoUtil.java
  appinventor/components/src/com/google/appinventor/components/runtime/util/FroyoWebViewClient.java
  appinventor/components/src/com/google/appinventor/components/runtime/util/HoneycombWebViewClient.java
  appinventor/docs/html/reference/components/userinterface.html
  appinventor/docs/markdown/reference/components/userinterface.md
Labels: affects: ucr, feature request, pull request: needs review

#2286 Add contains any and contains all options
  appinventor/blocklyeditor/src/blocks/text.js
  appinventor/blocklyeditor/src/generators/yail/text.js
  appinventor/blocklyeditor/src/msg/en/_messages.js
  appinventor/blocklyeditor/src/versioning.js
  appinventor/buildserver/src/com/google/appinventor/buildserver/resources/runtime.scm
  appinventor/components/src/com/google/appinventor/components/common/YaVersion.java
  appinventor/docs/html/reference/blocks/images/text/contains.png
  appinventor/docs/html/reference/blocks/images/text/containsall.png
  appinventor/docs/html/reference/blocks/images/text/containsany.png
  appinventor/docs/html/reference/blocks/text.html
  appinventor/docs/markdown/reference/blocks/images/text/contains.png
  appinventor/docs/markdown/reference/blocks/images/text/containsall.png
  appinventor/docs/markdown/reference/blocks/images/text/containsany.png
  appinventor/docs/markdown/reference/blocks/text.md
Labels: affects: ucr, feature request, pull request: ready to push to Gerrit

#2300 Do not capture copy events where user selection exists
  appinventor/appengine/src/com/google/appinventor/client/editor/youngandroid/YaFormEditor.java
Labels: affects: master, pull request: needs review, regression
