Repository mit-cml/appinventor-sources, pull requests merged in 2021-01, with the labels that each got.

#2363 Fix Chinese and Brazilian Portuguese translation loading
  appinventor/blocklyeditor/build.xml
  appinventor/blocklyeditor/src/msg/BlocklyTranslationGenerator.java
  appinventor/blocklyeditor/src/msg/ai_blockly/messages_de.json
  appinventor/blocklyeditor/src/msg/ai_blockly/messages_es.json
  appinventor/blocklyeditor/src/msg/ai_blockly/messages_he.json
  appinventor/blocklyeditor/src/msg/ai_blockly/messages_pt_BR.json
  appinventor/blocklyeditor/src/msg/ai_blockly/messages_zh_CN.json
  appinventor/blocklyeditor/src/msg/ai_blockly/messages_zh_TW.json
  appinventor/blocklyeditor/tests/com/google/appinventor/blocklyeditor/component_database_tests.js
  appinventor/blocklyeditor/tests/com/google/appinventor/blocklyeditor/factorialTest.js
  appinventor/blocklyeditor/tests/com/google/appinventor/blocklyeditor/makeQuizTest.js
  appinventor/blocklyeditor/tests/com/google/appinventor/blocklyeditor/moleMashTest.js
  appinventor/blocklyeditor/tests/com/google/appinventor/blocklyeditor/pictureCycleTest.js
  appinventor/blocklyeditor/tests/com/google/appinventor/blocklyeditor/underscoreTest.js
  appinventor/blocklyeditor/tests/com/google/appinventor/generators_unit/generator_test_mainRoutine.js
Labels: affects: master, bug, pull request: needs review

#2351 Open external links in Help menu in separate tabs
  appinventor/appengine/src/com/google/appinventor/client/TopToolbar.java
Labels: affects: master, enhancement, on ai2-test, pull request: needs review

#2380 Fix PlayApp build on Windows
  appinventor/buildserver/src/com/google/appinventor/buildserver/Compiler.java
Labels: affects: master, pull request: needs review, regression

#2353 Fix: Load Tutorial URLs with https
  appinventor/appengine/src/com/google/appinventor/client/Ode.java
Labels: affects: master, pull request: needs review, technical debt

#2368 Correct order of blocks affecting global variable references
  appinventor/blocklyeditor/src/blocks/lexical-variables.js
  appinventor/blocklyeditor/src/field_lexical_variable.js
  appinventor/blocklyeditor/src/warningHandler.js
Labels: affects: master, bug, pull request: needs review

#2379 Fix PNG export when browser extensions inject CSS
  appinventor/blocklyeditor/src/exportBlocksImage.js
Labels: affects: master, bug, pull request: needs review

#2348 Removes Unused Imports (Compile Time Improvement) and clean code
  appinventor/aimerger/src/edu/mills/feeney/thesis/aimerger/AIMerger.java
  appinventor/aimerger_for_appinv_classic/src/edu/mills/feeney/thesis/aimerger/AIMerger.java
  appinventor/appengine/src/com/google/appinventor/client/AdminUserList.java
  appinventor/appengine/src/com/google/appinventor/client/Ode.java
  appinventor/appengine/src/com/google/appinventor/client/TopPanel.java
  appinventor/appengine/src/com/google/appinventor/client/boxes/ViewerBox.java
  appinventor/appengine/src/com/google/appinventor/client/editor/simple/components/MockCloudDB.java
  appinventor/appengine/src/com/google/appinventor/client/editor/simple/components/MockWebViewer.java
  appinventor/appengine/src/com/google/appinventor/client/editor/youngandroid/properties/YoungAndroidDefaultURLPropertyEditor.java
  appinventor/appengine/src/com/google/appinventor/client/explorer/commands/WarningDialogCommand.java
  appinventor/appengine/src/com/google/appinventor/client/properties/Properties.java
  appinventor/appengine/src/com/google/appinventor/client/widgets/Toolbar.java
  appinventor/appengine/src/com/google/appinventor/client/wizards/ComponentImportWizard.java
  appinventor/appengine/src/com/google/appinventor/client/wizards/ComponentUploadWizard.java
  appinventor/appengine/src/com/google/appinventor/client/wizards/DownloadUserSourceWizard.java
  appinventor/appengine/src/com/google/appinventor/client/wizards/InputTemplateUrlWizard.java
  appinventor/appengine/src/com/google/appinventor/client/wizards/youngandroid/NewYoungAndroidProjectWizard.java
  appinventor/appengine/src/com/google/appinventor/server/AdminInfoServiceImpl.java
  appinventor/appengine/src/com/google/appinventor/server/FileExporterImpl.java
  appinventor/appengine/src/com/google/appinventor/server/LoginServlet.java
  appinventor/appengine/src/com/google/appinventor/server/Whitelist.java
  appinventor/appengine/src/com/google/appinventor/server/project/youngandroid/YoungAndroidProjectService.java
Labels: affects: master, pull request: needs review, technical debt

#2358 Build Tools for App Inventor
  README.md
  buildtools
  buildtools.cmd
Labels: affects: master, pull request: needs reply to review, technical debt

#2396 Fix Restore button in Deleted Projects View
  appinventor/appengine/src/com/google/appinventor/client/explorer/youngandroid/ProjectToolbar.java
Labels: affects: master, bug, pull request: needs review

#2059 GitHub Actions
  .github/workflows/ant.yml
Labels: affects: master, pull request: needs review, technical debt
