Repository mit-cml/appinventor-sources, pull requests merged in 2021-05, with the labels that each got.

#2472 Implements visual accessibility features for designer and companion.
  appinventor/appengine/src/com/google/appinventor/client/editor/simple/components/MockButtonBase.java
  appinventor/appengine/src/com/google/appinventor/client/editor/simple/components/MockLabel.java
  appinventor/appengine/src/com/google/appinventor/client/editor/simple/components/MockPasswordTextBox.java
  appinventor/appengine/src/com/google/appinventor/client/editor/simple/components/MockTextBoxBase.java
  appinventor/appengine/src/com/google/appinventor/client/editor/simple/components/MockToggleBase.java
  appinventor/appengine/src/com/google/appinventor/client/youngandroid/YoungAndroidFormUpgrader.java
  appinventor/blocklyeditor/src/versioning.js
  appinventor/components/src/com/google/appinventor/components/common/YaVersion.java
  appinventor/components/src/com/google/appinventor/components/runtime/AccessibleComponent.java
  appinventor/components/src/com/google/appinventor/components/runtime/ButtonBase.java
  appinventor/components/src/com/google/appinventor/components/runtime/Canvas.java
  appinventor/components/src/com/google/appinventor/components/runtime/ComponentContainer.java
  appinventor/components/src/com/google/appinventor/components/runtime/Form.java
  appinventor/components/src/com/google/appinventor/components/runtime/HVArrangement.java
  appinventor/components/src/com/google/appinventor/components/runtime/Image.java
  appinventor/components/src/com/google/appinventor/components/runtime/Label.java
  appinventor/components/src/com/google/appinventor/components/runtime/MapFeatureContainerBase.java
  appinventor/components/src/com/google/appinventor/components/runtime/TableArrangement.java
  appinventor/components/src/com/google/appinventor/components/runtime/TextBoxBase.java
  appinventor/components/src/com/google/appinventor/components/runtime/ToggleBase.java
  appinventor/docs/html/reference/components/userinterface.html
  appinventor/docs/markdown/reference/components/userinterface.md
Labels: affects: ucr, feature request, pull request: needs reply to review

#2446 Remove hard-coded list of allowed Tutorial URLs
  appinventor/appengine/src/com/google/appinventor/client/Ode.java
  appinventor/appengine/src/com/google/appinventor/server/UserInfoServiceImpl.java
  appinventor/appengine/src/com/google/appinventor/server/storage/ObjectifyStorageIo.java
  appinventor/appengine/src/com/google/appinventor/server/storage/StorageIo.java
  appinventor/appengine/src/com/google/appinventor/server/storage/StoredData.java
  appinventor/appengine/src/com/google/appinventor/shared/rpc/user/Config.java
Labels: affects: master, pull request: needs review

#2488 Implement a service expiry notice
  appinventor/appengine/src/com/google/appinventor/client/Ode.java
  appinventor/appengine/src/com/google/appinventor/client/widgets/ExpiredServiceOverlay.java
  appinventor/appengine/src/com/google/appinventor/client/widgets/ExpiredServiceOverlay.ui.xml
  appinventor/appengine/src/com/google/appinventor/server/UserInfoServiceImpl.java
  appinventor/appengine/src/com/google/appinventor/shared/rpc/user/Config.java
  appinventor/appengine/war/WEB-INF/appengine-web.xml
Labels: affects: master, enhancement, pull request: needs review

#2457 New test Class for Label Component
  appinventor/components/tests/com/google/appinventor/components/runtime/LabelTest.java
Labels: affects: master, pull request: needs review, technical debt

#2491 Fix issue with extension info being lost in builds
  appinventor/buildserver/src/com/google/appinventor/buildserver/Compiler.java
Labels: affects: master, bug, pull request: needs review
