Repository mit-cml/appinventor-sources, pull requests merged in 2021-09, with the labels that each got.

#2553 Support Whitespaces for the Sources' File Paths
  appinventor/appengine/build.xml
  appinventor/blocklyeditor/build.xml
Labels: bug, pull request: needs review, affects: master

#2556 Fix contains/contains any/contains all in traditional chinese
  appinventor/blocklyeditor/src/msg/ai_blockly/messages_zh_CN.json
  appinventor/blocklyeditor/src/msg/ai_blockly/messages_zh_TW.json
Labels: pull request: needs review, affects: master, regression

#2527 Refactor: Handle default values cleanly
  appinventor/buildserver/src/com/google/appinventor/buildserver/Compiler.java
  appinventor/buildserver/src/com/google/appinventor/buildserver/Project.java
Labels: pull request: needs review, technical debt, affects: master

#2552 Move build tools to its proper dir "/tools/"
  appinventor/buildserver/build.xml
  appinventor/buildserver/src/com/google/appinventor/buildserver/Compiler.java
  appinventor/components/build.xml
Labels: pull request: needs review, technical debt, affects: master

#2521 Update string in generateActivityMetadata()
  appinventor/buildserver/src/com/google/appinventor/buildserver/Compiler.java
Labels: pull request: needs review, technical debt, affects: master
