Repository mit-cml/appinventor-sources, pull requests merged in 2021-04, with the labels that each got.

#2383 Fix text not equals semantics
  appinventor/blocklyeditor/src/generators/yail/text.js
Labels: affects: master, bug, pull request: needs review

#2469 Add hostname to buildserver/vars
  appinventor/buildserver/src/com/google/appinventor/buildserver/BuildServer.java
Labels: affects: master, pull request: needs review

#2470 Load built-in templates via the repo parameter
  appinventor/appengine/src/com/google/appinventor/client/Ode.java
  appinventor/appengine/src/com/google/appinventor/client/wizards/TemplateUploadWizard.java
Labels: affects: master, feature request, pull request: needs review

#2449 Change propertyDefintions into propertyDefinitions
  appinventor/appengine/src/com/google/appinventor/client/editor/simple/components/utils/PropertiesUtil.java
Labels: affects: master, pull request: needs review, technical debt

#2450 Fix several typos in MockComponent.java
  appinventor/appengine/src/com/google/appinventor/client/editor/simple/components/MockComponent.java
Labels: affects: master, pull request: needs review, technical debt

#2464 Change Accerleromter to Accelerometer
  appinventor/components/src/com/google/appinventor/components/runtime/Camera.java
  appinventor/components/src/com/google/appinventor/components/runtime/Pedometer.java
Labels: affects: master, pull request: needs review
