Repository mit-cml/appinventor-sources, pull requests merged in 2021-06, with the labels that each got.

#2458 New Test Class for TextBox Component
  appinventor/components/tests/com/google/appinventor/components/runtime/TextBoxTest.java
Labels: affects: master, pull request: needs review, technical debt

#2495 Fixed Issue 2494
  appinventor/components/src/com/google/appinventor/components/runtime/TextToSpeech.java
Labels: affects: master, documentation, pull request: needs review

#2475 Shows project name dialog box when uploading a project with an invalid name.
  appinventor/appengine/src/com/google/appinventor/client/OdeMessages.java
  appinventor/appengine/src/com/google/appinventor/client/explorer/commands/CopyYoungAndroidProjectCommand.java
  appinventor/appengine/src/com/google/appinventor/client/explorer/dialogs/NoProjectDialogBox.java
  appinventor/appengine/src/com/google/appinventor/client/utils/HTML5DragDrop.java
  appinventor/appengine/src/com/google/appinventor/client/utils/html5dnd.js
  appinventor/appengine/src/com/google/appinventor/client/wizards/ProjectUploadWizard.java
  appinventor/appengine/src/com/google/appinventor/client/wizards/RequestNewProjectNameWizard.java
  appinventor/appengine/src/com/google/appinventor/client/wizards/RequestProjectNewNameInterface.java
  appinventor/appengine/src/com/google/appinventor/client/wizards/TemplateUploadWizard.java
  appinventor/appengine/src/com/google/appinventor/client/wizards/youngandroid/NewYoungAndroidProjectWizard.java
  appinventor/appengine/src/com/google/appinventor/client/youngandroid/TextValidators.java
Labels: affects: master, feature request, pull request: in review

#1751 [GSoC] ListView layout
  appinventor/appengine/src/com/google/appinventor/client/OdeMessages.java
  appinventor/appengine/src/com/google/appinventor/client/editor/simple/components/MockListView.java
  appinventor/appengine/src/com/google/appinventor/client/editor/simple/components/MockVisibleComponent.java
  appinventor/appengine/src/com/google/appinventor/client/editor/simple/components/utils/PropertiesUtil.java
  appinventor/appengine/src/com/google/appinventor/client/editor/youngandroid/properties/YoungAndroidListViewAddDataPropertyEditor.java
  appinventor/appengine/src/com/google/appinventor/client/editor/youngandroid/properties/YoungAndroidListViewLayoutChoicePropertyEditor.java
  appinventor/appengine/src/com/google/appinventor/client/widgets/properties/ChoicePropertyEditor.java
  appinventor/appengine/src/com/google/appinventor/client/youngandroid/YoungAndroidFormUpgrader.java
  appinventor/blocklyeditor/src/versioning.js
  appinventor/components/src/com/google/appinventor/components/common/ComponentConstants.java
  appinventor/components/src/com/google/appinventor/components/common/PropertyTypeConstants.java
  appinventor/components/src/com/google/appinventor/components/common/YaVersion.java
  appinventor/components/src/com/google/appinventor/components/runtime/Component.java
  appinventor/components/src/com/google/appinventor/components/runtime/ListView.java
  appinventor/components/src/com/google/appinventor/components/runtime/util/ElementsUtil.java
  appinventor/components/src/com/google/appinventor/components/runtime/util/ListViewArrayAdapterImageSingleText.java
  appinventor/components/src/com/google/appinventor/components/runtime/util/ListViewArrayAdapterImageTwoText.java
  appinventor/components/src/com/google/appinventor/components/runtime/util/ListViewArrayAdapterSingleText.java
  appinventor/components/src/com/google/appinventor/components/runtime/util/ListViewArrayAdapterTwoText.java
  appinventor/components/src/com/google/appinventor/components/runtime/util/ListViewArrayAdapterTwoTextLinear.java
  appinventor/docs/html/reference/components/userinterface.html
  appinventor/docs/markdown/reference/components/userinterface.md
Labels: affects: ucr, feature request, pull request: in review

#2503 Fix minor bugs in helper block form upgrader
  appinventor/appengine/src/com/google/appinventor/client/youngandroid/YoungAndroidFormUpgrader.java
Labels: affects: ucr, bug, pull request: needs review
