Repository mit-cml/appinventor-sources, pull requests merged in 2021-10, with the labels that each got.

#2583 Inaccessible Link Issue fix in FirebaseDB Documentation
  appinventor/components/src/com/google/appinventor/components/runtime/FirebaseDB.java
Labels: documentation, pull request: needs review, affects: master

#2566 Fixed Issue 2517
  appinventor/components/src/com/google/appinventor/components/runtime/Canvas.java
Labels: bug, pull request: needs review, affects: ucr

#2589 Trigger AfterTextInput on cancel iff TextInputCancelled is not defined
  appinventor/components/src/com/google/appinventor/components/runtime/Notifier.java
Labels: enhancement, pull request: needs review, affects: ucr
