Repository mit-cml/appinventor-sources, pull requests merged in 2021-03, with the labels that each got.

#2385 Make companion code textbox single line only
  appinventor/aiplayapp/src/edu/mit/appinventor/aicompanion3/Screen1.scm
  appinventor/aiplayapp/src/edu/mit/appinventor/aicompanion3/Screen1.yail
Labels: affects: ucr, bug, pull request: in review, pull request: needs review

#2434 Fix multiple locale showing in login failed page
  appinventor/appengine/src/com/google/appinventor/server/LoginServlet.java
Labels: affects: master, bug, pull request: needs review

#2414 Removed if condition converting list-of-lists into dictionary
  appinventor/components/src/com/google/appinventor/components/runtime/util/YailDictionary.java
  appinventor/components/tests/com/google/appinventor/components/runtime/util/YailDictionaryTest.java
Labels: affects: ucr, bug, pull request: needs reply to review

#2427 Update CloudDB LUA Script
  appinventor/components/src/com/google/appinventor/components/runtime/CloudDB.java
Labels: affects: ucr, pull request: needs review

#2436 Set initial currentView to projects in Ode.java
  appinventor/appengine/src/com/google/appinventor/client/Ode.java
Labels: affects: master, bug, pull request: needs review

#2227 [GSoC] Adding Different Preview Options To The Designer
  appinventor/appengine/src/com/google/appinventor/client/Images.java
  appinventor/appengine/src/com/google/appinventor/client/OdeMessages.java
  appinventor/appengine/src/com/google/appinventor/client/editor/simple/SimpleVisibleComponentsPanel.java
  appinventor/appengine/src/com/google/appinventor/client/editor/simple/components/DesignPreviewChangeListener.java
  appinventor/appengine/src/com/google/appinventor/client/editor/simple/components/MockCheckBox.java
  appinventor/appengine/src/com/google/appinventor/client/editor/simple/components/MockComponent.java
  appinventor/appengine/src/com/google/appinventor/client/editor/simple/components/MockComponentsUtil.java
  appinventor/appengine/src/com/google/appinventor/client/editor/simple/components/MockForm.java
  appinventor/appengine/src/com/google/appinventor/client/editor/simple/components/MockSlider.java
  appinventor/appengine/src/com/google/appinventor/client/editor/simple/components/MockSwitch.java
  appinventor/appengine/src/com/google/appinventor/client/editor/simple/components/MockToggleBase.java
  appinventor/appengine/src/com/google/appinventor/client/editor/simple/components/MockVisibleComponent.java
  appinventor/appengine/src/com/google/appinventor/client/editor/simple/palette/SimpleComponentDescriptor.java
  appinventor/appengine/src/com/google/appinventor/client/settings/project/YoungAndroidSettings.java
  appinventor/appengine/src/com/google/appinventor/images/iOSBookmarkBlack.png
  appinventor/appengine/src/com/google/appinventor/images/iOSBookmarkWhite.png
  appinventor/appengine/src/com/google/appinventor/images/iPadBlackFB.png
  appinventor/appengine/src/com/google/appinventor/images/iPadLeftWhiteFB.png
  appinventor/appengine/src/com/google/appinventor/images/iPadRightBlack.png
  appinventor/appengine/src/com/google/appinventor/images/iPadRightWhite.png
  appinventor/appengine/src/com/google/appinventor/images/iPhoneLeftBlack.png
  appinventor/appengine/src/com/google/appinventor/images/iPhoneLeftWhiteFB.png
  appinventor/appengine/src/com/google/appinventor/images/iPhoneRightBlack.png
  appinventor/appengine/src/com/google/appinventor/images/iPhoneRightWhite.png
  appinventor/appengine/src/com/google/appinventor/images/phonebarAndroidMaterial.png
  appinventor/appengine/src/com/google/appinventor/shared/settings/SettingsConstants.java
  appinventor/appengine/war/index.html
  appinventor/appengine/war/static/css/DarkTheme.css
  appinventor/appengine/war/static/css/Ya.css
  appinventor/appengine/war/static/css/android_holo.css
  appinventor/appengine/war/static/css/android_material.css
  appinventor/appengine/war/static/css/iOS.css
  appinventor/appengine/war/static/fonts/Helvetica.ttf
  appinventor/appengine/war/static/images/iOSLandscapeMonitor.png
  appinventor/appengine/war/static/images/iOSLandscapeTablet.png
  appinventor/appengine/war/static/images/iOSPortraitMonitor.png
  appinventor/appengine/war/static/images/iOSPortraitTablet.png
  appinventor/appengine/war/static/images/iPhoneXLandscape.png
  appinventor/appengine/war/static/images/iPhoneXPotrait.png
Labels: affects: master, enhancement, on ai2-test, pull request: in review, pull request: needs review

#2393 Make tapThreshold a user settable property in component Canvas.java
  appinventor/appengine/src/com/google/appinventor/client/youngandroid/YoungAndroidFormUpgrader.java
  appinventor/blocklyeditor/src/versioning.js
  appinventor/components/src/com/google/appinventor/components/common/YaVersion.java
  appinventor/components/src/com/google/appinventor/components/runtime/Canvas.java
  appinventor/docs/html/reference/components/animation.html
  appinventor/docs/markdown/reference/components/animation.md
Labels: affects: ucr, feature request, pull request: in review

#2439 Changed TestToSpeech to TextToSpeech
  appinventor/components/src/com/google/appinventor/components/runtime/TextToSpeech.java
Labels: affects: master, documentation, pull request: needs review
