Repository mit-cml/appinventor-sources, pull requests merged in 2021-11, with the labels that each got.

#2599 Fix missing Blockly messages from nb187 release
  appinventor/blocklyeditor/src/msg/ai_blockly/messages.json
Labels: pull request: needs review, affects: master, regression

#2600 Fix ListView handling of filters and recyled elements
  appinventor/components/src/com/google/appinventor/components/runtime/ListAdapterWithRecyclerView.java
Labels: pull request: needs review, affects: ucr, regression

#2605 Use Authkey in sources if there is one
  appinventor/appengine/build.xml
Labels: pull request: needs reply to review, technical debt, affects: master
