Repository mit-cml/appinventor-sources, pull requests merged in 2022-10, with the labels that each got.

#2499 Custom Font Typeface Support [GSOC-2021]
  appinventor/appengine/src/com/google/appinventor/client/editor/simple/components/MockButtonBase.java
  appinventor/appengine/src/com/google/appinventor/client/editor/simple/components/MockComponentsUtil.java
  appinventor/appengine/src/com/google/appinventor/client/editor/simple/components/MockLabel.java
  appinventor/appengine/src/com/google/appinventor/client/editor/simple/components/MockPasswordTextBox.java
  appinventor/appengine/src/com/google/appinventor/client/editor/simple/components/MockRadioButton.java
  appinventor/appengine/src/com/google/appinventor/client/editor/simple/components/MockSwitch.java
  appinventor/appengine/src/com/google/appinventor/client/editor/simple/components/MockTextBoxBase.java
  appinventor/appengine/src/com/google/appinventor/client/editor/simple/components/MockToggleBase.java
  appinventor/appengine/src/com/google/appinventor/client/editor/simple/components/utils/PropertiesUtil.java
  appinventor/appengine/src/com/google/appinventor/client/editor/youngandroid/properties/YoungAndroidFontTypefaceChoicePropertyEditor.java
  appinventor/appengine/src/com/google/appinventor/client/explorer/commands/PreviewFileCommand.java
  appinventor/appengine/src/com/google/appinventor/shared/storage/StorageUtil.java
  appinventor/components/src/com/google/appinventor/components/runtime/ButtonBase.java
  appinventor/components/src/com/google/appinventor/components/runtime/Component.java
  appinventor/components/src/com/google/appinventor/components/runtime/Label.java
  appinventor/components/src/com/google/appinventor/components/runtime/ListAdapterWithRecyclerView.java
  appinventor/components/src/com/google/appinventor/components/runtime/ListView.java
  appinventor/components/src/com/google/appinventor/components/runtime/TextBoxBase.java
  appinventor/components/src/com/google/appinventor/components/runtime/ToggleBase.java
  appinventor/components/src/com/google/appinventor/components/runtime/util/TextViewUtil.java
  appinventor/docs/markdown/reference/components/media.md
  appinventor/docs/markdown/reference/components/social.md
  appinventor/docs/markdown/reference/components/userinterface.md
Labels: feature request, affects: ucr

#2768 Raise FinishedClearRange event after clearing range
  appinventor/components/src/com/google/appinventor/components/runtime/Spreadsheet.java
Labels: bug, pull request: needs review, affects: ucr

#2753 Create Markdown for PHOLO documentation
  appinventor/docs/html/reference/blocks/lists.html
  appinventor/docs/html/reference/concepts/pholo.html
  appinventor/docs/markdown/reference/blocks/images/lists/butfirst.png
  appinventor/docs/markdown/reference/blocks/images/lists/butlast.png
  appinventor/docs/markdown/reference/blocks/images/lists/filternondest.png
  appinventor/docs/markdown/reference/blocks/images/lists/mapnondest.png
  appinventor/docs/markdown/reference/blocks/images/lists/maxnumber.png
  appinventor/docs/markdown/reference/blocks/images/lists/minnumber.png
  appinventor/docs/markdown/reference/blocks/images/lists/reduce.png
  appinventor/docs/markdown/reference/blocks/images/lists/slices.png
  appinventor/docs/markdown/reference/blocks/images/lists/sort.png
  appinventor/docs/markdown/reference/blocks/images/lists/sortwithcomparator.png
  appinventor/docs/markdown/reference/blocks/images/lists/sortwithkey.png
  appinventor/docs/markdown/reference/blocks/lists.md
  appinventor/docs/markdown/reference/concepts/images/bobData.png
  appinventor/docs/markdown/reference/concepts/images/bobDataList.png
  appinventor/docs/markdown/reference/concepts/images/filterBlock.png
  appinventor/docs/markdown/reference/concepts/images/filterResult.png
  appinventor/docs/markdown/reference/concepts/images/heightTable.png
  appinventor/docs/markdown/reference/concepts/images/lemonadeStandTable.png
  appinventor/docs/markdown/reference/concepts/images/mapBlock.png
  appinventor/docs/markdown/reference/concepts/images/mapResult.png
  appinventor/docs/markdown/reference/concepts/images/originalList.png
  appinventor/docs/markdown/reference/concepts/images/pholoblocks.png
  appinventor/docs/markdown/reference/concepts/images/reduceBlock.png
  appinventor/docs/markdown/reference/concepts/images/reduceResult.png
  appinventor/docs/markdown/reference/concepts/images/sortGenderHeightBlock.png
  appinventor/docs/markdown/reference/concepts/images/sortGenderHeightResult.png
  appinventor/docs/markdown/reference/concepts/images/sortHeightBlock.png
  appinventor/docs/markdown/reference/concepts/images/sortHeightResult.png
  appinventor/docs/markdown/reference/concepts/images/sortLastNameBlock.png
  appinventor/docs/markdown/reference/concepts/images/sortLastNameResult.png
  appinventor/docs/markdown/reference/concepts/pholo.md
Labels: documentation, pull request: needs review, affects: ucr

#2746 Work around scatter rendering crash in MPAndroidChart
  appinventor/components/src/com/google/appinventor/components/runtime/ScatterChartDataModel.java
Labels: bug, pull request: needs review, affects: ucr

#2715 Update Chrome-deprecated functions in drag and drop code
  appinventor/appengine/src/com/google/appinventor/client/utils/html5dnd.js
Labels: pull request: needs review, technical debt, affects: master
