Repository mit-cml/appinventor-sources, pull requests merged in 2022-09, with the labels that each got.

#2724 Only require acceptable version check for non-Apple devices
  appinventor/blocklyeditor/src/replmgr.js
Labels: pull request: needs review, affects: master, regression

#2722 Fix crash when File.MoveFile target exists
  appinventor/components/src/com/google/appinventor/components/runtime/File.java
  appinventor/components/src/com/google/appinventor/components/runtime/util/FileUtil.java
  appinventor/components/tests/com/google/appinventor/components/runtime/util/FileUtilTest.java
Labels: bug, pull request: needs review, affects: ucr

#2729 Extract spreadsheet ID from URL if provided
  appinventor/components/src/com/google/appinventor/components/runtime/Spreadsheet.java
Labels: enhancement, pull request: needs review, affects: ucr

#2733 Use AssetFetcher to update the Companion
  appinventor/appengine/src/com/google/appinventor/client/editor/youngandroid/BlocklyPanel.java
  appinventor/components/src/com/google/appinventor/components/common/YaVersion.java
  appinventor/components/src/com/google/appinventor/components/runtime/util/AssetFetcher.java
Labels: pull request: needs review, affects: ucr

#2699 Creating Functional Operators in the Blocks Editor (GSoC 2022)
  appinventor/blocklyeditor/src/blocks/lists.js
  appinventor/blocklyeditor/src/blocks/procedures.js
  appinventor/blocklyeditor/src/field_lexical_variable.js
  appinventor/blocklyeditor/src/generators/yail.js
  appinventor/blocklyeditor/src/generators/yail/lists.js
  appinventor/blocklyeditor/src/generators/yail/procedures.js
  appinventor/blocklyeditor/src/msg/ai_blockly/messages.json
  appinventor/buildserver/src/com/google/appinventor/buildserver/resources/runtime.scm
  appinventor/components/src/com/google/appinventor/components/runtime/AppInventorCompatActivity.java
  appinventor/docs/html/reference/blocks/images/lists/butfirst.png
  appinventor/docs/html/reference/blocks/images/lists/butlast.png
  appinventor/docs/html/reference/blocks/images/lists/filternondest.png
  appinventor/docs/html/reference/blocks/images/lists/mapnondest.png
  appinventor/docs/html/reference/blocks/images/lists/maxnumber.png
  appinventor/docs/html/reference/blocks/images/lists/minnumber.png
  appinventor/docs/html/reference/blocks/images/lists/reduce.png
  appinventor/docs/html/reference/blocks/images/lists/slices.png
  appinventor/docs/html/reference/blocks/images/lists/sort.png
  appinventor/docs/html/reference/blocks/images/lists/sortwithcomparator.png
  appinventor/docs/html/reference/blocks/images/lists/sortwithkey.png
  appinventor/docs/html/reference/blocks/lists.html
  appinventor/docs/html/reference/concepts/images/bobData.png
  appinventor/docs/html/reference/concepts/images/bobDataList.png
  appinventor/docs/html/reference/concepts/images/filterBlock.png
  appinventor/docs/html/reference/concepts/images/filterResult.png
  appinventor/docs/html/reference/concepts/images/heightTable.png
  appinventor/docs/html/reference/concepts/images/lemonadeStandTable.png
  appinventor/docs/html/reference/concepts/images/mapBlock.png
  appinventor/docs/html/reference/concepts/images/mapResult.png
  appinventor/docs/html/reference/concepts/images/originalList.png
  appinventor/docs/html/reference/concepts/images/pholoblocks.png
  appinventor/docs/html/reference/concepts/images/reduceBlock.png
  appinventor/docs/html/reference/concepts/images/reduceResult.png
  appinventor/docs/html/reference/concepts/images/sortGenderHeightBlock.png
  appinventor/docs/html/reference/concepts/images/sortGenderHeightResult.png
  appinventor/docs/html/reference/concepts/images/sortHeightBlock.png
  appinventor/docs/html/reference/concepts/images/sortHeightResult.png
  appinventor/docs/html/reference/concepts/images/sortLastNameBlock.png
  appinventor/docs/html/reference/concepts/images/sortLastNameResult.png
  appinventor/docs/html/reference/concepts/pholo.html
Labels: pull request: needs review, feature request, affects: ucr

#2748 Use globs for proguard library paths
  appinventor/components/build.xml
Labels: pull request: needs review, affects: master, regression

#2743 Implement BluetoothClient version 7 upgrade
  appinventor/appengine/src/com/google/appinventor/client/youngandroid/YoungAndroidFormUpgrader.java
Labels: bug, pull request: needs review, affects: master
