Repository mit-cml/appinventor-sources, pull requests merged in 2022-05, with the labels that each got.

#2629 Fix problems that have not been translated into tooltips.
  appinventor/blocklyeditor/src/component_database.js
Labels: pull request: needs review, affects: master, regression

#2626 Make use of targetWorkspace where applicable
  appinventor/blocklyeditor/src/blocks/helpers.js
  appinventor/blocklyeditor/src/workspace_svg.js
Labels: bug, pull request: needs review, affects: master

#2678 Correct translation keys in Blockly tests
  appinventor/blocklyeditor/tests/com/google/appinventor/blocklyeditor/component_database_tests.js
Labels: pull request: needs review, affects: master, regression

#2664 Cache Assets in the Companion
  appinventor/appengine/src/com/google/appinventor/server/DownloadServlet.java
  appinventor/components/src/com/google/appinventor/components/runtime/util/AssetFetcher.java
  appinventor/components/src/com/google/appinventor/components/runtime/util/HashDatabase.java
  appinventor/components/src/com/google/appinventor/components/runtime/util/HashDbInitialize.java
  appinventor/components/src/com/google/appinventor/components/runtime/util/HashFile.java
  appinventor/components/src/com/google/appinventor/components/runtime/util/QUtil.java
Labels: enhancement, pull request: in review, affects: ucr
