Repository mit-cml/appinventor-sources, pull requests merged in 2022-06, with the labels that each got.

#2688 Make helper block typeblock functions behave statically
  appinventor/blocklyeditor/src/blocks/helpers.js
Labels: pull request: needs review, affects: master, regression

#2611 Have Legacy Mode use a Popup Window
  appinventor/aiplayapp/src/edu/mit/appinventor/aicompanion3/Screen1.bky
  appinventor/aiplayapp/src/edu/mit/appinventor/aicompanion3/Screen1.scm
  appinventor/aiplayapp/src/edu/mit/appinventor/aicompanion3/Screen1.yail
  appinventor/appengine/src/com/google/appinventor/client/Ode.java
  appinventor/blocklyeditor/src/msg/ai_blockly/messages.json
  appinventor/blocklyeditor/src/replmgr.js
  appinventor/components/src/com/google/appinventor/components/runtime/PhoneStatus.java
  appinventor/components/src/com/google/appinventor/components/runtime/util/AppInvHTTPD.java
Labels: pull request: needs reply to review, affects: ucr

#2689 Do not use AssetFetcher on iOS
  appinventor/appengine/src/com/google/appinventor/client/AssetManager.java
  appinventor/blocklyeditor/src/replmgr.js
Labels: pull request: needs review, affects: ucr

#2690 Add Introduction Message on the home screen of Companion
  appinventor/aiplayapp/src/edu/mit/appinventor/aicompanion3/Screen1.scm
  appinventor/aiplayapp/src/edu/mit/appinventor/aicompanion3/Screen1.yail
Labels: pull request: ready to push to Gerrit, affects: ucr

#2698 Fix "Doit" in Legacy Mode
  appinventor/blocklyeditor/src/replmgr.js
Labels: pull request: needs review, affects: master, regression

#2692 Only remove procedure decls when the block is in the main workspace
  appinventor/blocklyeditor/src/blocks/procedures.js
Labels: bug, pull request: needs review, affects: master

#2694 Remove redundant translation entries from ComponentTranslations.java
  appinventor/components/src/com/google/appinventor/components/scripts/ComponentTranslationGenerator.java
Labels: enhancement, pull request: needs review, affects: master

#2693 Always output parameters of blocks even on name collisions
  appinventor/components/src/com/google/appinventor/components/scripts/ComponentTranslationGenerator.java
Labels: pull request: needs review, technical debt, affects: master

#2702 Add a flag "auth.deleteaccountallowed"
  appinventor/appengine/src/com/google/appinventor/client/Ode.java
  appinventor/appengine/src/com/google/appinventor/client/TopPanel.java
  appinventor/appengine/src/com/google/appinventor/server/UserInfoServiceImpl.java
  appinventor/appengine/src/com/google/appinventor/shared/rpc/user/Config.java
Labels: pull request: needs review, affects: master
