Repository mit-cml/appinventor-sources, pull requests merged in 2023-09, with the labels that each got.

#2980 Fix order of created/modified date labels
  appinventor/appengine/src/com/google/appinventor/client/explorer/youngandroid/ProjectListItem.ui.xml
Labels: pull request: needs review, affects: master, regression

#2988 Allow loading media from private directory without file: scheme
  appinventor/components/src/com/google/appinventor/components/runtime/util/MediaUtil.java
Labels: bug, pull request: needs review, affects: ucr, android

#2985 Restore scrolling on project explorer view
  appinventor/appengine/war/static/css/Ya.css
Labels: pull request: needs review, affects: master, regression

#3004 Keep extension classes in extension package when proguarding
  appinventor/lib/proguard/proguard.cfg
Labels: bug, pull request: needs review, AI Extensions, affects: master
