Repository mit-cml/appinventor-sources, pull requests merged in 2023-10, with the labels that each got.

#2984 Fix Error Handling in ChatBot and ImageBot
  appinventor/components/src/com/google/appinventor/components/runtime/ChatBot.java
  appinventor/components/src/com/google/appinventor/components/runtime/ImageBot.java
Labels: pull request: needs review, affects: ucr

#2911 ListData and Font details features (GSoC 2023)
  appinventor/components-ios/src/ListView.swift
Labels: enhancement, pull request: needs review, affects: ucr, ios

#2995 Fix procedure names not set in backpack
  appinventor/blocklyeditor/src/field_procedurename.js
Labels: pull request: needs review, affects: master, regression

#2864 Provide error message regarding extensions for the gallery
  appinventor/appengine/src/com/google/appinventor/client/OdeMessages.java
  appinventor/appengine/src/com/google/appinventor/client/actions/SendToGalleryAction.java
  appinventor/appengine/src/com/google/appinventor/client/editor/youngandroid/YaProjectEditor.java
  appinventor/appengine/src/com/google/appinventor/client/editor/youngandroid/actions/SendToGalleryAction.java
  appinventor/appengine/src/com/google/appinventor/shared/rpc/project/ProjectNode.java
  appinventor/appengine/src/com/google/appinventor/shared/rpc/project/youngandroid/YoungAndroidProjectNode.java
Labels: enhancement, pull request: needs reply to review, affects: master

#2974 Fix alist to dict bug with FString keys
  appinventor/components/src/com/google/appinventor/components/runtime/util/YailDictionary.java
Labels: affects: ucr

#3000 Switch to gviz export API for Spreadsheet
  appinventor/components/src/com/google/appinventor/components/runtime/Spreadsheet.java
Labels: bug, pull request: needs review, affects: ucr, android

#2997 Fix USB connections not loading extensions
  appinventor/blocklyeditor/src/replmgr.js
Labels: pull request: needs review, affects: master, regression

#3010 Make java_dev_appserver.sh command single-line in README.md
  README.md
Labels: documentation, pull request: needs reply to review, affects: master

#2992 Fix misaligned buildserver stat reports
  appinventor/buildserver/src/com/google/appinventor/buildserver/stats/SimpleStatReporter.java
Labels: bug, pull request: needs review, affects: master

#3005 Load and compare project properties in tests
  appinventor/appengine/tests/com/google/appinventor/server/ProjectServiceTest.java
Labels: pull request: needs review, technical debt, affects: master

#2972 Only send Strict Transport Security Header using https
  appinventor/appengine/war/index.jsp
Labels: pull request: needs review, affects: master

#2991 Restore substitution for spaces in project name
  appinventor/appengine/src/com/google/appinventor/client/wizards/youngandroid/NewYoungAndroidProjectWizard.java
Labels: pull request: needs reply to review, affects: master, regression

#2819 ResponseTextEncoding property for Web component
  appinventor/appengine/src/com/google/appinventor/client/OdeMessages_zh_CN.properties
  appinventor/appengine/src/com/google/appinventor/client/youngandroid/YoungAndroidFormUpgrader.java
  appinventor/blocklyeditor/src/versioning.js
  appinventor/components/src/com/google/appinventor/components/common/YaVersion.java
  appinventor/components/src/com/google/appinventor/components/runtime/Web.java
  appinventor/docs/html/reference/components/connectivity.html
  appinventor/docs/markdown/reference/components/connectivity.md
Labels: enhancement, pull request: needs review, affects: ucr

#3021 Fix regression in use of ListView.Elements on iOS
  appinventor/components-ios/src/ListView.swift
Labels: pull request: needs review, affects: ucr, regression, ios, testflight

#2993 Inline BluetoothReflection functionality
  appinventor/components/src/com/google/appinventor/components/runtime/BluetoothClient.java
  appinventor/components/src/com/google/appinventor/components/runtime/BluetoothConnectionBase.java
  appinventor/components/src/com/google/appinventor/components/runtime/BluetoothServer.java
  appinventor/components/src/com/google/appinventor/components/runtime/util/BluetoothReflection.java
  appinventor/components/src/com/google/appinventor/components/runtime/util/SUtil.java
  appinventor/components/tests/com/google/appinventor/components/runtime/BluetoothConnectionBaseTest.java
  appinventor/docs/html/reference/components/connectivity.html
  appinventor/docs/markdown/reference/components/connectivity.md
Labels: pull request: needs review, technical debt, affects: ucr, android

#3028 Add missing coerce-to-number-list code path in iOS
  appinventor/components-ios/src/runtime.scm
Labels: bug, pull request: needs review, affects: ucr, ios, testflight

#2789 Add "RemoveItemAtIndex" block to ListView
  appinventor/appengine/src/com/google/appinventor/client/youngandroid/YoungAndroidFormUpgrader.java
  appinventor/blocklyeditor/src/versioning.js
  appinventor/components-ios/src/ErrorMessages.swift
  appinventor/components-ios/src/ListView.swift
  appinventor/components/src/com/google/appinventor/components/common/YaVersion.java
  appinventor/components/src/com/google/appinventor/components/runtime/ListAdapterWithRecyclerView.java
  appinventor/components/src/com/google/appinventor/components/runtime/ListView.java
  appinventor/components/src/com/google/appinventor/components/runtime/util/ElementsUtil.java
  appinventor/components/src/com/google/appinventor/components/runtime/util/ErrorMessages.java
  appinventor/docs/html/reference/components/userinterface.html
  appinventor/docs/markdown/reference/components/userinterface.md
Labels: enhancement, pull request: needs reply to review, affects: ucr

#2946 Project Properties Dialog - GSoC'23
  appinventor/appengine/build.xml
  appinventor/appengine/src/com/google/appinventor/client/OdeMessages.java
  appinventor/appengine/src/com/google/appinventor/client/TopToolbar.java
  appinventor/appengine/src/com/google/appinventor/client/TopToolbar.ui.xml
  appinventor/appengine/src/com/google/appinventor/client/editor/simple/components/MockForm.java
  appinventor/appengine/src/com/google/appinventor/client/editor/youngandroid/DesignToolbar.java
  appinventor/appengine/src/com/google/appinventor/client/editor/youngandroid/DesignToolbar.ui.xml
  appinventor/appengine/src/com/google/appinventor/client/editor/youngandroid/YaFormEditor.java
  appinventor/appengine/src/com/google/appinventor/client/editor/youngandroid/YaProjectEditor.java
  appinventor/appengine/src/com/google/appinventor/client/editor/youngandroid/actions/ProjectPropertiesAction.java
  appinventor/appengine/src/com/google/appinventor/client/explorer/dialogs/ProjectPropertiesDialogBox.java
  appinventor/appengine/src/com/google/appinventor/client/explorer/dialogs/ProjectPropertiesDialogBox.ui.xml
  appinventor/appengine/war/static/css/Ya.css
  appinventor/components/src/com/google/appinventor/components/annotations/PropertyCategory.java
  appinventor/components/src/com/google/appinventor/components/runtime/Form.java
Labels: pull request: needs review, technical debt, affects: master

#3024 Fix lack of lifecycle management in TextToSpeech on iOS
  appinventor/aicompanionapp/src/ViewController.swift
  appinventor/components-ios/src/Form.swift
  appinventor/components-ios/src/NonvisibleComponent.swift
  appinventor/components-ios/src/TextToSpeech.swift
Labels: bug, pull request: needs review, affects: ucr, ios, testflight

#3036 Use darker gray for iOS PasswordTextbox hint color
  appinventor/components-ios/src/PasswordTextBox.swift
Labels: bug, pull request: needs review, affects: ucr, ios

#3029 Add more missing methods to iOS ListView
  appinventor/components-ios/src/ListView.swift
  appinventor/components-ios/tests/Unit Tests/components/visible/ListViewTests.swift
Labels: pull request: needs review, technical debt, affects: ucr, ios

#3031 Add Send To Gallery button to designer toolbar template
  appinventor/appengine/src/com/google/appinventor/client/actions/SendToGalleryAction.java
  appinventor/appengine/src/com/google/appinventor/client/editor/youngandroid/DesignToolbar.java
  appinventor/appengine/src/com/google/appinventor/client/editor/youngandroid/DesignToolbar.ui.xml
  appinventor/appengine/src/com/google/appinventor/client/editor/youngandroid/actions/SendToGalleryAction.java
  appinventor/appengine/src/com/google/appinventor/server/GalleryExtensionException.java
  appinventor/appengine/src/com/google/appinventor/server/project/youngandroid/YoungAndroidProjectService.java
  appinventor/appengine/src/com/google/appinventor/server/storage/ObjectifyStorageIo.java
  appinventor/appengine/src/com/google/appinventor/shared/rpc/RpcResult.java
Labels: pull request: needs reply to review, affects: master, regression

#3040 Make TTS stop when switching screens in companion
  appinventor/components/src/com/google/appinventor/components/runtime/TextToSpeech.java
Labels: bug, pull request: needs review, affects: ucr, android

#3039 Fix scrollbar and HTML visibility in Project Properties Dialog
  appinventor/appengine/src/com/google/appinventor/client/TopToolbar.java
  appinventor/appengine/src/com/google/appinventor/client/TopToolbar.ui.xml
  appinventor/appengine/src/com/google/appinventor/client/explorer/dialogs/ProjectPropertiesDialogBox.java
  appinventor/appengine/war/static/css/Ya.css
Labels: bug, pull request: needs review, affects: master
