Repository mit-cml/appinventor-sources, pull requests merged in 2023-02, with the labels that each got.

#2508 Fix image resizing on scalar changes
  appinventor/appengine/src/com/google/appinventor/client/editor/simple/components/MockImageBase.java
Labels: bug, pull request: needs review, affects: master

#2786 Implement new stats blocks
  appinventor/blocklyeditor/src/blocks/lists.js
  appinventor/blocklyeditor/src/blocks/math.js
  appinventor/blocklyeditor/src/field_lexical_variable.js
  appinventor/blocklyeditor/src/generators/yail/lists.js
  appinventor/blocklyeditor/src/generators/yail/math.js
  appinventor/blocklyeditor/src/msg/ai_blockly/messages.json
  appinventor/blocklyeditor/src/versioning.js
  appinventor/buildserver/src/com/google/appinventor/buildserver/resources/runtime.scm
  appinventor/components/src/com/google/appinventor/components/common/YaVersion.java
  appinventor/docs/html/reference/blocks/images/lists/maxnumber.png
  appinventor/docs/html/reference/blocks/images/lists/minnumber.png
  appinventor/docs/html/reference/blocks/images/math/avg.png
  appinventor/docs/html/reference/blocks/images/math/gm.png
  appinventor/docs/html/reference/blocks/images/math/maxl.png
  appinventor/docs/html/reference/blocks/images/math/minl.png
  appinventor/docs/html/reference/blocks/images/math/mode.png
  appinventor/docs/html/reference/blocks/images/math/sd.png
  appinventor/docs/html/reference/blocks/images/math/se.png
  appinventor/docs/html/reference/blocks/math.html
  appinventor/docs/markdown/reference/blocks/images/lists/maxnumber.png
  appinventor/docs/markdown/reference/blocks/images/lists/minnumber.png
  appinventor/docs/markdown/reference/blocks/images/math/avg.png
  appinventor/docs/markdown/reference/blocks/images/math/gm.png
  appinventor/docs/markdown/reference/blocks/images/math/maxl.png
  appinventor/docs/markdown/reference/blocks/images/math/minl.png
  appinventor/docs/markdown/reference/blocks/images/math/mode.png
  appinventor/docs/markdown/reference/blocks/images/math/sd.png
  appinventor/docs/markdown/reference/blocks/images/math/se.png
  appinventor/docs/markdown/reference/blocks/math.md
Labels: enhancement, pull request: needs review, affects: ucr

#2452 Add "every component" block
  appinventor/blocklyeditor/src/blocks/components.js
  appinventor/blocklyeditor/src/component_database.js
  appinventor/blocklyeditor/src/drawer.js
  appinventor/blocklyeditor/src/generators/yail.js
  appinventor/blocklyeditor/src/generators/yail/componentblock.js
  appinventor/blocklyeditor/src/msg/ai_blockly/messages.json
  appinventor/blocklyeditor/src/versioning.js
  appinventor/blocklyeditor/src/warningHandler.js
  appinventor/buildserver/src/com/google/appinventor/buildserver/resources/runtime.scm
  appinventor/components/src/com/google/appinventor/components/common/YaVersion.java
  appinventor/components/src/com/google/appinventor/components/runtime/util/ComponentUtil.java
Labels: pull request: needs review, feature request, affects: ucr

#2487 Make split string consistent over Android
  appinventor/buildserver/src/com/google/appinventor/buildserver/resources/runtime.scm
  appinventor/components/src/com/google/appinventor/components/runtime/util/JavaStringUtils.java
  appinventor/components/tests/com/google/appinventor/components/runtime/util/JavaStringUtilsTest.java
Labels: enhancement, pull request: in review, affects: ucr

#2799 Fix Regex Invoke
  appinventor/buildserver/src/com/google/appinventor/buildserver/resources/runtime.scm
Labels: pull request: needs review, affects: ucr

#2818 0-indexed row numbers returned in Spreadsheets component resolved
  appinventor/components/src/com/google/appinventor/components/runtime/Spreadsheet.java
Labels: bug, pull request: needs review, affects: ucr

#2780 Update spreadsheet data structures before GotSheet event
  appinventor/components/src/com/google/appinventor/components/runtime/Spreadsheet.java
Labels: bug, pull request: needs review, affects: ucr

#2742 Assert immutability for PendingIntents in Texting component
  appinventor/components/src/com/google/appinventor/components/runtime/Texting.java
  appinventor/components/src/com/google/appinventor/components/runtime/util/SmsBroadcastReceiver.java
Labels: pull request: needs review, affects: ucr, regression

#2745 Adjust Web file access permission checks
  appinventor/components/src/com/google/appinventor/components/runtime/Web.java
Labels: pull request: needs review, affects: ucr, regression

#2747 Fix File.Exists using Asset scope in APK
  appinventor/components/src/com/google/appinventor/components/runtime/File.java
Labels: bug, pull request: needs review, affects: ucr

#2823 Return empty YailList when list has only one element
  appinventor/buildserver/src/com/google/appinventor/buildserver/resources/runtime.scm
Labels: bug, pull request: needs review, affects: ucr

#2749 Reimplement ComponentDescriptorGenerator with JSONObject
  appinventor/components/src/com/google/appinventor/components/scripts/ComponentDescriptorGenerator.java
  appinventor/components/src/com/google/appinventor/components/scripts/ComponentListGenerator.java
  appinventor/components/src/com/google/appinventor/components/scripts/ComponentProcessor.java
Labels: pull request: needs review, technical debt, affects: master

#2752 Fix issues with null geometries in FeatureCollections
  appinventor/components/src/com/google/appinventor/components/runtime/MapFeatureContainerBase.java
  appinventor/components/src/com/google/appinventor/components/runtime/util/GeoJSONUtil.java
  appinventor/components/tests/com/google/appinventor/components/runtime/util/GeoJSONUtilTest.java
  appinventor/docs/html/reference/components/maps.html
  appinventor/docs/markdown/reference/components/maps.md
Labels: bug, pull request: needs review, affects: ucr

#2821 Implement updates to Tracking module for GA4
  appinventor/appengine/src/com/google/appinventor/client/Ode.java
  appinventor/appengine/src/com/google/appinventor/client/TopToolbar.java
  appinventor/appengine/src/com/google/appinventor/client/editor/youngandroid/YaBlocksEditor.java
  appinventor/appengine/src/com/google/appinventor/client/editor/youngandroid/YaFormEditor.java
  appinventor/appengine/src/com/google/appinventor/client/tracking/Tracking.java
Labels: pull request: needs review, technical debt, affects: master

#2250 Fix some hard-coded HTTP URLs
  appinventor/appengine/src/com/google/appinventor/client/TopToolbar.java
  appinventor/appengine/src/com/google/appinventor/client/explorer/dialogs/NoProjectDialogBox.java
  appinventor/appengine/src/com/google/appinventor/client/wizards/TemplateUploadWizard.java
Labels: bug, pull request: needs review, affects: master

#2755 Have Bluetooth components ask for permissions on Android 12+
  appinventor/appengine/src/com/google/appinventor/client/youngandroid/YoungAndroidFormUpgrader.java
  appinventor/blocklyeditor/src/versioning.js
  appinventor/buildserver/src/com/google/appinventor/buildserver/Compiler.java
  appinventor/buildserver/src/com/google/appinventor/buildserver/util/PermissionConstraint.java
  appinventor/components/build.xml
  appinventor/components/src/com/google/appinventor/components/annotations/PermissionConstraint.java
  appinventor/components/src/com/google/appinventor/components/annotations/UsesPermissions.java
  appinventor/components/src/com/google/appinventor/components/common/ComponentDescriptorConstants.java
  appinventor/components/src/com/google/appinventor/components/common/YaVersion.java
  appinventor/components/src/com/google/appinventor/components/runtime/BluetoothClient.java
  appinventor/components/src/com/google/appinventor/components/runtime/BluetoothServer.java
  appinventor/components/src/com/google/appinventor/components/runtime/util/SUtil.java
  appinventor/components/src/com/google/appinventor/components/scripts/ComponentListGenerator.java
  appinventor/components/src/com/google/appinventor/components/scripts/ComponentProcessor.java
  appinventor/docs/html/reference/components/connectivity.html
  appinventor/docs/markdown/reference/components/connectivity.md
Labels: pull request: needs review, technical debt, affects: ucr

#2592 Remove Blobstore Conversion
  appinventor/appengine/src/com/google/appinventor/server/BlobUpgradeServlet.java
  appinventor/appengine/src/com/google/appinventor/server/UserInfoServiceImpl.java
  appinventor/appengine/src/com/google/appinventor/server/storage/ObjectifyStorageIo.java
  appinventor/appengine/src/com/google/appinventor/server/storage/StorageIo.java
  appinventor/appengine/war/WEB-INF/appengine-web.xml
  appinventor/appengine/war/WEB-INF/queue.xml
  appinventor/appengine/war/WEB-INF/web.xml
Labels: pull request: needs review, affects: master

#2676 Fix: do not read in whole file in UploadServlet
  appinventor/appengine/src/com/google/appinventor/server/FileImporterImpl.java
Labels: bug, pull request: needs review, affects: master

#2839 Provide the popup window HTML source
  appinventor/components/src/com/google/appinventor/components/runtime/util/AppInvHTTPD.java
  appinventor/misc/popup/README.md
  appinventor/misc/popup/popup.html
Labels: pull request: needs review, affects: master

#2840 Update supported browsers list in index
  appinventor/appengine/war/index.html
Labels: pull request: needs review, technical debt, affects: master
