Repository mit-cml/appinventor-sources, pull requests merged in 2023-01, with the labels that each got.

#2778 Helper block support for Player component
  appinventor/components/src/com/google/appinventor/components/runtime/Player.java
Labels: bug, pull request: needs review, affects: master

#2796 Coerce UseProxy flag to boolean
  appinventor/blocklyeditor/src/replmgr.js
Labels: bug, pull request: needs review, affects: master

#2769 Resize Blockly workspace on toggling tutorial pane
  appinventor/appengine/src/com/google/appinventor/client/Ode.java
  appinventor/appengine/src/com/google/appinventor/client/editor/FileEditor.java
  appinventor/appengine/src/com/google/appinventor/client/editor/youngandroid/BlocklyPanel.java
  appinventor/appengine/src/com/google/appinventor/client/editor/youngandroid/YaBlocksEditor.java
Labels: bug, pull request: needs review, affects: master

#2757 Handle large positive Colors in ChartDataBase
  appinventor/components/src/com/google/appinventor/components/runtime/ChartDataBase.java
  appinventor/components/tests/com/google/appinventor/components/runtime/ChartData2DTest.java
Labels: bug, pull request: needs review, affects: ucr

#2761 Update to latest Physicaloid with Android S support
  appinventor/lib/physicaloid/physicaloid-library.jar
Labels: pull request: needs review, affects: ucr, regression

#2679 Update traditional chinese translation for HK
  appinventor/blocklyeditor/src/msg/ai_blockly/messages_zh_TW.json
Labels: pull request: needs reply to review, affects: master

#2750 Add new Bluetooth permissions to Permission enum
  appinventor/components/src/com/google/appinventor/components/common/Permission.java
Labels: enhancement, pull request: needs review, affects: ucr

#2806 Support AssetFetcher use on iOS with WebRTC
  appinventor/blocklyeditor/src/replmgr.js
Labels: enhancement, pull request: needs review, affects: master
