Repository mit-cml/appinventor-sources, pull requests merged in 2023-04, with the labels that each got.

#2872 Update minimum target SDK version for dependencies
  appinventor/Pods/Pods.xcodeproj/project.pbxproj
Labels: pull request: needs review, technical debt, affects: ucr, ios

#2865 Fix screen orientation artifacts in compiled apps
  appinventor/buildserver/src/com/google/appinventor/buildserver/Compiler.java
  appinventor/buildserver/src/com/google/appinventor/buildserver/FormPropertiesAnalyzer.java
  appinventor/buildserver/src/com/google/appinventor/buildserver/Project.java
  appinventor/buildserver/src/com/google/appinventor/buildserver/ProjectBuilder.java
  appinventor/buildserver/tests/com/google/appinventor/buildserver/CompilerTest.java
Labels: bug, pull request: needs review, affects: master, android

#2871 IOS Dialog - Extensions
  appinventor/blocklyeditor/src/msg/ai_blockly/messages.json
  appinventor/blocklyeditor/src/replmgr.js
Labels: enhancement, pull request: needs reply to review, affects: master

#2874 Report the contents of /etc/hostname in buildserver "vars"
  appinventor/buildserver/src/com/google/appinventor/buildserver/BuildServer.java
Labels: enhancement, pull request: needs reply to review, affects: master

#2862 Visual accessibility
  appinventor/AIComponentKit.xcodeproj/project.pbxproj
  appinventor/components-ios/src/AccessibleComponent.swift
  appinventor/components-ios/src/ButtonBase.swift
  appinventor/components-ios/src/Checkbox.swift
  appinventor/components-ios/src/Component.swift
  appinventor/components-ios/src/EmailPicker.swift
  appinventor/components-ios/src/Form.swift
  appinventor/components-ios/src/Image.swift
  appinventor/components-ios/src/Label.swift
  appinventor/components-ios/src/PasswordTextBox.swift
  appinventor/components-ios/src/Switch.swift
  appinventor/components-ios/src/TextBox.swift
  appinventor/components-ios/src/TextBoxBase.swift
Labels: enhancement, pull request: needs review, affects: ucr, ios, testflight

#2877 Use platform-specific file separator in ProjectBuilder.java
  appinventor/buildserver/src/com/google/appinventor/buildserver/ProjectBuilder.java
Labels: pull request: needs review, affects: master, regression

#2878 Handle unknown component_method shape via mutation
  appinventor/blocklyeditor/src/backpack.js
  appinventor/blocklyeditor/src/blocks/components.js
  appinventor/blocklyeditor/src/versioning.js
Labels: pull request: needs review, technical debt, affects: master

#2867 Upadted the Documentation for the Flung part of Canvas and ImageSprite
  appinventor/components/src/com/google/appinventor/components/runtime/Canvas.java
  appinventor/components/src/com/google/appinventor/components/runtime/Sprite.java
  appinventor/docs/html/reference/components/animation.html
  appinventor/docs/markdown/reference/components/animation.md
Labels: documentation, pull request: needs reply to review, affects: master

#2882 Immediately active new screen when opening
  appinventor/components-ios/src/Application.swift
  appinventor/components-ios/src/Form.swift
  appinventor/components-ios/src/ReplForm.swift
  appinventor/components-ios/src/WebRTCNativeManager.swift
Labels: pull request: needs review, affects: ucr, regression, ios, testflight

#2868 Remove use of fatalError in iOS code
  appinventor/AICompanionApp.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  appinventor/AIComponentKit.xcodeproj/project.pbxproj
  appinventor/aicompanionapp/src/ViewController.swift
  appinventor/components-ios/src/Canvas.swift
  appinventor/components-ios/src/DateTimePickerBase.swift
  appinventor/components-ios/src/ListPicker.swift
  appinventor/components-ios/src/Map.swift
  appinventor/components-ios/src/Notifier.swift
  appinventor/components-ios/src/PickerBase.swift
  appinventor/components-ios/src/ShowAlert.swift
  appinventor/components-ios/src/Spinner.swift
  appinventor/components-ios/src/TableArrangement.swift
  appinventor/components-ios/src/Translator.swift
  appinventor/components-ios/src/YailRuntimeError.swift
Labels: pull request: needs reply to review, technical debt, affects: ucr, ios
