Repository mit-cml/appinventor-sources, pull requests merged in 2023-06, with the labels that each got.

#2902 bugfix/iPad ImageSprite display and position mismatch
  appinventor/components-ios/src/ImageSprite.swift
Labels: bug, pull request: needs review, affects: ucr, ios

#2861 Patch ZXCapture to work with iPadOS 16
  appinventor/Pods/ZXingObjC/ZXingObjC/client/ZXCapture.m
Labels: enhancement, pull request: needs review, affects: ucr, ios, testflight

#2905 Implement ChatBot and ImageBot for iOS
  appinventor/AIComponentKit.xcodeproj/project.pbxproj
  appinventor/components-ios/src/ChatBot.swift
  appinventor/components-ios/src/ErrorMessages.swift
  appinventor/components-ios/src/HVArrangement.swift
  appinventor/components-ios/src/ImageBot.swift
  appinventor/components-ios/src/ProxiedComponent.swift
  appinventor/components-ios/src/chat.pb.swift
  appinventor/components-ios/src/chat.proto
  appinventor/components-ios/src/image.pb.swift
  appinventor/components-ios/src/image.proto
Labels: pull request: needs review, feature request, affects: ucr, ios

#2899 Dispatch error to screen if not handled by spreadsheet
  appinventor/components/src/com/google/appinventor/components/runtime/Spreadsheet.java
  appinventor/components/src/com/google/appinventor/components/runtime/util/ErrorMessages.java
Labels: bug, pull request: needs review, affects: ucr, android

#2904 Add MediaUtil support for file asset URLs in APKs
  appinventor/components/src/com/google/appinventor/components/runtime/util/MediaUtil.java
Labels: pull request: needs review, affects: ucr, android

#2907 Bump iOS version number to 2.64.2 (12)
  appinventor/aicompanionapp/src/Info.plist
Labels: pull request: needs review, affects: ucr

#2913 Ensure SpeechRecognition session valid after TextToSpeech or other audio
  appinventor/components-ios/src/SpeechRecognizer.swift
Labels: bug, pull request: needs review, affects: ucr, ios

#2912 Add missing provider/model fields in ChatBot request
  appinventor/components-ios/src/ChatBot.swift
Labels: bug, pull request: needs review, affects: ucr, ios

#2915 Implement a Stop method for TextToSpeech
  appinventor/appengine/src/com/google/appinventor/client/youngandroid/YoungAndroidFormUpgrader.java
  appinventor/blocklyeditor/src/versioning.js
  appinventor/components-ios/src/TextToSpeech.swift
  appinventor/components/src/com/google/appinventor/components/common/YaVersion.java
  appinventor/components/src/com/google/appinventor/components/runtime/TextToSpeech.java
  appinventor/components/src/com/google/appinventor/components/runtime/util/ExternalTextToSpeech.java
  appinventor/components/src/com/google/appinventor/components/runtime/util/ITextToSpeech.java
  appinventor/components/src/com/google/appinventor/components/runtime/util/InternalTextToSpeech.java
  appinventor/docs/html/reference/components/media.html
  appinventor/docs/markdown/reference/components/media.md
Labels: pull request: needs review, feature request, affects: ucr, testflight

#2921 Only check for helper key for defined properties
  appinventor/blocklyeditor/src/blocks/components.js
Labels: bug, pull request: needs review, affects: master
