Repository mit-cml/appinventor-sources, pull requests merged in 2024-08, with the labels that each got.

#3210 Fix incorrect short-circuit of permission constraint handling
  appinventor/buildserver/src/com/google/appinventor/buildserver/tasks/common/LoadComponentInfo.java
Labels: bug, pull request: needs review, affects: master, on ai2-test, android

#3211 Do not open Picker if BeforePicking fails (BluetoothClient fix)
  appinventor/components/src/com/google/appinventor/components/runtime/BluetoothClient.java
  appinventor/components/src/com/google/appinventor/components/runtime/Picker.java
Labels: bug, pull request: needs review, affects: ucr, android

#3214 Fix DismissProgressDialog dismissing other dialogs
  appinventor/components-ios/src/Notifier.swift
Labels: bug, pull request: needs review, pull request: needs reply to review, affects: ucr, ios

#3223 Fix bug where ListPicker won't open without a BeforePicking event
  appinventor/buildserver/src/com/google/appinventor/buildserver/resources/runtime.scm
  appinventor/components/src/com/google/appinventor/components/runtime/EventDispatcher.java
  appinventor/components/src/com/google/appinventor/components/runtime/Picker.java
Labels: pull request: needs review, affects: ucr, regression, on ai2-test, android

#3226 Remove extra comma in json example
  appinventor/docs/html/reference/blocks/dictionaries.html
  appinventor/docs/markdown/reference/blocks/dictionaries.md
Labels: bug, documentation, pull request: needs review

#3231 Move pull request template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: pull request: needs review, technical debt, affects: master
