Repository mit-cml/appinventor-sources, pull requests merged in 2024-03, with the labels that each got.

#3139 Fix lack of translation on 'add items to list' block
  appinventor/blocklyeditor/src/blocks/lists.js
Labels: bug, pull request: needs review, affects: master, Internationalization

#3145 Add server-side config for enabling some extensions for iOS
  appinventor/appengine/src/com/google/appinventor/client/Ode.java
  appinventor/appengine/src/com/google/appinventor/server/UserInfoServiceImpl.java
  appinventor/appengine/src/com/google/appinventor/server/storage/ObjectifyStorageIo.java
  appinventor/appengine/src/com/google/appinventor/server/storage/StorageIo.java
  appinventor/appengine/src/com/google/appinventor/server/storage/StoredData.java
  appinventor/appengine/src/com/google/appinventor/shared/rpc/user/Config.java
  appinventor/blocklyeditor/src/replmgr.js
Labels: pull request: needs review, technical debt, affects: master

#2496 [GSoC] Animation Improvements
  appinventor/appengine/src/com/google/appinventor/client/OdeMessages.java
  appinventor/appengine/src/com/google/appinventor/client/editor/simple/components/MockBall.java
  appinventor/appengine/src/com/google/appinventor/client/editor/simple/components/MockImageSprite.java
  appinventor/appengine/src/com/google/appinventor/client/editor/simple/components/utils/PropertiesUtil.java
  appinventor/appengine/src/com/google/appinventor/client/editor/youngandroid/properties/YoungAndroidSpriteOriginPropertyEditor.java
  appinventor/appengine/src/com/google/appinventor/client/widgets/dnd/DragSourcePanel.java
  appinventor/appengine/src/com/google/appinventor/client/widgets/dnd/DragSourceSupport.java
  appinventor/appengine/src/com/google/appinventor/client/widgets/properties/EditableProperty.java
  appinventor/appengine/src/com/google/appinventor/client/wizards/MarkOriginWizard.java
  appinventor/appengine/src/com/google/appinventor/client/youngandroid/YoungAndroidFormUpgrader.java
  appinventor/blocklyeditor/src/versioning.js
  appinventor/components/src/com/google/appinventor/components/common/PropertyTypeConstants.java
  appinventor/components/src/com/google/appinventor/components/common/YaVersion.java
  appinventor/components/src/com/google/appinventor/components/runtime/Ball.java
  appinventor/components/src/com/google/appinventor/components/runtime/ImageSprite.java
  appinventor/components/src/com/google/appinventor/components/runtime/Sprite.java
  appinventor/components/src/com/google/appinventor/components/runtime/util/Vector2D.java
  appinventor/components/tests/com/google/appinventor/components/runtime/SpriteCollisionTest.java
  appinventor/components/tests/com/google/appinventor/components/runtime/SpriteTest.java
  appinventor/docs/html/reference/components/animation.html
  appinventor/docs/markdown/reference/components/animation.md
Labels: pull request: needs review, feature request, affects: ucr, Is Still Draft

#3137 Chinese Simplified update March 2024
  appinventor/appengine/src/com/google/appinventor/client/OdeMessages_zh_CN.properties
  appinventor/appengine/src/com/google/appinventor/client/explorer/dialogs/NoProjectDialogBoxNoProjectDialogBoxUiBinderImplGenMessages_zh_CN.properties
  appinventor/blocklyeditor/src/msg/ai_blockly/messages_zh_CN.json
Labels: translation

#2262 Update login.jsp to handle locale
  appinventor/appengine/src/com/google/appinventor/server/LoginServlet.java
  appinventor/appengine/src/com/google/appinventor/server/loginmessages_zh_cn.properties
  appinventor/appengine/war/login.jsp
Labels: enhancement, pull request: needs reply to review, affects: master
