Repository mit-cml/appinventor-sources, pull requests merged in 2024-01, with the labels that each got.

#3061 Update README to add git submodule instructions for vagrant workflow
  README.md
Labels: documentation, pull request: needs review, affects: master

#3087 Fixed ListView selection removal bug #3008
  appinventor/components/src/com/google/appinventor/components/runtime/ListView.java
  appinventor/components/tests/com/google/appinventor/components/runtime/ListViewTest.java
Labels: bug, pull request: needs review, affects: ucr, android

#3077 Use correct units in VideoPlayer for iOS
  appinventor/components-ios/src/VideoPlayer.swift
Labels: bug, pull request: needs review, affects: ucr, ios

#2466 New Test cases Class for TinyDB component.
  appinventor/components/tests/com/google/appinventor/components/runtime/TinyDBTest.java
Labels: pull request: needs review, technical debt, affects: master

#3080 Implement Promises for Ode
  appinventor/appengine/build.xml
  appinventor/appengine/src/com/google/appinventor/client/Ode.java
  appinventor/appengine/src/com/google/appinventor/client/editor/simple/ComponentNotFoundException.java
  appinventor/appengine/src/com/google/appinventor/client/editor/youngandroid/YaBlocksEditor.java
  appinventor/appengine/src/com/google/appinventor/client/editor/youngandroid/YaFormEditor.java
  appinventor/appengine/src/com/google/appinventor/client/editor/youngandroid/YaProjectEditor.java
  appinventor/appengine/src/com/google/appinventor/client/editor/youngandroid/i18n/BlocklyMsg.java
  appinventor/appengine/src/com/google/appinventor/client/explorer/project/ProjectManager.java
  appinventor/appengine/src/com/google/appinventor/client/settings/SettingsAccessProvider.java
  appinventor/appengine/src/com/google/appinventor/client/settings/project/ProjectSettings.java
  appinventor/appengine/src/com/google/appinventor/client/settings/user/UserSettings.java
  appinventor/appengine/src/com/google/appinventor/client/utils/Promise.java
  appinventor/appengine/src/com/google/appinventor/client/utils/Urls.java
  appinventor/appengine/src/com/google/appinventor/client/wizards/ComponentImportWizard.java
  appinventor/appengine/src/com/google/appinventor/client/wizards/ComponentRenameWizard.java
Labels: enhancement, pull request: needs review, affects: master

#3092 Allow renaming template projects on name conflict
  appinventor/appengine/src/com/google/appinventor/client/wizards/TemplateUploadWizard.java
Labels: pull request: needs review, technical debt, affects: master

#3100 Make sure the buildserver includes extensions
  appinventor/buildserver/src/com/google/appinventor/buildserver/tasks/android/RunD8.java
Labels: pull request: needs review, affects: master

#3103 Increase the stack size when invoking d8
  appinventor/buildserver/src/com/google/appinventor/buildserver/tasks/android/RunD8.java
Labels: pull request: needs review, pull request: in review, affects: master, regression, android

#3105 Address some issues in new promises code
  appinventor/appengine/src/com/google/appinventor/client/editor/youngandroid/YaProjectEditor.java
  appinventor/appengine/src/com/google/appinventor/client/utils/Promise.java
Labels: pull request: needs review, affects: master, regression

#3106 Add accessibility link and update copyright year
  appinventor/docs/html/reference/blocks/colors.html
  appinventor/docs/html/reference/blocks/control.html
  appinventor/docs/html/reference/blocks/dictionaries.html
  appinventor/docs/html/reference/blocks/index.html
  appinventor/docs/html/reference/blocks/lists.html
  appinventor/docs/html/reference/blocks/logic.html
  appinventor/docs/html/reference/blocks/math.html
  appinventor/docs/html/reference/blocks/procedures.html
  appinventor/docs/html/reference/blocks/text.html
  appinventor/docs/html/reference/blocks/variables.html
  appinventor/docs/html/reference/components/animation.html
  appinventor/docs/html/reference/components/charts.html
  appinventor/docs/html/reference/components/connectivity.html
  appinventor/docs/html/reference/components/datascience.html
  appinventor/docs/html/reference/components/experimental.html
  appinventor/docs/html/reference/components/index.html
  appinventor/docs/html/reference/components/layout.html
  appinventor/docs/html/reference/components/legomindstorms.html
  appinventor/docs/html/reference/components/maps.html
  appinventor/docs/html/reference/components/media.html
  appinventor/docs/html/reference/components/sensors.html
  appinventor/docs/html/reference/components/social.html
  appinventor/docs/html/reference/components/storage.html
  appinventor/docs/html/reference/components/userinterface.html
  appinventor/docs/html/reference/concepts/lists.html
  appinventor/docs/html/reference/concepts/mutators.html
  appinventor/docs/html/reference/concepts/pholo.html
  appinventor/docs/html/reference/index.html
  appinventor/docs/html/reference/other/IoT.html
  appinventor/docs/html/reference/other/activitystarter.html
  appinventor/docs/html/reference/other/advanced-listview.html
  appinventor/docs/html/reference/other/any-component-blocks.html
  appinventor/docs/html/reference/other/appstoplay.html
  appinventor/docs/html/reference/other/backpack.html
  appinventor/docs/html/reference/other/compatibilityIssues.html
  appinventor/docs/html/reference/other/displaylist.html
  appinventor/docs/html/reference/other/download-pngs.html
  appinventor/docs/html/reference/other/editing-functions.html
  appinventor/docs/html/reference/other/emulator.html
  appinventor/docs/html/reference/other/extensions.html
  appinventor/docs/html/reference/other/extensionsGestures.html
  appinventor/docs/html/reference/other/extensionsMultitouch.html
  appinventor/docs/html/reference/other/extensionsRotation.html
  appinventor/docs/html/reference/other/firebaseIntro.html
  appinventor/docs/html/reference/other/genymotion.html
  appinventor/docs/html/reference/other/googlesheets-api-setup.html
  appinventor/docs/html/reference/other/index.html
  appinventor/docs/html/reference/other/json-web-apis.html
  appinventor/docs/html/reference/other/locationsensor.html
  appinventor/docs/html/reference/other/manyscreens.html
  appinventor/docs/html/reference/other/media.html
  appinventor/docs/html/reference/other/merger.html
  appinventor/docs/html/reference/other/responsiveDesign.html
  appinventor/docs/html/reference/other/sizes.html
  appinventor/docs/html/reference/other/testing.html
  appinventor/docs/html/reference/other/tinywebdb.html
  appinventor/docs/html/reference/other/usingImages.html
  appinventor/docs/html/reference/other/vr.html
  appinventor/docs/html/reference/other/xml.html
  appinventor/docs/markdown/_includes/footer.html
Labels: documentation, pull request: needs review, affects: master
