Repository mit-cml/appinventor-sources, pull requests merged in 2024-02, with the labels that each got.

#3102 Fix Internal TTS infinite callback
  appinventor/components/src/com/google/appinventor/components/runtime/util/InternalTextToSpeech.java
Labels: bug, pull request: needs review, affects: ucr, android

#3096 Fix ios scrolling
  appinventor/components-ios/src/Form.swift
Labels: bug, pull request: needs review, affects: ucr, ios

#3116 Japanese translation initial release.
  appinventor/appengine/src/com/google/appinventor/YaClient.gwt.xml
  appinventor/appengine/src/com/google/appinventor/client/OdeMessages_ja.properties
  appinventor/appengine/src/com/google/appinventor/client/explorer/dialogs/NoProjectDialogBoxNoProjectDialogBoxUiBinderImplGenMessages_ja.properties
  appinventor/appengine/src/com/google/appinventor/client/languages.json
  appinventor/blocklyeditor/src/msg/ai_blockly/messages_ja.json
Labels: pull request: needs review, affects: master, translation

#3073 Added documentation for special regex characters in 'replace all' block
  appinventor/docs/html/reference/blocks/text.html
  appinventor/docs/markdown/reference/blocks/text.md
Labels: documentation, pull request: needs reply to review, affects: master

#3095 Added DataFile component description in documentation
  appinventor/components/src/com/google/appinventor/components/runtime/DataFile.java
  appinventor/docs/html/reference/components/storage.html
  appinventor/docs/markdown/reference/components/storage.md
Labels: documentation, pull request: needs review, affects: master

#3117 Spanish update
  appinventor/appengine/src/com/google/appinventor/client/OdeMessages_es_ES.properties
  appinventor/appengine/src/com/google/appinventor/client/explorer/dialogs/NoProjectDialogBoxNoProjectDialogBoxUiBinderImplGenMessages_es.properties
  appinventor/blocklyeditor/src/msg/ai_blockly/messages_es.json
Labels: pull request: needs review, affects: master, translation

#3112 Fixed FontSize bugs of CheckBox and Switch in the Designer
  appinventor/appengine/src/com/google/appinventor/client/editor/simple/components/MockCheckBox.java
  appinventor/appengine/src/com/google/appinventor/client/editor/simple/components/MockSwitch.java
  appinventor/appengine/src/com/google/appinventor/client/editor/simple/components/MockToggleBase.java
Labels: bug, pull request: needs reply to review, affects: master

#2374 Allow sharing files from app private directory
  appinventor/buildserver/src/com/google/appinventor/buildserver/tasks/android/XmlConfig.java
  appinventor/components/src/com/google/appinventor/components/runtime/Sharing.java
  appinventor/docs/html/reference/components/social.html
  appinventor/docs/markdown/reference/components/social.md
Labels: enhancement, pull request: needs reply to review, affects: master

#3093 OnTextChanged, HintColor property and MoveCursorTo methods (including Front and End) for TextBoxes
  appinventor/appengine/src/com/google/appinventor/client/youngandroid/YoungAndroidFormUpgrader.java
  appinventor/blocklyeditor/src/versioning.js
  appinventor/components/src/com/google/appinventor/components/common/YaVersion.java
  appinventor/components/src/com/google/appinventor/components/runtime/PasswordTextBox.java
  appinventor/components/src/com/google/appinventor/components/runtime/TextBoxBase.java
  appinventor/docs/html/reference/components/social.html
  appinventor/docs/html/reference/components/userinterface.html
  appinventor/docs/markdown/reference/components/social.md
  appinventor/docs/markdown/reference/components/userinterface.md
Labels: pull request: needs reply to review, feature request, affects: ucr, android

#3119 Use border box sizing for MockPasswordTextBox
  appinventor/appengine/war/static/css/Ya.css
Labels: bug, pull request: needs review, affects: master

#3111 Handle quoted-strings in Content-Type charset parameter
  appinventor/components-ios/src/Web.swift
Labels: bug, pull request: needs review, affects: ucr, ios

#2937 Progress Components
  appinventor/appengine/src/com/google/appinventor/client/Images.java
  appinventor/appengine/src/com/google/appinventor/client/editor/simple/components/MockCircularProgress.java
  appinventor/appengine/src/com/google/appinventor/client/editor/simple/components/MockLinearProgress.java
  appinventor/appengine/src/com/google/appinventor/client/editor/simple/palette/SimpleComponentDescriptor.java
  appinventor/appengine/src/com/google/appinventor/images/circularProgress.png
  appinventor/appengine/src/com/google/appinventor/images/linearProgress.png
  appinventor/components/src/com/google/appinventor/components/common/YaVersion.java
  appinventor/components/src/com/google/appinventor/components/runtime/CircularProgress.java
  appinventor/components/src/com/google/appinventor/components/runtime/LinearProgress.java
Labels: pull request: needs reply to review, affects: ucr, android, kodular

#3118 Remove duplicated zh_TW translation file and generator code
  appinventor/appengine/src/com/google/appinventor/client/editor/youngandroid/i18n/BlocklyTranslationGenerator.java
  appinventor/blocklyeditor/src/msg/ai_blockly/messages_zh_tw.json
Labels: pull request: needs review, affects: master, translation

#3120 Implement PR #3093 for iOS
  appinventor/components-ios/src/EmailPicker.swift
  appinventor/components-ios/src/PasswordTextBox.swift
  appinventor/components-ios/src/TextBox.swift
  appinventor/components-ios/src/TextBoxBase.swift
Labels: pull request: needs review, feature request, affects: ucr, ios

#3123 Fix project properties dialog not accessible in non-English languages
  appinventor/appengine/src/com/google/appinventor/client/explorer/dialogs/ProjectPropertiesDialogBox.java
Labels: pull request: needs review, affects: master, Internationalization

#3121 Fixed TextBoxBase.TextChanged() issue in previous PR
  appinventor/components/src/com/google/appinventor/components/runtime/TextBoxBase.java
Labels: bug, pull request: needs reply to review, affects: ucr, android

#3032 new project wizard added
  appinventor/appengine/src/com/google/appinventor/client/OdeMessages.java
  appinventor/appengine/src/com/google/appinventor/client/editor/youngandroid/YaFormEditor.java
  appinventor/appengine/src/com/google/appinventor/client/editor/youngandroid/properties/YoungAndroidThemeChoicePropertyEditor.java
  appinventor/appengine/src/com/google/appinventor/client/widgets/properties/ChoicePropertyEditor.java
  appinventor/appengine/src/com/google/appinventor/client/widgets/properties/SubsetJSONPropertyEditor.java
  appinventor/appengine/src/com/google/appinventor/client/widgets/properties/toolkit_beginner.json
  appinventor/appengine/src/com/google/appinventor/client/widgets/properties/toolkit_intermediate.json
  appinventor/appengine/src/com/google/appinventor/client/wizards/youngandroid/NewYoungAndroidProjectWizard.java
  appinventor/appengine/src/com/google/appinventor/client/wizards/youngandroid/NewYoungAndroidProjectWizard.ui.xml
  appinventor/appengine/src/com/google/appinventor/server/project/youngandroid/YoungAndroidProjectService.java
  appinventor/appengine/src/com/google/appinventor/shared/rpc/project/youngandroid/NewYoungAndroidProjectParameters.java
  appinventor/appengine/tests/com/google/appinventor/server/ProjectServiceTest.java
  appinventor/appengine/war/static/css/Ya.css
  appinventor/components/src/com/google/appinventor/components/runtime/Form.java
  appinventor/docs/html/reference/components/userinterface.html
  appinventor/docs/markdown/reference/components/userinterface.md
Labels: enhancement, pull request: needs reply to review, affects: master

#3124 Coerce NSString to int when applicable in YAIL
  appinventor/schemekit/src/yail.m
Labels: bug, pull request: needs review, affects: ucr, ios

#3126 Correct a small documentation error and rebuild
  appinventor/components/src/com/google/appinventor/components/runtime/DataCollection.java
  appinventor/docs/html/reference/components/charts.html
  appinventor/docs/html/reference/components/social.html
  appinventor/docs/html/reference/components/userinterface.html
  appinventor/docs/markdown/reference/components/charts.md
  appinventor/docs/markdown/reference/components/social.md
  appinventor/docs/markdown/reference/components/userinterface.md
Labels: documentation, pull request: needs review, affects: ucr

#3125 Disable broken Upload File option in Toolkit editor
  appinventor/appengine/src/com/google/appinventor/client/widgets/properties/SubsetJSONPropertyEditor.java
Labels: bug, pull request: needs review, affects: master

#3085 Implement Trendline component for Charts
  appinventor/appengine/src/com/google/appinventor/client/Images.java
  appinventor/appengine/src/com/google/appinventor/client/OdeMessages.java
  appinventor/appengine/src/com/google/appinventor/client/editor/simple/components/MockChart.java
  appinventor/appengine/src/com/google/appinventor/client/editor/simple/components/MockChartData.java
  appinventor/appengine/src/com/google/appinventor/client/editor/simple/components/MockChartLayout.java
  appinventor/appengine/src/com/google/appinventor/client/editor/simple/components/MockTrendline.java
  appinventor/appengine/src/com/google/appinventor/client/editor/simple/components/utils/PropertiesUtil.java
  appinventor/appengine/src/com/google/appinventor/client/editor/simple/palette/SimpleComponentDescriptor.java
  appinventor/appengine/src/com/google/appinventor/client/editor/youngandroid/properties/YoungAndroidBestFitModelPropertyEditor.java
  appinventor/appengine/src/com/google/appinventor/client/editor/youngandroid/properties/YoungAndroidStrokeStylePropertyEditor.java
  appinventor/appengine/src/com/google/appinventor/client/youngandroid/YoungAndroidFormUpgrader.java
  appinventor/appengine/src/com/google/appinventor/images/trendline.png
  appinventor/blocklyeditor/src/versioning.js
  appinventor/components/build.xml
  appinventor/components/src/com/google/appinventor/components/common/BestFitModel.java
  appinventor/components/src/com/google/appinventor/components/common/LOBFValues.java
  appinventor/components/src/com/google/appinventor/components/common/LinearRegression.java
  appinventor/components/src/com/google/appinventor/components/common/PropertyTypeConstants.java
  appinventor/components/src/com/google/appinventor/components/common/StrokeStyle.java
  appinventor/components/src/com/google/appinventor/components/common/TrendlineCalculator.java
  appinventor/components/src/com/google/appinventor/components/common/YaVersion.java
  appinventor/components/src/com/google/appinventor/components/runtime/AnomalyDetection.java
  appinventor/components/src/com/google/appinventor/components/runtime/AxisChartView.java
  appinventor/components/src/com/google/appinventor/components/runtime/Chart.java
  appinventor/components/src/com/google/appinventor/components/runtime/ChartComponent.java
  appinventor/components/src/com/google/appinventor/components/runtime/ChartData2D.java
  appinventor/components/src/com/google/appinventor/components/runtime/ChartDataBase.java
  appinventor/components/src/com/google/appinventor/components/runtime/ChartView.java
  appinventor/components/src/com/google/appinventor/components/runtime/DataCollection.java
  appinventor/components/src/com/google/appinventor/components/runtime/LineChartBaseDataModel.java
  appinventor/components/src/com/google/appinventor/components/runtime/LineChartDataModel.java
  appinventor/components/src/com/google/appinventor/components/runtime/LineChartViewBase.java
  appinventor/components/src/com/google/appinventor/components/runtime/Regression.java
  appinventor/components/src/com/google/appinventor/components/runtime/ScatterChartDataModel.java
  appinventor/components/src/com/google/appinventor/components/runtime/ScatterChartView.java
  appinventor/components/src/com/google/appinventor/components/runtime/Trendline.java
  appinventor/components/src/com/google/appinventor/components/runtime/util/ExponentialRegression.java
  appinventor/components/src/com/google/appinventor/components/runtime/util/HasTrendline.java
  appinventor/components/src/com/google/appinventor/components/runtime/util/LineWithTrendlineRenderer.java
  appinventor/components/src/com/google/appinventor/components/runtime/util/LogarithmicRegression.java
  appinventor/components/src/com/google/appinventor/components/runtime/util/OlsTrendLine.java
  appinventor/components/src/com/google/appinventor/components/runtime/util/QuadraticRegression.java
  appinventor/components/src/com/google/appinventor/components/runtime/util/ScatterWithTrendlineRenderer.java
  appinventor/components/src/com/google/appinventor/components/runtime/util/YailDictionary.java
  appinventor/components/tests/com/google/appinventor/components/runtime/AbstractChartTest.java
  appinventor/components/tests/com/google/appinventor/components/runtime/AnomalyDetectionTest.java
  appinventor/docs/html/reference/components/charts.html
  appinventor/docs/html/reference/components/datascience.html
  appinventor/docs/markdown/reference/components/charts.md
  appinventor/docs/markdown/reference/components/datascience.md
  appinventor/lib/commons-math3/commons-math3-3.6.1.jar
Labels: pull request: needs review, feature request, affects: ucr, android
