Repository mit-cml/appinventor-sources, pull requests merged in 2025-02, with the labels that each got.

#3328 fix to 1880, handle aia files in url param repo
  appinventor/appengine/src/com/google/appinventor/client/Ode.java
  appinventor/appengine/src/com/google/appinventor/client/utils/HTML5DragDrop.java
  appinventor/appengine/src/com/google/appinventor/client/utils/html5dnd.js
Labels: enhancement, pull request: needs review, affects: master

#3353 Issue 3329 and minor commits
  appinventor/appengine/src/com/google/appinventor/client/Ode.java
  appinventor/appengine/src/com/google/appinventor/client/TopPanel.java
  appinventor/appengine/src/com/google/appinventor/client/editor/simple/components/MockForm.java
Labels: bug, pull request: needs reply to review, affects: master

#3324 Added error handling in Spreadsheet component
  appinventor/components/src/com/google/appinventor/components/runtime/Spreadsheet.java
Labels: pull request: needs reply to review, technical debt, affects: ucr, android

#3354 Fix #3335: Detect and handle unavailable extensions in dragged PNGs
  appinventor/blocklyeditor/src/exportBlocksImage.js
  appinventor/blocklyeditor/src/msg/ai_blockly/messages.json
  appinventor/blocklyeditor/src/msg/ai_blockly/messages_ca.json
  appinventor/blocklyeditor/src/msg/ai_blockly/messages_de.json
  appinventor/blocklyeditor/src/msg/ai_blockly/messages_es.json
  appinventor/blocklyeditor/src/msg/ai_blockly/messages_fr.json
  appinventor/blocklyeditor/src/msg/ai_blockly/messages_he.json
  appinventor/blocklyeditor/src/msg/ai_blockly/messages_hu.json
  appinventor/blocklyeditor/src/msg/ai_blockly/messages_hy.json
  appinventor/blocklyeditor/src/msg/ai_blockly/messages_it.json
  appinventor/blocklyeditor/src/msg/ai_blockly/messages_ja.json
  appinventor/blocklyeditor/src/msg/ai_blockly/messages_ko.json
  appinventor/blocklyeditor/src/msg/ai_blockly/messages_lt.json
  appinventor/blocklyeditor/src/msg/ai_blockly/messages_nl.json
  appinventor/blocklyeditor/src/msg/ai_blockly/messages_pl.json
  appinventor/blocklyeditor/src/msg/ai_blockly/messages_pt.json
  appinventor/blocklyeditor/src/msg/ai_blockly/messages_pt_BR.json
  appinventor/blocklyeditor/src/msg/ai_blockly/messages_ru.json
  appinventor/blocklyeditor/src/msg/ai_blockly/messages_sv.json
  appinventor/blocklyeditor/src/msg/ai_blockly/messages_tr.json
  appinventor/blocklyeditor/src/msg/ai_blockly/messages_uk.json
  appinventor/blocklyeditor/src/msg/ai_blockly/messages_zh_CN.json
  appinventor/blocklyeditor/src/msg/ai_blockly/messages_zh_TW.json
Labels: bug, pull request: in review, affects: master

#3369 Fix copy paste in designer
  appinventor/appengine/src/com/google/appinventor/client/editor/youngandroid/YaFormEditor.java
Labels: bug, pull request: needs review, affects: master

#3368 Make Blockly 10 build on Windows
  appinventor/blocklyeditor/build.xml
Labels: pull request: needs review, affects: master, regression

#3379 Refactor and fix issues in designer copy/paste in Chrome
  appinventor/appengine/src/com/google/appinventor/client/editor/youngandroid/YaBlocksEditor.java
  appinventor/appengine/src/com/google/appinventor/client/editor/youngandroid/YaFormEditor.java
Labels: pull request: needs review, affects: master, regression

#3382 Make Blockly controls high contrast with background again
  appinventor/blocklyeditor/src/blocklyeditor.js
  appinventor/lib/blockly/blockly_compressed.js
  appinventor/lib/blockly/media/sprites.png
  appinventor/lib/blockly/media/sprites.svg
Labels: pull request: needs review, affects: master, regression

#3303 Update AIProject.java
  appinventor/aimerger_for_appinv_classic/src/edu/mills/feeney/thesis/aimerger/AIProject.java
Labels: pull request: needs reply to review, technical debt, affects: master

#3371 Fixed passwordtextbox textchanged function not working previously
  appinventor/components-ios/src/PasswordTextBox.swift
Labels: bug, pull request: needs review, affects: ucr, ios

#3292 Added @UsesXmls annotation which allows to create xml files in APK resources
  appinventor/buildserver/src/com/google/appinventor/buildserver/context/ComponentInfo.java
  appinventor/buildserver/src/com/google/appinventor/buildserver/tasks/android/XmlConfig.java
  appinventor/buildserver/src/com/google/appinventor/buildserver/tasks/common/LoadComponentInfo.java
  appinventor/components/src/com/google/appinventor/components/annotations/UsesXmls.java
  appinventor/components/src/com/google/appinventor/components/annotations/XmlElement.java
  appinventor/components/src/com/google/appinventor/components/common/ComponentDescriptorConstants.java
  appinventor/components/src/com/google/appinventor/components/scripts/ComponentListGenerator.java
  appinventor/components/src/com/google/appinventor/components/scripts/ComponentProcessor.java
Labels: pull request: needs reply to review, feature request, affects: master, android

#3383 Fix internal error from dictionaries drawer in Japanese
  appinventor/blocklyeditor/src/msg/ai_blockly/messages_ja.json
Labels: bug, pull request: needs review, affects: master

#3373 Add Support for conducting surveys of users
  appinventor/appengine/src/com/google/appinventor/client/Ode.java
  appinventor/appengine/src/com/google/appinventor/client/utils/Urls.java
  appinventor/appengine/src/com/google/appinventor/server/UserInfoServiceImpl.java
  appinventor/appengine/src/com/google/appinventor/server/survey/Survey.java
  appinventor/appengine/src/com/google/appinventor/server/survey/SurveyProto.java
  appinventor/appengine/src/com/google/appinventor/server/survey/survey.proto
  appinventor/appengine/src/com/google/appinventor/shared/rpc/user/Config.java
  appinventor/common/src/com/google/appinventor/common/version/AppInventorFeatures.java
Labels: pull request: needs review, affects: master

#3342 Trash refactor
  appinventor/appengine/src/com/google/appinventor/client/OdeMessages.java
  appinventor/appengine/src/com/google/appinventor/client/actions/DeleteAction.java
  appinventor/appengine/src/com/google/appinventor/client/actions/DeleteForeverProjectAction.java
  appinventor/appengine/src/com/google/appinventor/client/actions/RestoreProjectAction.java
  appinventor/appengine/src/com/google/appinventor/client/explorer/folder/ProjectFolder.java
  appinventor/appengine/src/com/google/appinventor/client/explorer/project/Project.java
  appinventor/appengine/src/com/google/appinventor/client/explorer/project/ProjectManager.java
  appinventor/appengine/src/com/google/appinventor/client/explorer/youngandroid/ProjectList.java
  appinventor/appengine/src/com/google/appinventor/client/wizards/MoveProjectsWizard.java
Labels: enhancement, pull request: needs reply to review, affects: master

#3280 Adapting Mock ListView to new ListView properties.
  appinventor/appengine/src/com/google/appinventor/client/editor/simple/components/MockComponentsUtil.java
  appinventor/appengine/src/com/google/appinventor/client/editor/simple/components/MockListView.java
  appinventor/appengine/src/com/google/appinventor/client/editor/simple/components/MockVisibleComponent.java
  appinventor/appengine/war/static/css/Ya.css
Labels: enhancement, pull request: needs review, affects: master

#3402 Fix expired service overlay for Neo
  appinventor/appengine/src/com/google/appinventor/client/widgets/ExpiredServiceOverlay.ui.xml
Labels: pull request: needs review, affects: master, regression
