Repository mit-cml/appinventor-sources, pull requests merged in 2025-04, with the labels that each got.

#3362 Fix folder name validation to replace invalid characters and correct error messages (#3345)
  appinventor/appengine/src/com/google/appinventor/client/OdeMessages.java
  appinventor/appengine/src/com/google/appinventor/client/wizards/NewFolderWizard.java
  appinventor/appengine/src/com/google/appinventor/client/wizards/RequestNewProjectNameWizard.java
  appinventor/appengine/src/com/google/appinventor/client/youngandroid/TextValidators.java
Labels: pull request: needs review, technical debt, affects: master

#3411 Fix Display Hidden Components Checkbox for All Screens
  appinventor/appengine/src/com/google/appinventor/client/Ode.java
  appinventor/appengine/src/com/google/appinventor/client/editor/simple/SimpleVisibleComponentsPanel.java
  appinventor/appengine/src/com/google/appinventor/client/editor/simple/SimpleVisibleComponentsPanel.ui.xml
  appinventor/appengine/src/com/google/appinventor/client/editor/youngandroid/HiddenComponentsCheckbox.java
  appinventor/appengine/src/com/google/appinventor/client/editor/youngandroid/HiddenComponentsManager.java
  appinventor/appengine/src/com/google/appinventor/client/editor/youngandroid/YaFormEditor.java
  appinventor/appengine/src/com/google/appinventor/client/style/neo/SimpleVisibleComponentsPanelNeo.ui.xml
Labels: pull request: needs review, affects: master, regression

#3147 Add local service implementations to support client-side-only use of App Inventor
  appinventor/appengine/build.xml
  appinventor/appengine/src/com/google/appinventor/YaClient.gwt.xml
  appinventor/appengine/src/com/google/appinventor/client/Ode.java
  appinventor/appengine/src/com/google/appinventor/client/RpcStatusPopup.java
  appinventor/appengine/src/com/google/appinventor/client/actions/ExportZipAction.java
  appinventor/appengine/src/com/google/appinventor/client/jzip/GenerateOptions.java
  appinventor/appengine/src/com/google/appinventor/client/jzip/JSZip.java
  appinventor/appengine/src/com/google/appinventor/client/jzip/LoadOptions.java
  appinventor/appengine/src/com/google/appinventor/client/jzip/TextDecoder.java
  appinventor/appengine/src/com/google/appinventor/client/jzip/TextEncoder.java
  appinventor/appengine/src/com/google/appinventor/client/jzip/Type.java
  appinventor/appengine/src/com/google/appinventor/client/jzip/ZipObject.java
  appinventor/appengine/src/com/google/appinventor/client/local/LocalDownloader.java
  appinventor/appengine/src/com/google/appinventor/client/local/LocalGetMotdService.java
  appinventor/appengine/src/com/google/appinventor/client/local/LocalProjectService.java
  appinventor/appengine/src/com/google/appinventor/client/local/LocalTokenAuthService.java
  appinventor/appengine/src/com/google/appinventor/client/local/LocalUploader.java
  appinventor/appengine/src/com/google/appinventor/client/local/LocalUserInfoService.java
  appinventor/appengine/src/com/google/appinventor/client/utils/Downloader.java
  appinventor/appengine/src/com/google/appinventor/client/utils/Uploader.java
  appinventor/appengine/war/index.jsp
  appinventor/appengine/war/static/js/jszip.min.js
  appinventor/blocklyeditor/src/replmgr.js
Labels: feature request, affects: master, for-ai2-test

#3427 New element layout in ListView.
  appinventor/appengine/src/com/google/appinventor/client/OdeMessages.java
  appinventor/appengine/src/com/google/appinventor/client/editor/simple/components/MockListView.java
  appinventor/appengine/src/com/google/appinventor/client/editor/youngandroid/properties/YoungAndroidListViewAddDataPropertyEditor.java
  appinventor/appengine/src/com/google/appinventor/client/editor/youngandroid/properties/YoungAndroidListViewLayoutChoicePropertyEditor.java
  appinventor/appengine/src/com/google/appinventor/client/youngandroid/YoungAndroidFormUpgrader.java
  appinventor/appengine/war/static/css/Ya.css
  appinventor/blocklyeditor/src/versioning.js
  appinventor/components-ios/src/ListView.swift
  appinventor/components/src/com/google/appinventor/components/common/ComponentConstants.java
  appinventor/components/src/com/google/appinventor/components/common/LayoutType.java
  appinventor/components/src/com/google/appinventor/components/common/YaVersion.java
  appinventor/components/src/com/google/appinventor/components/runtime/Component.java
  appinventor/components/src/com/google/appinventor/components/runtime/ListAdapterWithRecyclerView.java
  appinventor/components/src/com/google/appinventor/components/runtime/ListView.java
  appinventor/components/src/com/google/appinventor/components/runtime/ListViewImageSingleTextAdapter.java
  appinventor/components/src/com/google/appinventor/components/runtime/ListViewImageTopTwoTextAdapter.java
  appinventor/components/src/com/google/appinventor/components/runtime/ListViewImageTwoTextVerticalAdapter.java
  appinventor/components/src/com/google/appinventor/components/runtime/ListViewSingleTextAdapter.java
  appinventor/components/src/com/google/appinventor/components/runtime/ListViewTwoTextAdapter.java
  appinventor/components/src/com/google/appinventor/components/runtime/ListViewTwoTextLinearAdapter.java
  appinventor/docs/markdown/reference/components/userinterface.md
Labels: enhancement, pull request: needs review, affects: ucr, android, ios, for-ai2-test

#3437 Texting Component: Use a notification channel and Ask for Post Notifications Permission
  appinventor/components/src/com/google/appinventor/components/runtime/Texting.java
  appinventor/components/src/com/google/appinventor/components/runtime/util/SmsBroadcastReceiver.java
Labels: pull request: needs reply to review, affects: ucr, regression, android, for-ai2-test

#3445 Redirect to the login page directly from index.jsp
  appinventor/appengine/war/index.jsp
Labels: enhancement, pull request: needs review, affects: master, for-ai2-test
