Repository mit-cml/appinventor-sources, pull requests merged in 2025-03, with the labels that each got.

#3406 Fix warning icon color #3399
  appinventor/blocklyeditor/media/ai2blockly.css
Labels: pull request: needs review, affects: master, regression

#3403 Remove MIT-specific iOS settings from AICompanionApp
  appinventor/AICompanionApp.xcodeproj/project.pbxproj
Labels: pull request: needs review, technical debt, affects: master, ios

#3413 Update documentation deps for Apple Silicon and rebuild docs
  appinventor/docs/html/reference/blocks/dictionaries.html
  appinventor/docs/html/reference/components/userinterface.html
  appinventor/docs/html/reference/other/json-web-apis.html
  appinventor/docs/markdown/Gemfile.lock
Labels: documentation, pull request: needs review, affects: master

#3160 Add custom url for map component
  appinventor/appengine/src/com/google/appinventor/client/OdeMessages.java
  appinventor/appengine/src/com/google/appinventor/client/editor/simple/components/MockMap.java
  appinventor/appengine/src/com/google/appinventor/client/editor/simple/components/utils/PropertiesUtil.java
  appinventor/appengine/src/com/google/appinventor/client/editor/youngandroid/properties/YoungAndroidMapCustomUrlPropertyEditor.java
  appinventor/appengine/src/com/google/appinventor/client/editor/youngandroid/properties/YoungAndroidMapTypePropertyEditor.java
  appinventor/appengine/src/com/google/appinventor/client/youngandroid/YoungAndroidFormUpgrader.java
  appinventor/blocklyeditor/src/versioning.js
  appinventor/components-ios/src/ErrorMessages.swift
  appinventor/components-ios/src/Map.swift
  appinventor/components-ios/src/MapFactory.swift
  appinventor/components/src/com/google/appinventor/components/common/MapType.java
  appinventor/components/src/com/google/appinventor/components/common/PropertyTypeConstants.java
  appinventor/components/src/com/google/appinventor/components/common/YaVersion.java
  appinventor/components/src/com/google/appinventor/components/runtime/Map.java
  appinventor/components/src/com/google/appinventor/components/runtime/util/DummyMapController.java
  appinventor/components/src/com/google/appinventor/components/runtime/util/MapFactory.java
  appinventor/components/src/com/google/appinventor/components/runtime/util/NativeOpenStreetMapController.java
  appinventor/docs/html/reference/components/maps.html
  appinventor/docs/markdown/reference/components/maps.md
Labels: pull request: needs review, feature request, affects: ucr, android

#3391 Fixed custom map type on iOS version
  appinventor/appengine/src/com/google/appinventor/client/OdeMessages.java
  appinventor/appengine/src/com/google/appinventor/client/editor/simple/components/MockMap.java
  appinventor/appengine/src/com/google/appinventor/client/editor/simple/components/utils/PropertiesUtil.java
  appinventor/appengine/src/com/google/appinventor/client/editor/youngandroid/properties/YoungAndroidMapCustomUrlPropertyEditor.java
  appinventor/appengine/src/com/google/appinventor/client/editor/youngandroid/properties/YoungAndroidMapTypePropertyEditor.java
  appinventor/appengine/src/com/google/appinventor/client/youngandroid/YoungAndroidFormUpgrader.java
  appinventor/blocklyeditor/src/versioning.js
  appinventor/components-ios/src/ErrorMessages.swift
  appinventor/components-ios/src/Map.swift
  appinventor/components-ios/src/MapFactory.swift
  appinventor/components/src/com/google/appinventor/components/common/MapType.java
  appinventor/components/src/com/google/appinventor/components/common/PropertyTypeConstants.java
  appinventor/components/src/com/google/appinventor/components/common/YaVersion.java
  appinventor/components/src/com/google/appinventor/components/runtime/Map.java
  appinventor/components/src/com/google/appinventor/components/runtime/util/DummyMapController.java
  appinventor/components/src/com/google/appinventor/components/runtime/util/MapFactory.java
  appinventor/components/src/com/google/appinventor/components/runtime/util/NativeOpenStreetMapController.java
  appinventor/docs/html/reference/components/maps.html
  appinventor/docs/markdown/reference/components/maps.md
Labels: pull request: needs review, feature request, affects: ucr, ios

#1792 Absolute Arrangement
  appinventor/appengine/src/com/google/appinventor/client/editor/simple/components/MockAbsoluteArrangement.java
  appinventor/appengine/src/com/google/appinventor/client/editor/simple/components/MockAbsoluteLayout.java
  appinventor/appengine/src/com/google/appinventor/client/editor/simple/components/MockContainer.java
  appinventor/appengine/src/com/google/appinventor/client/editor/simple/components/MockVisibleComponent.java
  appinventor/appengine/src/com/google/appinventor/client/editor/simple/palette/SimpleComponentDescriptor.java
  appinventor/appengine/src/com/google/appinventor/client/editor/youngandroid/BlocklyPanel.java
  appinventor/appengine/src/com/google/appinventor/client/editor/youngandroid/YaBlocksEditor.java
  appinventor/appengine/src/com/google/appinventor/client/editor/youngandroid/YaFormEditor.java
  appinventor/blocklyeditor/src/component_database.js
  appinventor/blocklyeditor/src/drawer.js
  appinventor/components/src/com/google/appinventor/components/common/ComponentConstants.java
  appinventor/components/src/com/google/appinventor/components/common/YaVersion.java
  appinventor/components/src/com/google/appinventor/components/runtime/AbsoluteArrangement.java
  appinventor/components/src/com/google/appinventor/components/runtime/AndroidViewComponent.java
  appinventor/components/src/com/google/appinventor/components/runtime/Canvas.java
  appinventor/components/src/com/google/appinventor/components/runtime/Chart.java
  appinventor/components/src/com/google/appinventor/components/runtime/ComponentContainer.java
  appinventor/components/src/com/google/appinventor/components/runtime/Form.java
  appinventor/components/src/com/google/appinventor/components/runtime/HVArrangement.java
  appinventor/components/src/com/google/appinventor/components/runtime/MapFeatureContainerBase.java
  appinventor/components/src/com/google/appinventor/components/runtime/RelativeLayout.java
  appinventor/components/src/com/google/appinventor/components/runtime/TableArrangement.java
  appinventor/components/src/com/google/appinventor/components/runtime/util/ViewUtil.java
  appinventor/docs/html/reference/components/animation.html
  appinventor/docs/html/reference/components/charts.html
  appinventor/docs/html/reference/components/layout.html
  appinventor/docs/html/reference/components/maps.html
  appinventor/docs/html/reference/components/media.html
  appinventor/docs/html/reference/components/social.html
  appinventor/docs/html/reference/components/userinterface.html
  appinventor/docs/markdown/reference/components/animation.md
  appinventor/docs/markdown/reference/components/charts.md
  appinventor/docs/markdown/reference/components/layout.md
  appinventor/docs/markdown/reference/components/maps.md
  appinventor/docs/markdown/reference/components/media.md
  appinventor/docs/markdown/reference/components/social.md
  appinventor/docs/markdown/reference/components/userinterface.md
Labels: pull request: needs reply to review, feature request, affects: ucr

#3370 Implement asynchronous location functions
  appinventor/appengine/src/com/google/appinventor/client/youngandroid/YoungAndroidFormUpgrader.java
  appinventor/blocklyeditor/src/versioning.js
  appinventor/components-ios/src/LocationSensor.swift
  appinventor/components/src/com/google/appinventor/components/common/YaVersion.java
  appinventor/components/src/com/google/appinventor/components/runtime/LocationSensor.java
  appinventor/docs/html/reference/components/sensors.html
  appinventor/docs/markdown/reference/components/sensors.md
Labels: pull request: needs review, feature request, affects: ucr, android, ios

#3384 Fix ability to add/remove entries from certain types of charts #3262
  appinventor/components/src/com/google/appinventor/components/runtime/ChartData2D.java
Labels: bug, pull request: needs review, affects: ucr

#3316 Set axes color and added AxesTextColor property
  appinventor/appengine/src/com/google/appinventor/client/youngandroid/YoungAndroidFormUpgrader.java
  appinventor/blocklyeditor/src/versioning.js
  appinventor/components-ios/src/Chart.swift
  appinventor/components-ios/src/ChartDataBase.swift
  appinventor/components-ios/src/ChartDataModel.swift
  appinventor/components/src/com/google/appinventor/components/common/YaVersion.java
  appinventor/components/src/com/google/appinventor/components/runtime/Chart.java
  appinventor/components/src/com/google/appinventor/components/runtime/ChartDataBase.java
  appinventor/components/src/com/google/appinventor/components/runtime/ChartDataModel.java
  appinventor/components/src/com/google/appinventor/components/runtime/PointChartView.java
  appinventor/docs/html/reference/components/charts.html
  appinventor/docs/markdown/reference/components/charts.md
Labels: pull request: needs review, feature request, affects: ucr, android, ios

#2804 Adding-showAsInteger-property-chart2d
  appinventor/appengine/src/com/google/appinventor/client/OdeMessages.java
  appinventor/appengine/src/com/google/appinventor/client/editor/simple/components/utils/PropertiesUtil.java
  appinventor/appengine/src/com/google/appinventor/client/editor/youngandroid/properties/YoungAndroidChartLabelValueTypeChoicePropertyEditor.java
  appinventor/appengine/src/com/google/appinventor/client/youngandroid/YoungAndroidFormUpgrader.java
  appinventor/components/src/com/google/appinventor/components/common/PropertyTypeConstants.java
  appinventor/components/src/com/google/appinventor/components/common/YaVersion.java
  appinventor/components/src/com/google/appinventor/components/runtime/AxisChartView.java
  appinventor/components/src/com/google/appinventor/components/runtime/BarChartDataModel.java
  appinventor/components/src/com/google/appinventor/components/runtime/Chart.java
  appinventor/components/src/com/google/appinventor/components/runtime/ChartComponent.java
  appinventor/components/src/com/google/appinventor/components/runtime/ChartDataBase.java
  appinventor/components/src/com/google/appinventor/components/runtime/ChartDataModel.java
  appinventor/components/src/com/google/appinventor/components/runtime/Component.java
  appinventor/components/src/com/google/appinventor/components/runtime/PointChartDataModel.java
  appinventor/components/src/com/google/appinventor/components/runtime/Trendline.java
  appinventor/docs/html/reference/components/charts.html
  appinventor/docs/markdown/reference/components/charts.md
Labels: enhancement, pull request: needs review, affects: ucr

#3081 Handle throwable with null message in REPL
  appinventor/buildserver/src/com/google/appinventor/buildserver/resources/runtime.scm
  appinventor/components/src/com/google/appinventor/components/runtime/util/AssetFetcher.java
  appinventor/components/src/com/google/appinventor/components/runtime/util/RuntimeErrorAlert.java
Labels: bug, pull request: needs reply to review, affects: ucr, android

#3401 add dependency versions and remove blockly submodule instructions
  README.md
Labels: pull request: needs review, technical debt, affects: master

#3416 Fix half-broken mutator bubbles
  appinventor/blocklyeditor/src/workspace_svg.js
Labels: pull request: needs review, affects: master, regression, for-ai2-test

#3417 Fix procedure names in backpack
  appinventor/blocklyeditor/build.xml
  appinventor/blocklyeditor/src/workspace_svg.js
  appinventor/lib/blockly-plugins/block-lexical-variables-core-2.0.6.min.js
  appinventor/lib/blockly-plugins/block-lexical-variables-core-3.0.1.min.js
Labels: pull request: needs review, affects: master, regression, for-ai2-test

#3420 Fix MockListView in Neo
  appinventor/appengine/src/com/google/appinventor/client/style/neo/neo.css
Labels: enhancement, pull request: needs review, affects: master

#3424 Mark workspace as invisible at initialization time
  appinventor/appengine/src/com/google/appinventor/client/editor/youngandroid/BlocklyPanel.java
Labels: pull request: needs review, affects: master, regression, for-ai2-test

#3152 Update Slider for #2435
  appinventor/appengine/src/com/google/appinventor/client/editor/simple/components/MockSlider.java
  appinventor/appengine/src/com/google/appinventor/client/youngandroid/YoungAndroidFormUpgrader.java
  appinventor/blocklyeditor/src/versioning.js
  appinventor/components-ios/src/Slider.swift
  appinventor/components/src/com/google/appinventor/components/common/YaVersion.java
  appinventor/components/src/com/google/appinventor/components/runtime/Slider.java
  appinventor/docs/markdown/reference/components/userinterface.md
Labels: pull request: needs review, feature request, affects: ucr, android, ios

#3281 Fix margins in ListView
  appinventor/components/src/com/google/appinventor/components/runtime/ListView.java
Labels: bug, pull request: needs reply to review, affects: ucr, android, for-ai2-test

#3426 Fix issues related to labels in AbsoluteArrangement
  appinventor/components/src/com/google/appinventor/components/runtime/Label.java
  appinventor/components/src/com/google/appinventor/components/runtime/RelativeLayout.java
Labels: bug, pull request: needs review, affects: ucr, android, for-ai2-test

#3418 Fix delete key not removing blocks in mutator
  appinventor/appengine/war/static/js/workspace-multiselect-0.1.14-beta1.min.js
Labels: pull request: needs review, affects: master, regression, for-ai2-test

#2483 Fixes issue #2479
  appinventor/appengine/src/com/google/appinventor/client/editor/simple/components/MockContainer.java
  appinventor/appengine/src/com/google/appinventor/client/editor/simple/components/MockTableArrangement.java
  appinventor/appengine/src/com/google/appinventor/client/editor/simple/components/MockTableLayout.java
  appinventor/appengine/src/com/google/appinventor/client/editor/youngandroid/YaFormEditor.java
  appinventor/appengine/src/com/google/appinventor/client/widgets/dnd/DragSourceSupport.java
Labels: bug, pull request: needs reply to review, affects: master, for-ai2-test

#3423 Make Neo the default first-time UIPicker is opened
  appinventor/appengine/src/com/google/appinventor/client/settings/user/GeneralSettings.java
  appinventor/appengine/src/com/google/appinventor/client/wizards/UISettingsWizard.java
Labels: enhancement, pull request: needs review, affects: master, for-ai2-test
