Repository mit-cml/appinventor-sources, pull requests merged in 2025-08, with the labels that each got.

#3537 Make iOS report extension support during rendezvous
  appinventor/aicompanionapp/src/ViewController.swift
  appinventor/blocklyeditor/src/replmgr.js
Labels: enhancement, pull request: needs review, affects: master, ios

#3057 Implement a PermissionRegistry for Android permission constraints
  appinventor/components/src/com/google/appinventor/components/runtime/Form.java
  appinventor/components/src/com/google/appinventor/components/runtime/util/PermissionRegistry.java
Labels: pull request: needs review, technical debt, affects: ucr, android, for-ai2-test

#3524 Add support for remotely debugging Junit tests
  appinventor/build-common.xml
Labels: pull request: needs review, technical debt, affects: master

#3490 Make YoungAndroidPalettePanel a singleton
  appinventor/appengine/src/com/google/appinventor/client/editor/blocks/BlocklyPanel.java
  appinventor/appengine/src/com/google/appinventor/client/editor/blocks/BlocksEditor.java
  appinventor/appengine/src/com/google/appinventor/client/editor/designer/DesignerEditor.java
  appinventor/appengine/src/com/google/appinventor/client/editor/simple/SimpleEditor.java
  appinventor/appengine/src/com/google/appinventor/client/editor/simple/SimpleNonVisibleComponentsPanel.java
  appinventor/appengine/src/com/google/appinventor/client/editor/simple/components/MockComponent.java
  appinventor/appengine/src/com/google/appinventor/client/editor/simple/components/MockContainer.java
  appinventor/appengine/src/com/google/appinventor/client/editor/simple/palette/AbstractPalettePanel.java
  appinventor/appengine/src/com/google/appinventor/client/editor/simple/palette/BaseComponentFactory.java
  appinventor/appengine/src/com/google/appinventor/client/editor/simple/palette/SimpleComponentDescriptor.java
  appinventor/appengine/src/com/google/appinventor/client/editor/simple/palette/SimplePaletteItem.java
  appinventor/appengine/src/com/google/appinventor/client/editor/simple/palette/SimplePalettePanel.java
  appinventor/appengine/src/com/google/appinventor/client/editor/youngandroid/YaBlocksEditor.java
  appinventor/appengine/src/com/google/appinventor/client/editor/youngandroid/YaFormEditor.java
  appinventor/appengine/src/com/google/appinventor/client/editor/youngandroid/YaProjectEditor.java
  appinventor/appengine/src/com/google/appinventor/client/editor/youngandroid/palette/OrderedPaletteHelper.java
  appinventor/appengine/src/com/google/appinventor/client/editor/youngandroid/palette/YoungAndroidPalettePanel.java
  appinventor/appengine/src/com/google/appinventor/client/editor/youngandroid/properties/YoungAndroidChatbotModelPropertyEditor.java
  appinventor/appengine/src/com/google/appinventor/client/editor/youngandroid/properties/YoungAndroidChatbotProviderPropertyEditor.java
  appinventor/appengine/src/com/google/appinventor/client/editor/youngandroid/properties/YoungAndroidMapCustomUrlPropertyEditor.java
  appinventor/components/src/com/google/appinventor/components/runtime/PasswordTextBox.java
Labels: pull request: needs review, affects: master, for-ai2-test

#3470 ColorChoice Property Editor
  appinventor/appengine/src/com/google/appinventor/client/editor/youngandroid/YaProjectEditor.java
  appinventor/appengine/src/com/google/appinventor/client/editor/youngandroid/properties/YoungAndroidColorChoicePropertyEditor.java
  appinventor/appengine/src/com/google/appinventor/client/local/LocalProjectService.java
  appinventor/appengine/src/com/google/appinventor/client/settings/project/YoungAndroidSettings.java
  appinventor/appengine/src/com/google/appinventor/client/widgets/properties/ColorChoicePropertyEditor.java
  appinventor/appengine/src/com/google/appinventor/server/FileImporterImpl.java
  appinventor/appengine/src/com/google/appinventor/server/project/youngandroid/YoungAndroidSettingsBuilder.java
  appinventor/appengine/src/com/google/appinventor/shared/settings/SettingsConstants.java
  appinventor/appengine/war/index.jsp
  appinventor/appengine/war/static/css/nano.min.css
  appinventor/appengine/war/static/js/pickr.min.js
Labels: pull request: needs reply to review, feature request, affects: master, for-ai2-test

#3471 Add password protection to buildserver
  appinventor/appengine/src/com/google/appinventor/server/project/youngandroid/YoungAndroidProjectService.java
  appinventor/appengine/war/WEB-INF/appengine-web.xml
  appinventor/buildserver/build.xml
  appinventor/buildserver/src/com/google/appinventor/buildserver/BuildServer.java
Labels: pull request: needs review, technical debt, affects: master, for-ai2-test

#2230 Implementing .aar libraries for extensions.
  appinventor/buildserver/src/com/google/appinventor/buildserver/tasks/android/AttachAarLibs.java
  appinventor/components/src/com/google/appinventor/components/scripts/ExternalComponentGenerator.java
Labels: pull request: in review, feature request, affects: master, for-ai2-test

#3563 Fix missing icon for PasswordTextBox
  appinventor/appengine/src/com/google/appinventor/client/editor/youngandroid/palette/YoungAndroidComponentFactory.java
  appinventor/appengine/src/com/google/appinventor/client/editor/youngandroid/palette/YoungAndroidPalettePanel.java
Labels: pull request: needs review, affects: master, regression

#3559 Fix broken blocklyeditor builds on Windows
  appinventor/blocklyeditor/build.xml
Labels: pull request: needs review, affects: master, regression

#3568 Make sure we cleanup temporary files after a build is complete
  appinventor/buildserver/src/com/google/appinventor/buildserver/BuildServer.java
Labels: pull request: needs reply to review, affects: master, regression

#3439 Be able to make Splash Screen mandatory
  appinventor/appengine/src/com/google/appinventor/client/Ode.java
Labels: enhancement, pull request: needs reply to review, affects: master

#3567 Fix iOS spreadsheet authentication
  appinventor/components-ios/src/Spreadsheet.swift
Labels: bug, pull request: needs review, affects: master, ios, testflight

#3560 Fix progress view animations on iOS
  appinventor/AICompanionApp.xcodeproj/project.pbxproj
  appinventor/components-ios/src/CircularProgress.swift
  appinventor/components-ios/src/LinearProgress.swift
Labels: bug, pull request: needs review, affects: master, ios, testflight
