Repository mit-cml/appinventor-sources, pull requests merged in 2025-06, with the labels that each got.

#3462 Add Image Creation to ChatBot
  appinventor/appengine/src/com/google/appinventor/client/youngandroid/YoungAndroidFormUpgrader.java
  appinventor/blocklyeditor/src/versioning.js
  appinventor/components/src/com/google/appinventor/components/common/YaVersion.java
  appinventor/components/src/com/google/appinventor/components/runtime/ChatBot.java
  appinventor/components/src/com/google/appinventor/components/runtime/ImageBot.java
  appinventor/components/src/com/google/appinventor/components/runtime/chatbot/ChatBotToken.java
  appinventor/components/src/com/google/appinventor/components/runtime/chatbot/chat.proto
  appinventor/components/src/com/google/appinventor/components/runtime/util/FileUtil.java
  appinventor/docs/markdown/reference/components/experimental.md
Labels: enhancement, pull request: needs review, affects: ucr, android

#3489 Break up component translation map into smaller methods
  appinventor/components/src/com/google/appinventor/components/scripts/ComponentTranslationGenerator.java
Labels: pull request: needs review, technical debt, affects: master

#3476 Fix hanging builds due to malformed keystores
  appinventor/buildserver/src/com/google/appinventor/buildserver/DexExecTask.java
  appinventor/buildserver/src/com/google/appinventor/buildserver/Main.java
  appinventor/buildserver/src/com/google/appinventor/buildserver/ProjectBuilder.java
  appinventor/buildserver/src/com/google/appinventor/buildserver/tasks/android/GenerateClasses.java
  appinventor/buildserver/src/com/google/appinventor/buildserver/tasks/android/RunAapt.java
  appinventor/buildserver/src/com/google/appinventor/buildserver/tasks/android/RunAapt2.java
  appinventor/buildserver/src/com/google/appinventor/buildserver/tasks/android/RunApkSigner.java
  appinventor/buildserver/src/com/google/appinventor/buildserver/tasks/android/RunBundletool.java
  appinventor/buildserver/src/com/google/appinventor/buildserver/tasks/android/RunD8.java
  appinventor/buildserver/src/com/google/appinventor/buildserver/tasks/android/RunZipAlign.java
  appinventor/buildserver/src/com/google/appinventor/buildserver/util/Execution.java
Labels: pull request: needs review, technical debt, affects: master, for-ai2-test

#3497 fix: blocks png lex var color
  appinventor/blocklyeditor/src/exportBlocksImage.js
Labels: pull request: needs review, affects: master, regression

#3501 Change TalkToMe to SimpleChatbot in NoProjectsDialog
  appinventor/appengine/src/com/google/appinventor/client/explorer/dialogs/NoProjectDialogBox.java
  appinventor/appengine/src/com/google/appinventor/client/explorer/dialogs/NoProjectDialogBox.ui.xml
  appinventor/appengine/war/templates/SimpleChatbot/SimpleChatbot.json
  appinventor/appengine/war/templates/SimpleChatbot/SimpleChatbot.zip
  appinventor/appengine/war/templates/SimpleChatbot/screenshot.png
  appinventor/appengine/war/templates/SimpleChatbot/thumbnail.png
Labels: status: new, pull request: needs review, affects: master
