Repository mit-cml/appinventor-sources, pull requests merged in 2025-01, with the labels that each got.

#3305 Provide dialog with connection status
  appinventor/aicompanionapp/src/ViewController.swift
  appinventor/components-ios/src/PhoneStatus.swift
  appinventor/components-ios/src/WebRTCNativeManager.swift
Labels: enhancement, pull request: needs review, affects: ucr, ios, testflight

#3306 Fix bugs in iOS collision detection
  appinventor/components-ios/src/Ball.swift
  appinventor/components-ios/src/Vector2D.swift
Labels: pull request: needs review, affects: ucr, regression, ios, testflight

#3307 Implement potential fix for yail_get_simple_name crash
  appinventor/schemekit/src/yail.m
Labels: bug, pull request: needs review, affects: ucr, ios

#3310 Implement the ScreenOrientation helper for iOS
  appinventor/AIComponentKit.xcodeproj/project.pbxproj
  appinventor/components-ios/src/Form.swift
  appinventor/components-ios/src/OptionList.swift
  appinventor/components-ios/src/ScreenOrientation.swift
  appinventor/components-ios/src/runtime.scm
Labels: pull request: needs review, technical debt, affects: ucr, ios

#3312 Implement LOBFValues for iOS
  appinventor/AIComponentKit.xcodeproj/project.pbxproj
  appinventor/components-ios/src/LOBFValues.swift
  appinventor/components-ios/src/Trendline.swift
Labels: enhancement, pull request: needs review, affects: ucr, ios

#3309 Fix iOS marker moves
  appinventor/components-ios/src/MapFeatureBase.swift
Labels: bug, pull request: needs review, affects: ucr, ios

#3315 Fix TinyDB.swift due to iOS 18 changes
  appinventor/components-ios/src/TinyDB.swift
Labels: pull request: needs review, technical debt, affects: ucr, ios

#3319 Fix Wifi prompt bug in iOS companion
  appinventor/aicompanionapp/src/ViewController.swift
  appinventor/components-ios/src/Notifier.swift
Labels: pull request: needs review, affects: ucr, regression, ios

#3193 Keyboard Navigation
  appinventor/appengine/src/com/google/appinventor/client/Ode.java
  appinventor/appengine/src/com/google/appinventor/client/OdeMessages.java
  appinventor/appengine/src/com/google/appinventor/client/TopToolbar.ui.xml
  appinventor/appengine/src/com/google/appinventor/client/actions/ShowShortcutsAction.java
  appinventor/appengine/src/com/google/appinventor/client/editor/simple/SimpleVisibleComponentsPanel.java
  appinventor/appengine/src/com/google/appinventor/client/editor/simple/SimpleVisibleComponentsPanel.ui.xml
  appinventor/appengine/src/com/google/appinventor/client/editor/simple/components/MockComponent.java
  appinventor/appengine/src/com/google/appinventor/client/editor/simple/components/MockVisibleComponent.java
  appinventor/appengine/src/com/google/appinventor/client/editor/simple/palette/SimplePaletteItem.java
  appinventor/appengine/src/com/google/appinventor/client/editor/youngandroid/DesignToolbar.java
  appinventor/appengine/src/com/google/appinventor/client/editor/youngandroid/YaFormEditor.java
  appinventor/appengine/src/com/google/appinventor/client/editor/youngandroid/actions/RefreshCompanionAction.java
  appinventor/appengine/src/com/google/appinventor/client/editor/youngandroid/actions/ResetAction.java
  appinventor/appengine/src/com/google/appinventor/client/editor/youngandroid/palette/YoungAndroidPalettePanel.java
  appinventor/appengine/src/com/google/appinventor/client/editor/youngandroid/properties/YoungAndroidLengthPropertyEditor.java
  appinventor/appengine/src/com/google/appinventor/client/explorer/SourceStructureExplorer.java
  appinventor/appengine/src/com/google/appinventor/client/explorer/commands/AddFormCommand.java
  appinventor/appengine/src/com/google/appinventor/client/explorer/commands/CopyYoungAndroidProjectCommand.java
  appinventor/appengine/src/com/google/appinventor/client/explorer/commands/DeleteFileCommand.java
  appinventor/appengine/src/com/google/appinventor/client/explorer/dialogs/NoProjectDialogBox.java
  appinventor/appengine/src/com/google/appinventor/client/explorer/dialogs/NoProjectDialogBox.ui.xml
  appinventor/appengine/src/com/google/appinventor/client/explorer/dialogs/ProjectPropertiesDialogBox.java
  appinventor/appengine/src/com/google/appinventor/client/explorer/dialogs/ProjectPropertiesDialogBox.ui.xml
  appinventor/appengine/src/com/google/appinventor/client/explorer/folder/ProjectFolder.java
  appinventor/appengine/src/com/google/appinventor/client/explorer/folder/ProjectFolder.ui.xml
  appinventor/appengine/src/com/google/appinventor/client/explorer/youngandroid/AssetList.java
  appinventor/appengine/src/com/google/appinventor/client/explorer/youngandroid/ProjectList.java
  appinventor/appengine/src/com/google/appinventor/client/explorer/youngandroid/ProjectList.ui.xml
  appinventor/appengine/src/com/google/appinventor/client/explorer/youngandroid/ProjectListItem.java
  appinventor/appengine/src/com/google/appinventor/client/explorer/youngandroid/ProjectListItem.ui.xml
  appinventor/appengine/src/com/google/appinventor/client/style/neo/ProjectFolderNeo.java
  appinventor/appengine/src/com/google/appinventor/client/style/neo/ProjectFolderNeo.ui.xml
  appinventor/appengine/src/com/google/appinventor/client/style/neo/ProjectListItemNeo.java
  appinventor/appengine/src/com/google/appinventor/client/style/neo/ProjectListItemNeo.ui.xml
  appinventor/appengine/src/com/google/appinventor/client/style/neo/ProjectListNeo.java
  appinventor/appengine/src/com/google/appinventor/client/style/neo/ProjectListNeo.ui.xml
  appinventor/appengine/src/com/google/appinventor/client/style/neo/SimpleVisibleComponentsPanelNeo.java
  appinventor/appengine/src/com/google/appinventor/client/style/neo/SimpleVisibleComponentsPanelNeo.ui.xml
  appinventor/appengine/src/com/google/appinventor/client/style/neo/TopPanelNeo.ui.xml
  appinventor/appengine/src/com/google/appinventor/client/variableColors.css
  appinventor/appengine/src/com/google/appinventor/client/widgets/ContextMenu.java
  appinventor/appengine/src/com/google/appinventor/client/widgets/DropDownButton.java
  appinventor/appengine/src/com/google/appinventor/client/widgets/properties/AdditionalChoicePropertyEditor.java
  appinventor/appengine/src/com/google/appinventor/client/widgets/properties/ChoicePropertyEditor.java
  appinventor/appengine/src/com/google/appinventor/client/widgets/properties/ColorChoicePropertyEditor.java
  appinventor/appengine/src/com/google/appinventor/client/widgets/properties/SubsetJSONPropertyEditor.java
  appinventor/appengine/src/com/google/appinventor/client/wizards/Dialog.java
  appinventor/appengine/src/com/google/appinventor/client/wizards/FileUploadWizard.java
  appinventor/appengine/src/com/google/appinventor/client/wizards/FileUploadWizard.ui.xml
  appinventor/appengine/src/com/google/appinventor/client/wizards/MoveProjectsWizard.java
  appinventor/appengine/src/com/google/appinventor/client/wizards/MoveProjectsWizard.ui.xml
  appinventor/appengine/src/com/google/appinventor/client/wizards/NewFolderWizard.java
  appinventor/appengine/src/com/google/appinventor/client/wizards/NewFolderWizard.ui.xml
  appinventor/appengine/src/com/google/appinventor/client/wizards/UISettingsWizard.java
  appinventor/appengine/src/com/google/appinventor/client/wizards/UISettingsWizard.ui.xml
  appinventor/appengine/src/com/google/appinventor/client/wizards/youngandroid/NewYoungAndroidProjectWizard.java
  appinventor/appengine/src/com/google/appinventor/client/wizards/youngandroid/NewYoungAndroidProjectWizard.ui.xml
  appinventor/appengine/war/static/css/Ya.css
Labels: affects: master, GSOC

#3325 Fix: Prevent Auto-loading of Projects from Trash (#3208)
  appinventor/appengine/src/com/google/appinventor/client/Ode.java
  appinventor/appengine/src/com/google/appinventor/client/explorer/project/ProjectManager.java
Labels: bug, pull request: needs review, affects: master

#3304 Fix missing action bar in Device Default theme
  appinventor/blocklyeditor/src/generators/yail.js
Labels: pull request: needs review, affects: master, regression, android

#3299 Call JsonUtil directly from runtime.scm
  appinventor/buildserver/src/com/google/appinventor/buildserver/resources/runtime.scm
Labels: pull request: needs review, affects: master, regression, android

#3337 Fix procedure arguments becoming undefined in Blockly v10
  appinventor/blocklyeditor/src/blocks/procedures.js
Labels: pull request: needs review, affects: master, regression

#3334 Fix backpack rendering issue when extension blocks present
  appinventor/blocklyeditor/src/blocks/components.js
Labels: pull request: needs review, affects: master, regression

#3333 Reduce overly gratuitous refreshes of the companion app
  appinventor/appengine/src/com/google/appinventor/client/editor/youngandroid/YaBlocksEditor.java
  appinventor/appengine/src/com/google/appinventor/client/editor/youngandroid/events/EventHelper.java
  appinventor/blocklyeditor/src/generators/yail.js
Labels: pull request: needs review, affects: master, regression

#3338 Fix YaClientApp.uptodate computation to not include Blockly i18n
  appinventor/appengine/build.xml
Labels: pull request: needs review, affects: master, regression

#3339 Use addStyleName rather than setStyleName in GWT Trees
  appinventor/appengine/src/com/google/appinventor/client/explorer/SourceStructureExplorer.java
  appinventor/appengine/src/com/google/appinventor/client/wizards/MoveProjectsWizard.java
  appinventor/appengine/src/com/google/appinventor/client/wizards/NewFolderWizard.java
Labels: pull request: needs review, affects: master, regression

#3343 Fix insertion marker issues in logic_operation block
  appinventor/blocklyeditor/src/blocks/logic.js
  appinventor/lib/blockly/blockly_compressed.js
Labels: pull request: needs review, affects: master, regression

#3347 Fix alist to dict handling in iOS 2.73
  appinventor/schemekit/src/yail.m
Labels: bug, pull request: needs review, affects: ucr, testflight

#3323 Implement ReceivingState block for iOS
  appinventor/AIComponentKit.xcodeproj/project.pbxproj
  appinventor/components-ios/src/ReceivingState.swift
  appinventor/components-ios/src/Texting.swift
  appinventor/components-ios/src/runtime.scm
Labels: enhancement, pull request: needs review, affects: ucr, ios, testflight

#3355 Fix block changes not incrementally updating companion
  appinventor/appengine/src/com/google/appinventor/client/editor/youngandroid/YaBlocksEditor.java
  appinventor/appengine/src/com/google/appinventor/client/editor/youngandroid/events/EventHelper.java
Labels: pull request: needs review, affects: master, regression

#3352 Fix block workspace not saving after component deletion
  appinventor/appengine/src/com/google/appinventor/client/editor/simple/palette/ComponentRemoveWidget.java
  appinventor/appengine/src/com/google/appinventor/client/editor/youngandroid/YaBlocksEditor.java
  appinventor/appengine/src/com/google/appinventor/client/editor/youngandroid/events/EventHelper.java
  appinventor/blocklyeditor/src/blocklyeditor.js
Labels: pull request: needs review, affects: master, regression

#3350 Implement MicroBlocks extension for iOS
  appinventor/AIComponentKit.xcodeproj/project.pbxproj
  appinventor/components-ios/src/BluetoothLE.swift
  appinventor/components-ios/src/ErrorMessages.swift
  appinventor/components-ios/src/MicroBlocks.swift
  appinventor/schemekit/src/SCMNameResolver.m
  appinventor/schemekit/src/yail.m
Labels: pull request: needs review, feature request, affects: ucr, ios, testflight

#3212 FilePicker iOS
  appinventor/AIComponentKit.xcodeproj/project.pbxproj
  appinventor/components-ios/src/File.swift
  appinventor/components-ios/src/FileAction.swift
  appinventor/components-ios/src/FilePicker.swift
  appinventor/components-ios/src/FileType.swift
Labels: pull request: needs review, feature request, affects: ucr, ios, testflight
